(()=>{
const D=window.TRAVEL_DATA||{},G=window.TRAVEL_GUIDE||{},days=D.days||[],routes=D.routes||{},places=G.places||[];
const byId=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const mapsSearch=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q||''),xhsSearch=q=>'https://www.xiaohongshu.com/search_result?keyword='+encodeURIComponent(q||'');

/* navigation */
const tripStart=new Date((G.trip?.start||'2026-09-26')+'T00:00:00'),tripEnd=new Date((G.trip?.end||'2026-10-06')+'T23:59:59');
const now=new Date(),ymd=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const dateKeyToDay={};days.forEach(d=>{const [m,dd]=d.date.split('/');dateKeyToDay[`2026-${m.padStart(2,'0')}-${dd.padStart(2,'0')}`]=d.n});
const actualDay=dateKeyToDay[ymd(now)]||null,isTravelDay=!!actualDay;
function switchView(v,push=true){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));document.querySelectorAll('#appnav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(push&&location.hash!=='#'+v)history.replaceState(null,'','#'+v);if(v==='trip'&&map)setTimeout(()=>map.invalidateSize(),100)}
byId('appnav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)switchView(b.dataset.view)});
const hash=(location.hash||'').replace('#',''),initial=['trip','today','explore','prepare'].includes(hash)?hash:(isTravelDay?'today':'trip');switchView(initial,false);

/* trip view */
const dayHtml=d=>`<details class="day${d.cambodia?' cambodia':''}"${d.cambodia?' open':''}><summary><div class="badge"><span>${esc(d.date)}</span><b>D${d.n}</b></div><div class="dtext"><h3>${esc(d.title)}</h3><p>${esc(d.desc)}</p><span class="level">强度：${esc(d.level)}</span></div><div class="chev">⌄</div></summary><div class="timeline">${d.timeline.map(x=>`<div class="trow"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</div><div class="todos">${d.tags.map(x=>`<span class="tag ${esc(x[0])}">${esc(x[1])}</span>`).join('')}</div>${d.n===9?'<a class="special-link" href="./angkor/">打开吴哥专题 →</a>':''}</details>`;
byId('days').innerHTML=days.map(dayHtml).join('');
byId('p0list').innerHTML=(G.p0||[]).map(x=>`<div class="priitem"><div class="pritop"><b>${esc(x[0])}</b><span class="pribadge P0">P0</span></div><p>${esc(x[1])}</p></div>`).join('');
const done=[...new Set(days.flatMap(d=>d.tags.filter(t=>t[0]==='done').map(t=>t[1])))];byId('confirmed').innerHTML=done.map(x=>`<div class="conf"><span class="check">✓</span><span>${esc(x)}</span></div>`).join('');
const hotelByDay={1:'Grand Hyatt Bali',2:'Grand Hyatt Bali',3:'KLEO Seminyak',4:'KLEO Seminyak',5:'Manis ae',6:'Hotel Majapahit',7:'Dusit Thani Laguna',8:'Park Hyatt Siem Reap',9:'Jaya House River Park',10:'Larryta sleeper 夜巴',11:'返港'};
byId('triptable').innerHTML=`<table><thead><tr><th>日期</th><th>当天主线</th><th>住宿 / 夜间</th><th>强度</th></tr></thead><tbody>${days.map(d=>`<tr><td>${esc(d.date)} D${d.n}</td><td>${esc(d.title)}</td><td>${esc(hotelByDay[d.n]||'')}</td><td>${esc(d.level)}</td></tr>`).join('')}</tbody></table>`;

/* map with offline fallback */
let selected='D9',map=null,live=false,layers=[],tools=byId('maptools'),fallback=byId('mapFallback'),status=byId('mapstatus'),gmaps=byId('gmaps');
function routePoints(k){return k==='ALL'?Object.values(routes).flat():routes[k]||[]}
function bounds(pts){let a=pts.map(p=>p[0]),b=pts.map(p=>p[1]),mnA=Math.min(...a),mxA=Math.max(...a),mnB=Math.min(...b),mxB=Math.max(...b),pA=Math.max((mxA-mnA)*.2,.012),pB=Math.max((mxB-mnB)*.2,.012);return[mnA-pA,mxA+pA,mnB-pB,mxB+pB]}
function renderFallback(k){const pts=routePoints(k);if(!pts.length)return;const [mnA,mxA,mnB,mxB]=bounds(pts),W=800,H=520,pr=p=>[40+(p[1]-mnB)/(mxB-mnB)*(W-80),40+(mxA-p[0])/(mxA-mnA)*(H-80)];let poly=pts.map(p=>pr(p).map(v=>v.toFixed(1)).join(',')).join(' '),grid='';for(let x=100;x<W;x+=100)grid+=`<line x1="${x}" y1="0" x2="${x}" y2="${H}"/>`;for(let y=100;y<H;y+=100)grid+=`<line x1="0" y1="${y}" x2="${W}" y2="${y}"/>`;let marks='';pts.forEach(p=>{let [x,y]=pr(p),left=x<W*.72,dx=left?10:-10,anchor=left?'start':'end';marks+=`<circle cx="${x}" cy="${y}" r="7" fill="#0d6b5d" stroke="#fff" stroke-width="3"/><text x="${x+dx}" y="${y-10}" text-anchor="${anchor}" font-size="15" font-weight="700" fill="#173e35">${esc(p[2])}</text>`});fallback.innerHTML=`<svg viewBox="0 0 ${W} ${H}" aria-label="${esc(k)} route map"><rect width="${W}" height="${H}" fill="#edf5ef"/><g opacity=".3" stroke="#8bb4a8">${grid}</g><polyline points="${poly}" fill="none" stroke="#0d6b5d" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" opacity=".8"/>${marks}</svg>`}
function googleRoute(k){let p=routes[k]||[];if(!p.length)return'#';let o=p[0].slice(0,2).join(','),d=p[p.length-1].slice(0,2).join(','),w=p.slice(1,-1).slice(0,8).map(x=>x.slice(0,2).join(',')).join('|');return'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(o)+'&destination='+encodeURIComponent(d)+(w?'&waypoints='+encodeURIComponent(w):'')}
function clearMap(){if(!map)return;layers.forEach(l=>map.removeLayer(l));layers=[]}
function renderLeaflet(k){if(!live||!map)return;clearMap();let pts=routePoints(k),ll=pts.map(p=>[p[0],p[1]]),line=L.polyline(ll,{weight:4,opacity:.8,color:'#0d6b5d'}).addTo(map);layers.push(line);pts.forEach(p=>{let m=L.circleMarker([p[0],p[1]],{radius:7,color:'#fff',weight:2,fillColor:'#0d6b5d',fillOpacity:1}).bindPopup('<b>'+esc(p[2])+'</b>').addTo(map);layers.push(m)});if(ll.length>1)map.fitBounds(L.latLngBounds(ll),{padding:[30,30]});setTimeout(()=>map.invalidateSize(),100)}
function showRoute(k){selected=k;[...tools.children].forEach(b=>b.classList.toggle('active',b.dataset.k===k));renderFallback(k);gmaps.hidden=k==='ALL';if(k!=='ALL')gmaps.href=googleRoute(k);renderLeaflet(k)}
['ALL',...Object.keys(routes)].forEach(k=>{let b=document.createElement('button');b.textContent=k==='ALL'?'全部':k;b.dataset.k=k;b.onclick=()=>showRoute(k);tools.appendChild(b)});showRoute('D9');
function startLeaflet(){if(!window.L||map)return;try{map=L.map('map',{zoomControl:true}).setView([13.41,103.87],12);let tiles=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}),ok=false;tiles.on('tileload',()=>{if(ok)return;ok=true;live=true;byId('map').classList.add('live');status.textContent='交互地图';renderLeaflet(selected)});tiles.on('tileerror',()=>status.textContent='备用路线图');tiles.addTo(map);setTimeout(()=>{if(!ok)status.textContent='备用路线图'},3500)}catch(e){status.textContent='备用路线图'}}
function loadLeaflet(src,backup){let s=document.createElement('script');s.src=src;s.async=true;s.onload=startLeaflet;s.onerror=()=>backup&&loadLeaflet(backup,null);document.head.appendChild(s)}
loadLeaflet('https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js','https://unpkg.com/leaflet@1.9.4/dist/leaflet.js');

/* Travel Mode */
const aliases={
'Grand Hyatt Bali':'grand-hyatt-bali','Uluwatu':'uluwatu','Ubud':'ubud','Nusa Penida':'nusa-penida','Bromo':'bromo','Angkor National Museum':'angkor-museum','吴哥国家博物馆':'angkor-museum','Angkor Wat':'angkor-wat','吴哥窟':'angkor-wat','Ta Prohm':'ta-prohm','South Gate':'south-gate','Angkor Thom':'south-gate','Bayon':'bayon','Baphuon':'baphuon','Elephant Terrace':'elephant-terrace','APOPO':'apopo','Phare':'phare','Jaya House':'jaya-house','Old Market':'old-market'};
const placeMap=Object.fromEntries(places.map(p=>[p.id,p]));
function placeForText(text){for(const [k,id] of Object.entries(aliases))if(text.includes(k))return placeMap[id];return null}
function splitStop(text){const idx=text.indexOf('：');return idx>0?[text.slice(0,idx),text.slice(idx+1)]:[text,'']}
const daySelect=byId('daySelect');days.forEach(d=>{const o=document.createElement('option');o.value=d.n;o.textContent=`D${d.n} · ${d.date} · ${d.title}`;daySelect.appendChild(o)});
let previewDay=actualDay||(now<tripStart?1:11);daySelect.value=previewDay;
function renderToday(n){const d=days.find(x=>x.n===Number(n));if(!d)return;daySelect.value=d.n;const exact=actualDay===d.n,before=now<tripStart,after=now>tripEnd;byId('todayKicker').textContent=exact?'Today · Live':before?'旅行前预览':'Travel Mode';byId('todayTitle').textContent=`D${d.n} · ${d.title}`;byId('todayDate').textContent=d.date;byId('todayDesc').textContent=exact?'今天只需要按下面顺序执行；临时变化优先保证下一段交通。':before?'旅行还没开始。你可以切换日期，提前熟悉当天节奏。':after?'旅行已结束，这里保留为可复盘的每日执行视图。':'按当天行程执行。';
byId('liveList').innerHTML=d.timeline.map(x=>{const [title,detail]=splitStop(x[1]),p=placeForText(x[1]);return `<article class="live-stop"><div class="live-time">${esc(x[0])}</div><div class="live-main"><h3>${esc(title)}</h3>${detail?`<p>${esc(detail)}</p>`:''}${p&&p.tip?`<p>${esc(p.tip)}</p>`:''}<div class="stop-meta">${p?.duration?`<span class="meta-pill">建议 ${esc(p.duration)}</span>`:''}${p?.risk?`<span class="meta-pill">风险 ${esc(p.risk)}</span>`:''}${p?.photo?`<span class="meta-pill">有出片建议</span>`:''}</div>${p?.photo?`<div class="photo-tip">拍摄：${esc(p.photo)}</div>`:''}<div class="stop-actions">${p?`<a href="${mapsSearch(p.maps||p.name)}" target="_blank" rel="noopener">Google Maps</a><a class="secondary" href="${xhsSearch(p.xhs||p.name)}" target="_blank" rel="noopener">小红书</a>`:''}${d.n===9&&p?'<a class="secondary" href="./angkor/">吴哥专题</a>':''}</div></div></article>`}).join('');
const key=`D${d.n}`;byId('todayQuick').innerHTML=`<a href="${googleRoute(key)}" target="_blank" rel="noopener">打开今天完整 Google Maps 路线</a><a href="${xhsSearch(d.title)}" target="_blank" rel="noopener">小红书搜索今天玩法</a>${d.n===9?'<a href="./angkor/">打开吴哥一日专题</a>':''}<div class="quick-note">路线或开放情况临时变化时，先保住已购交通、酒店入住和下一段出发时间。</div>`;
let nearby=places.filter(p=>p.status==='optional'&&(p.day===d.n||(d.n>=8&&p.city==='Siem Reap'))).slice(0,4);if(!nearby.length)nearby=places.filter(p=>p.day===d.n&&p.status==='scheduled').slice(0,3);byId('todayNearby').innerHTML=nearby.map(p=>`<div class="mini"><b>${esc(p.name)}</b><p>${esc(p.tip||'顺路可考虑')}</p></div>`).join('')||'<div class="mini"><b>今天不加项目</b><p>按主线执行即可。</p></div>';
}
daySelect.addEventListener('change',()=>renderToday(daySelect.value));renderToday(previewDay);

/* Explore */
const filters=[['all','全部'],['attraction','景点'],['experience','体验'],['shopping','购物'],['hotel','酒店'],['optional','自由备选']];let activeFilter='all';const filterbar=byId('filterbar');filters.forEach(([k,l])=>{let b=document.createElement('button');b.textContent=l;b.dataset.filter=k;b.classList.toggle('active',k==='all');b.onclick=()=>{activeFilter=k;[...filterbar.children].forEach(x=>x.classList.toggle('active',x.dataset.filter===k));renderPlaces()};filterbar.appendChild(b)});
function renderPlaces(){let arr=places.filter(p=>activeFilter==='all'||(activeFilter==='optional'?p.status==='optional':p.type===activeFilter));byId('placeGrid').innerHTML=arr.map(p=>`<article class="place-card"><div class="place-top"><div><h3>${esc(p.name)}</h3><div class="area">${esc(p.city)} · ${esc(p.type)}</div></div><span class="status ${esc(p.status)}">${p.status==='scheduled'?'已排入日程':'自由选择'}</span></div><p>${esc(p.tip||'')}</p>${p.photo?`<div class="photo-tip">出片：${esc(p.photo)}</div>`:''}<div class="place-actions"><a href="${mapsSearch(p.maps||p.name)}" target="_blank" rel="noopener">Google Maps / 实时评分</a><a class="secondary" href="${xhsSearch(p.xhs||p.name)}" target="_blank" rel="noopener">小红书</a></div></article>`).join('')}
renderPlaces();
byId('experienceList').innerHTML=(G.experiences||[]).map(x=>`<div class="compact"><b>${esc(x.name)}</b><small>${esc(x.area)} · 风险 ${esc(x.risk)}</small><p>${esc(x.note)}</p></div>`).join('');
byId('foodList').innerHTML=(G.food||[]).map(x=>`<div class="compact"><b>${esc(x.name)}</b><small>${esc(x.area)} · ${esc(x.kind)}</small><p>${esc(x.note)}</p><a href="${mapsSearch(x.maps||x.name)}" target="_blank" rel="noopener">Google Maps →</a></div>`).join('');
byId('shoppingList').innerHTML=(G.shopping||[]).map(x=>`<div class="compact"><b>${esc(x.name)}</b><small>${esc(x.area)}</small><p>${esc(x.what)}</p><a href="${mapsSearch(x.maps||x.name)}" target="_blank" rel="noopener">Google Maps →</a></div>`).join('');

/* Prepare checklist */
const CHECK_KEY='project-bali-checklist-v1';let checks={};try{checks=JSON.parse(localStorage.getItem(CHECK_KEY)||'{}')}catch(e){}
function saveChecks(){try{localStorage.setItem(CHECK_KEY,JSON.stringify(checks))}catch(e){}}
function progress(){const all=document.querySelectorAll('#checkGroups input[type=checkbox]'),done=[...all].filter(x=>x.checked).length,pct=all.length?Math.round(done/all.length*100):0;byId('checkProgress').textContent=`${done}/${all.length} · ${pct}%`}
byId('checkGroups').innerHTML=(G.checklist||[]).map((g,gi)=>`<section class="checkgroup"><h3>${esc(g.group)}</h3>${g.items.map((it,ii)=>{const key=`${gi}-${ii}`,on=!!checks[key];return `<label class="checkrow${on?' checked':''}"><input type="checkbox" data-key="${key}"${on?' checked':''}><span>${esc(it)}</span></label>`}).join('')}</section>`).join('');
byId('checkGroups').addEventListener('change',e=>{if(!e.target.matches('input[type=checkbox]'))return;checks[e.target.dataset.key]=e.target.checked;e.target.closest('.checkrow').classList.toggle('checked',e.target.checked);saveChecks();progress()});progress();
byId('language').innerHTML=`<section class="langblock"><h3>Indonesia · Bahasa Indonesia</h3>${(G.language?.indonesia||[]).map(x=>`<div class="phrase"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</section><section class="langblock"><h3>Cambodia · 够用版</h3>${(G.language?.cambodia||[]).map(x=>`<div class="phrase"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</section>`;
byId('tipList').innerHTML=(G.tips||[]).map(x=>`<div class="tipitem">${esc(x)}</div>`).join('');
})();