(()=>{const D=window.TRAVEL_DATA||{},days=D.days||[],routes=D.routes||{},byId=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const dayHtml=d=>`<details class="day${d.cambodia?' cambodia':''}"${d.cambodia?' open':''}><summary><div class="badge"><span>${esc(d.date)}</span><b>D${d.n}</b></div><div class="dtext"><h3>${esc(d.title)}</h3><p>${esc(d.desc)}</p><span class="level">强度：${esc(d.level)}</span></div><div class="chev">⌄</div></summary><div class="timeline">${d.timeline.map(x=>`<div class="trow"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</div><div class="todos">${d.tags.map(x=>`<span class="tag ${x[0]}">${esc(x[1])}</span>`).join('')}</div></details>`;
byId('days').innerHTML=days.map(dayHtml).join('');
let selected='D9',map=null,live=false,layers=[],tools=byId('maptools'),fallback=byId('mapFallback'),status=byId('mapstatus'),gmaps=byId('gmaps');
function routePoints(k){return k==='ALL'?Object.values(routes).flat():routes[k]||[]}
function bounds(pts){let a=pts.map(p=>p[0]),b=pts.map(p=>p[1]),mnA=Math.min(...a),mxA=Math.max(...a),mnB=Math.min(...b),mxB=Math.max(...b),pA=Math.max((mxA-mnA)*.2,.012),pB=Math.max((mxB-mnB)*.2,.012);return[mnA-pA,mxA+pA,mnB-pB,mxB+pB]}
function renderFallback(k){const pts=routePoints(k);if(!pts.length)return;const [mnA,mxA,mnB,mxB]=bounds(pts),W=800,H=520,pr=p=>[40+(p[1]-mnB)/(mxB-mnB)*(W-80),40+(mxA-p[0])/(mxA-mnA)*(H-80)];let poly=pts.map(p=>pr(p).map(v=>v.toFixed(1)).join(',')).join(' '),grid='';for(let x=100;x<W;x+=100)grid+=`<line x1="${x}" y1="0" x2="${x}" y2="${H}"/>`;for(let y=100;y<H;y+=100)grid+=`<line x1="0" y1="${y}" x2="${W}" y2="${y}"/>`;let marks='';pts.forEach(p=>{let [x,y]=pr(p),left=x<W*.72,dx=left?10:-10,anchor=left?'start':'end';marks+=`<circle cx="${x}" cy="${y}" r="7" fill="#0d6b5d" stroke="#fff" stroke-width="3"/><text x="${x+dx}" y="${y-10}" text-anchor="${anchor}" font-size="15" font-weight="700" fill="#173e35">${esc(p[2])}</text>`});fallback.innerHTML=`<svg viewBox="0 0 ${W} ${H}" aria-label="${k} route map"><rect width="${W}" height="${H}" fill="#edf5ef"/><g opacity=".3" stroke="#8bb4a8">${grid}</g><polyline points="${poly}" fill="none" stroke="#0d6b5d" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" opacity=".8"/>${marks}</svg>`}
function googleLink(k){let p=routes[k]||[];if(!p.length)return'#';let o=p[0].slice(0,2).join(','),d=p[p.length-1].slice(0,2).join(','),w=p.slice(1,-1).slice(0,8).map(x=>x.slice(0,2).join(',')).join('|');return'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(o)+'&destination='+encodeURIComponent(d)+(w?'&waypoints='+encodeURIComponent(w):'')}
function clearMap(){if(!map)return;layers.forEach(l=>map.removeLayer(l));layers=[]}
function renderLeaflet(k){if(!live||!map)return;clearMap();let pts=routePoints(k),ll=pts.map(p=>[p[0],p[1]]),line=L.polyline(ll,{weight:4,opacity:.8,color:'#0d6b5d'}).addTo(map);layers.push(line);pts.forEach(p=>{let m=L.circleMarker([p[0],p[1]],{radius:7,color:'#fff',weight:2,fillColor:'#0d6b5d',fillOpacity:1}).bindPopup('<b>'+esc(p[2])+'</b>').addTo(map);layers.push(m)});if(ll.length>1)map.fitBounds(L.latLngBounds(ll),{padding:[30,30]});setTimeout(()=>map.invalidateSize(),100)}
function show(k){selected=k;[...tools.children].forEach(b=>b.classList.toggle('active',b.dataset.k===k));renderFallback(k);if(k==='ALL'){gmaps.hidden=true}else{gmaps.hidden=false;gmaps.href=googleLink(k)}renderLeaflet(k)}
['ALL',...Object.keys(routes)].forEach(k=>{let b=document.createElement('button');b.textContent=k==='ALL'?'全部':k;b.dataset.k=k;b.onclick=()=>show(k);tools.appendChild(b)});show('D9');
function startLeaflet(){if(!window.L||map)return;try{map=L.map('map',{zoomControl:true}).setView([13.41,103.87],12);let tiles=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}),ok=false;tiles.on('tileload',()=>{if(ok)return;ok=true;live=true;byId('map').classList.add('live');status.textContent='交互地图';renderLeaflet(selected)});tiles.on('tileerror',()=>status.textContent='备用路线图');tiles.addTo(map);setTimeout(()=>{if(!ok)status.textContent='备用路线图'},3500)}catch(e){status.textContent='备用路线图'}}
function load(src,backup){let s=document.createElement('script');s.src=src;s.async=true;s.onload=startLeaflet;s.onerror=()=>backup&&load(backup,null);document.head.appendChild(s)}
load('https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js','https://unpkg.com/leaflet@1.9.4/dist/leaflet.js');
})();