(()=>{
'use strict';
const D=window.TRAVEL_DATA||{days:[],routes:{}},G=window.TRAVEL_GUIDE||{places:[],checklist:[],language:{},tips:[]};
const days=D.days||[],routes=D.routes||{},places=G.places||[];
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)],byId=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLowerCase().replace(/[·｜|()（）/\\,，.。:：\-—_]/g,' ').replace(/\s+/g,' ').trim();
const toast=msg=>{const n=byId('toast');if(!n)return;n.textContent=msg;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('show'),1800)};
const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);
const XHS_WEB=q=>'https://www.xiaohongshu.com/search_result?keyword='+encodeURIComponent(q)+'&source=web_search_result_notes';
function openXhs(q){q=String(q||'').trim();if(!q)return;try{navigator.clipboard?.writeText(q)}catch(e){};toast('已复制小红书关键词：'+q);if(!mobile){window.open(XHS_WEB(q),'_blank','noopener');return}const deep='xhsdiscover://search/result?keyword='+encodeURIComponent(q);const started=Date.now();window.location.href=deep;setTimeout(()=>{if(document.visibilityState==='visible'&&Date.now()-started<2500)window.location.href=XHS_WEB(q)},950)}
const GOOGLE=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q||'');
const APPLE=(q,lat,lon)=>'https://maps.apple.com/?q='+encodeURIComponent(q||'')+(Number.isFinite(lat)&&Number.isFinite(lon)?'&ll='+lat+','+lon:'');
const aliases={
 'grand hyatt bali':'grand-hyatt-bali','uluwatu':'uluwatu','ubud':'ubud','nusa penida':'nusa-penida','bromo':'bromo','angkor national museum':'angkor-museum','吴哥国家博物馆':'angkor-museum','angkor wat':'angkor-wat','吴哥窟':'angkor-wat','ta prohm':'ta-prohm','塔普伦':'ta-prohm','south gate':'south-gate','angkor thom':'south-gate','bayon':'bayon','巴戎':'bayon','baphuon':'baphuon','elephant terrace':'elephant-terrace','apopo':'apopo','phare':'phare','jaya house':'jaya-house','old market':'old-market','kelingking':'kelingking','精灵坠崖':'kelingking','diamond beach':'diamond-beach','钻石沙滩':'diamond-beach','māua':'maua-penida','maua':'maua-penida','serangan':'serangan-marina','satcha':'satcha','banteay srei':'banteay-srei'};
const placeById=Object.fromEntries(places.map(p=>[p.id,p]));
function placeFor(name){const n=norm(name);for(const [k,id] of Object.entries(aliases))if(n.includes(norm(k))&&placeById[id])return placeById[id];return places.find(p=>{const pn=norm(p.name);return pn&&n&&(n.includes(pn)||pn.includes(n))})||null}
function routeFor(n){const base=(routes['D'+n]||[]).map((p,i)=>({lat:Number(p[0]),lon:Number(p[1]),name:p[2],orig:i}));let order=[];try{order=JSON.parse(localStorage.getItem('bali-route-order-D'+n)||'[]')}catch(e){}if(Array.isArray(order)&&order.length===base.length&&new Set(order).size===base.length)return order.map(i=>base[i]).filter(Boolean);return base}
function saveOrder(n,pts){localStorage.setItem('bali-route-order-D'+n,JSON.stringify(pts.map(p=>p.orig)))}
function routeGoogle(pts){if(!pts.length)return'#';if(pts.length===1)return GOOGLE(pts[0].name);const o=pts[0],d=pts[pts.length-1],w=pts.slice(1,-1).slice(0,8).map(p=>p.lat+','+p.lon).join('|');return'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(o.lat+','+o.lon)+'&destination='+encodeURIComponent(d.lat+','+d.lon)+(w?'&waypoints='+encodeURIComponent(w):'')}
function routeApple(pts){if(!pts.length)return'#';const o=pts[0],d=pts[Math.min(1,pts.length-1)];return'https://maps.apple.com/?saddr='+o.lat+','+o.lon+'&daddr='+d.lat+','+d.lon+'&dirflg=d'}
function routeSvg(pts){if(!pts.length)return'<div style="padding:24px">暂无路线</div>';let lats=pts.map(p=>p.lat),lons=pts.map(p=>p.lon),a=Math.min(...lats),b=Math.max(...lats),c=Math.min(...lons),d=Math.max(...lons),ys=Math.max(.001,b-a),xs=Math.max(.001,d-c),W=620,H=250;const xy=p=>[45+(p.lon-c)/xs*(W-90),H-35-(p.lat-a)/ys*(H-70)];const poly=pts.map(p=>xy(p).join(',')).join(' ');const marks=pts.map((p,i)=>{const [x,y]=xy(p);return`<g><circle cx="${x}" cy="${y}" r="12" fill="#173f36" stroke="#fff" stroke-width="3"/><text x="${x}" y="${y+4}" text-anchor="middle" font-size="10" font-weight="800" fill="#fff">${i+1}</text><text x="${x}" y="${y-18}" text-anchor="middle" font-size="11" font-weight="700" fill="#21332e">${esc(p.name)}</text></g>`}).join('');return`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="当日路线"><rect width="${W}" height="${H}" fill="#edf5ef"/><g opacity=".22" stroke="#8bb4a8">${[80,160,240,320,400,480,560].map(x=>`<line x1="${x}" y1="0" x2="${x}" y2="${H}"/>`).join('')}${[60,120,180].map(y=>`<line x1="0" y1="${y}" x2="${W}" y2="${y}"/>`).join('')}</g><polyline points="${poly}" fill="none" stroke="#197e8f" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>${marks}</svg>`}
function dayTimeFor(d,name,i){const nn=norm(name);const hit=(d.timeline||[]).find(x=>norm(x[1]).includes(nn.split(' ')[0])||nn.includes(norm(String(x[1]).split('：')[0])));return hit?hit[0]:((d.timeline||[])[Math.min(i,(d.timeline||[]).length-1)]||['时间待定'])[0]}
function dwell(p){return p?.duration||'按现场节奏'}
function exactXhs(p,name){return p?.xhs||name}
function mapActions(name,p,lat,lon){const q=p?.maps||name;return`<a href="${esc(GOOGLE(q))}" target="_blank" rel="noopener">Google Maps</a>${!/(hotel|airport|harbour|terminal)/i.test((p?.type||'')+' '+name)?`<button type="button" class="xhs-btn" data-xhs="${esc(exactXhs(p,name))}">小红书</button>`:''}`}
function wireXhs(root=document){$$('[data-xhs]',root).forEach(b=>{b.onclick=()=>openXhs(b.dataset.xhs)})}

/* framing */
const anchors=[['9/28','13:30 快船','Serangan → Banjar Nyuh'],['10/4','04:40 出发','Park Hyatt → Angkor Wat'],['10/5','约23:00 夜巴','Siem Reap → Phnom Penh'],['10/6','11:25 CX608','KTI → HKG']];
byId('timeAnchors').innerHTML=anchors.map(x=>`<div class="anchor"><small>${x[0]}</small><b>${x[1]}</b><span>${x[2]}</span></div>`).join('');
const chapters=[['01','每日行程','11 天主线、Mini Route、交通与时间锚点'],['02','景点','已排入与可选景点分开查看'],['03','购物','顺路市场、手工艺与伴手礼'],['04','体验','海岛、火山、SPA、表演与文化体验'],['05','餐饮','沿路线解决吃饭，保留代表性当地味道'],['06','行前准备','必须确认与装备清单，状态本机保存'],['07','语言','印尼语、高棉语与英语备用'],['08','当地须知','天气、礼仪、交通、安全与支付']];
byId('directoryGrid').innerHTML=chapters.map(x=>`<a class="dir-item" href="#ch${x[0]}"><b>${x[0]}</b><div><strong>${x[1]}</strong><span>${x[2]}</span></div></a>`).join('');
byId('chapterRail').innerHTML=chapters.map(x=>`<a href="#ch${x[0]}"><b>${x[0]}</b><span>${x[1]}</span></a>`).join('');

/* chapter 01 */
function renderDays(){byId('itineraryDays').innerHTML=days.map(d=>{const pts=routeFor(d.n);return`<details class="day-card" id="day-${d.n}" ${d.n===1?'open':''}><summary><div class="day-badge">D${d.n}</div><div class="day-copy"><h3>${esc(d.date)} · ${esc(d.title)}</h3><p>${esc(d.desc||'')}</p></div><span class="day-level">${esc(d.level||'')}</span></summary><div class="day-body"><div><div class="timeline">${(d.timeline||[]).map(x=>`<div class="trow"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</div>${d.n===3||d.n===4?'<div class="route-actions"><a class="secondary" href="./penida/">佩尼达专题</a></div>':''}${d.n===9?'<div class="route-actions"><a class="secondary" href="./angkor/">吴哥专题</a></div>':''}</div><div><div class="mini-route" data-mini-route="${d.n}">${routeSvg(pts)}</div><div class="route-actions"><a href="${routeGoogle(pts)}" target="_blank" rel="noopener">Google 今日路线</a><a class="secondary" href="${routeApple(pts)}" target="_blank" rel="noopener">Apple Maps</a></div><details class="customizer"><summary>调整当天站点顺序</summary><div data-customizer="${d.n}"></div></details></div></div></details>`}).join('');
$$('[data-customizer]').forEach(box=>renderCustomizer(Number(box.dataset.customizer),box))}
function renderCustomizer(n,box){const pts=routeFor(n);box.innerHTML=pts.map((p,i)=>`<div class="custom-row"><span>${i+1}. ${esc(p.name)}</span><button type="button" data-move="up" data-i="${i}" ${i===0?'disabled':''}>↑</button><button type="button" data-move="down" data-i="${i}" ${i===pts.length-1?'disabled':''}>↓</button></div>`).join('')+`<div class="route-actions"><button class="btn secondary" type="button" data-reset-order>恢复原顺序</button></div>`;box.onclick=e=>{const m=e.target.closest('[data-move]');if(m){const i=Number(m.dataset.i),arr=routeFor(n),j=m.dataset.move==='up'?i-1:i+1;[arr[i],arr[j]]=[arr[j],arr[i]];saveOrder(n,arr);renderDays();if(currentDay===n)renderTrip();return}if(e.target.closest('[data-reset-order]')){localStorage.removeItem('bali-route-order-D'+n);renderDays();if(currentDay===n)renderTrip()}}}
renderDays();

/* chapter 02 */
const sights=places.filter(p=>p.type==='attraction');
byId('sightGrid').innerHTML=sights.map(p=>`<article class="info-card ${p.status==='scheduled'?'scheduled':'optional'}"><div class="kicker">${p.status==='scheduled'?'已排入日程':'自由备选'}${p.day?' · D'+p.day:''}</div><h3>${esc(p.name)}</h3><p>${esc(p.tip||'按当天路线和体力决定。')}</p><div class="meta">${p.duration?`<span class="pill">${esc(p.duration)}</span>`:''}${p.risk?`<span class="pill">风险 ${esc(p.risk)}</span>`:''}</div><div class="card-actions">${mapActions(p.name,p)}</div></article>`).join('');

/* chapter 03 */
const shopping=[...(G.shopping||[]),...places.filter(p=>p.type==='shopping').map(p=>({name:p.name,area:p.city,what:p.tip,maps:p.maps,xhs:p.xhs}))];
const seen=new Set();const shoppingUnique=shopping.filter(x=>{const k=norm(x.name);if(seen.has(k))return false;seen.add(k);return true});
byId('shoppingGrid').innerHTML=shoppingUnique.map(x=>`<article class="info-card"><div class="kicker">${esc(x.area||'顺路购物')}</div><h3>${esc(x.name)}</h3><p>${esc(x.what||x.note||'顺路浏览，避免为购物额外折返。')}</p><div class="card-actions"><a href="${GOOGLE(x.maps||x.name)}" target="_blank" rel="noopener">Google Maps</a><button type="button" class="xhs-btn" data-xhs="${esc(x.xhs||x.name)}">小红书</button></div></article>`).join('');

/* chapter 04 */
byId('experienceGrid').innerHTML=(G.experiences||[]).map(x=>`<article class="info-card"><div class="kicker">${esc(x.area||'体验')}</div><h3>${esc(x.name)}</h3><p>${esc(x.note||'')}</p><div class="meta"><span class="pill">风险 ${esc(x.risk||'按现场')}</span></div><div class="card-actions"><a href="${GOOGLE(x.name+' '+(x.area||''))}" target="_blank" rel="noopener">Google Maps</a><button type="button" class="xhs-btn" data-xhs="${esc(x.name+' '+(x.area||''))}">小红书</button></div></article>`).join('');

/* chapter 05 */
const primer=[['巴厘岛 / 印尼','先看 rice / noodles / grilled / sambal；不吃辣直接说 “Tidak pedas”。'],['新加坡','熟食中心先找摊位再占位；热门时段减少跨区追餐厅。'],['柬埔寨','常见菜量适合分享；寺庙日午餐以出餐快、空调和补水优先。'],['整段旅程','高强度日不为餐厅跨城折返；酒店餐厅与顺路餐厅就是有效备选。']];
byId('foodPrimer').innerHTML=primer.map(x=>`<article class="info-card"><div class="kicker">MENU PRIMER</div><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');
const snacks=[['Pisang Goreng','巴厘岛 / 印尼','炸香蕉，适合作为咖啡或车程中的轻量甜点。'],['Lapis Surabaya','泗水','层次分明的当地蛋糕，适合少量尝试或带走。'],['Kaya Toast','新加坡','咖椰吐司配咖啡/奶茶，是落地或早晨最省力的一餐。'],['Num Pang','柬埔寨','法棍三明治类街头小吃，适合白天快速补充。']];
byId('snackGrid').innerHTML=snacks.map(x=>`<article class="info-card"><div class="kicker">LOCAL BITE · ${x[1]}</div><h3>${x[0]}</h3><p>${x[2]}</p><div class="card-actions"><button type="button" class="xhs-btn" data-xhs="${esc(x[0]+' '+x[1])}">小红书</button></div></article>`).join('');
byId('foodGrid').innerHTML=(G.food||[]).map(x=>`<article class="info-card"><div class="kicker">${esc(x.kind||'顺路吃')}</div><h3>${esc(x.name)}</h3><p>${esc(x.note||'')}</p><div class="meta"><span class="pill">${esc(x.area||'')}</span></div><div class="card-actions"><a href="${GOOGLE(x.maps||x.name)}" target="_blank" rel="noopener">Google Maps</a><button type="button" class="xhs-btn" data-xhs="${esc(x.name+' '+(x.area||''))}">小红书</button></div></article>`).join('');

/* chapter 06 */
function checkKey(g,i){return'project-bali-check:'+g+':'+i}
function renderChecklist(){let total=0,done=0;byId('checkGrid').innerHTML=(G.checklist||[]).map((g,gi)=>`<section class="check-group"><h3>${esc(g.group)}</h3>${(g.items||[]).map((x,i)=>{total++;const yes=localStorage.getItem(checkKey(gi,i))==='1';if(yes)done++;return`<label class="check-item"><input type="checkbox" data-check="${gi}:${i}" ${yes?'checked':''}><span>${esc(x)}</span></label>`}).join('')}</section>`).join('');byId('checkProgress').textContent=total?Math.round(done/total*100)+'%':'0%';$$('[data-check]').forEach(c=>c.onchange=()=>{const [g,i]=c.dataset.check.split(':');localStorage.setItem(checkKey(g,i),c.checked?'1':'0');renderChecklist()})}
renderChecklist();

/* chapter 07 */
const langGroups=[
 ['印尼语 · 基本礼貌',(G.language?.indonesia||[]).slice(0,5)],
 ['高棉语 / 当地沟通',(G.language?.cambodia||[]).slice(0,5)],
 ['英语备用 · 酒店',[["Could you store our luggage?","可以帮我们寄存行李吗？"],["Is late check-out available?","可以延迟退房吗？"],["Could we use the pool after check-out?","退房后还能使用泳池吗？"],["Please arrange a car for us.","请帮我们安排车辆。"],["Could we have a breakfast box?","可以准备早餐盒吗？"]]],
 ['英语备用 · 交通',[["Please take us to this address.","请带我们去这个地址。"],["What time should we arrive at the harbour?","我们几点前要到码头？"],["Is this the direct boat?","这是直达船吗？"],["Please stop here.","请在这里停车。"],["We need to go to KTI airport.","我们要去 KTI 机场。"]]],
 ['英语备用 · 餐厅与问题',[["No spicy, please.","请不要辣。"],["Could we have the bill?","请结账。"],["Can we pay by card?","可以刷卡吗？"],["We have a reservation under Meng.","我们有 Meng 名下的预约。"],["Could you help us with this?","可以帮我们处理这个吗？"]]]
];
byId('languageGrid').innerHTML=langGroups.map(g=>`<section class="lang-group"><h3>${g[0]}</h3>${g[1].map(x=>`<div class="lang-row"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</section>`).join('');

/* chapter 08 */
const notes=[
 ['天气与体感',[['海岛天气','巴厘岛和佩尼达的降雨与海况可能快速变化。出海前 48 小时复核海况，现场天气差就保船班和酒店，不硬塞水上项目。'],['Bromo 凌晨','火山日出时段明显比白天冷且风大。外套、长裤和口罩提前放到随手包，不要凌晨再翻大箱。'],['吴哥高温','吴哥日出后升温很快。早餐盒、饮水和轻薄长衣在早上就带齐，中午前结束核心寺庙。'],['雨天备选','雨天优先室内博物馆、酒店、SPA 和餐饮，不为了完成清单在湿滑悬崖或寺庙石阶赶路。']]],
 ['文化与礼仪',[['寺庙着装','吴哥宗教遗址准备遮肩、过膝衣物；轻薄透气优先，进入神圣区域时按现场标识执行。'],['拍摄边界','悬崖、寺庙高处和人流密集处都把安全位置放在构图前面。不跨护栏、不堵通道，也不要求陌生人配合摆拍。'],['酒店与服务','需要 late checkout、SPA 或接送时提前确认具体时间和费用。口头“可以”尽量让前台写到房间备注或消息里。'],['市场沟通','市场购买先确认总价和币种，再付款；不想买就礼貌结束，不为了砍价反复占用摊主时间。']]],
 ['当地交通',[['码头','快船日提前到港完成 check-in 和行李交接。不要把 Google Maps 的预计车程当成登船截止时间。'],['跨城车','SUB→Bromo、Bromo→泗水、SAI→市区这类长转场提前锁车，避免落地后现场议价影响后续入住。'],['吴哥司机','10/4 司机按已定四个核心点跑，不临时增加大圈。每离开一个点前确认下一站和集合位置。'],['金边机场','10/6 夜巴抵达后直接导航 Techo International Airport（KTI），不要使用旧 PNH 作为目的地。']]],
 ['安全与应急',[['悬崖','Kelingking 只做上方观景点；不要下海滩，不跨护栏。若到达晚，缩短停留而不是压缩返酒店车程。'],['海上交通','晕船或海况不佳时优先坐稳、补水并听船员安排；贵重物品和电子设备做好防水。'],['夜巴','上车前把护照、手机、充电宝和第二天登机需要的物品放随身小包，大箱进入行李舱后不再反复取。'],['证件备份','护照、航班、酒店、船票、夜巴确认单保存离线截图；手机没网时仍能给司机或工作人员查看。']]],
 ['支付与现金',[['币种','印尼以 IDR、新加坡以 SGD、柬埔寨常见 USD/KHR 场景。付款前先看清标价币种，避免只凭数字判断。'],['银行卡','酒店和大型商户优先用卡；小市场、司机、小额消费保留当地现金。不要把所有现金放在同一处。'],['换汇','旅行模式里的汇率是参考换算，可在线刷新也可手动输入；实际刷卡汇率以发卡行和交易入账为准。'],['共同记账','两个人的共同开销在 Travel Mode 里记录付款人和是否平分，结算只计算已录入项目，不替代银行卡账单。']]]
];
byId('localNotes').innerHTML=notes.map(n=>`<details class="fold"><summary>${n[0]}</summary><div class="fold-body">${n[1].map(x=>`<p><b>${x[0]}</b><br>${x[1]}</p>`).join('')}</div></details>`).join('');
wireXhs();

/* Trip Mode */
let currentDay=1,currentPage='itinerary',provider=localStorage.getItem('project-bali-map-provider')||'google',liveMap=null,liveLayers=[];
function placeUrl(stop){const p=placeFor(stop.name),q=p?.maps||stop.name;return provider==='apple'?APPLE(q,stop.lat,stop.lon):GOOGLE(q)}
function tripStopHtml(stop,i,d){const p=placeFor(stop.name),time=dayTimeFor(d,stop.name,i),hotel=/hotel|hyatt|jaya house|māua|maua|dusit|majapahit|manis/i.test(stop.name);return`<article class="trip-stop"><span class="trip-stop-no">${String(i+1).padStart(2,'0')}</span><time>${esc(time)} · ${esc(dwell(p))}</time><strong>${esc(stop.name)}</strong>${p?.practicalNote?`<p>${esc(p.practicalNote)}</p>`:(p?.tip?`<p>${esc(p.tip)}</p>`:'')} ${p?.timeGuard?`<div class="guard"><b>止损时间</b> ${esc(p.timeGuard)}</div>`:''}<div class="trip-stop-actions"><a class="map" href="${esc(placeUrl(stop))}" target="_blank" rel="noopener">${provider==='apple'?'Apple':'Google'}</a>${hotel?'':`<button class="xhs" type="button" data-xhs="${esc(exactXhs(p,stop.name))}">小红书</button>`}<span class="attachment-chips" data-vault-chips="${esc('D'+currentDay+':'+stop.orig+':'+stop.name)}"></span><button class="plus" type="button" data-vault-open="${esc('D'+currentDay+':'+stop.orig+':'+stop.name)}" data-vault-name="${esc(stop.name)}">＋</button></div></article>`}
function fallbackFor(d){if(d.n===3)return'如果船班或海况不理想，优先保留已确认船班和住宿；Kelingking 可缩短为上方观景台快速停留。';if(d.n===4)return'如果上午下雨或路况拖慢，只做 Diamond Beach 上方观景台，不下阶梯，并提前回 Banjar Nyuh。';if(d.n===9)return'如果日出后体力不足，保留 Angkor Wat、Ta Prohm、South Gate、Bayon，直接删除 Baphuon / Elephant Terrace。';if(d.n===10)return'如果两个人都累，APOPO 后留酒店休息；Phare 直接取消，优先保证洗澡、取行李和夜巴。';return'临时延误时先保住已购交通、酒店入住和下一段硬时间；普通景点可以缩短或删除。'}
function renderTrip(){const d=days.find(x=>x.n===currentDay)||days[0];if(!d)return;byId('tripTitle').textContent='D'+d.n+' · '+d.title;byId('tripSub').textContent=d.date+' · '+(d.level||'');byId('tripDayTabs').innerHTML=days.map(x=>`<button type="button" data-trip-day="${x.n}" class="${x.n===currentDay?'active':''}">D${x.n}</button>`).join('');$$('[data-trip-day]').forEach(b=>b.onclick=()=>{currentDay=Number(b.dataset.tripDay);renderTrip()});$$('[data-trip-page]').forEach(b=>b.classList.toggle('active',b.dataset.tripPage===currentPage));$$('.trip-page').forEach(p=>p.classList.toggle('active',p.id==='trip-'+currentPage));renderTripItinerary(d);renderTripMap(d);renderTripPhoto(d);renderLedger(d);wireXhs(byId('tripMode'));bindVaultButtons();}
function renderTripItinerary(d){const pts=routeFor(d.n);byId('trip-itinerary').innerHTML=`<div class="trip-intro"><small>${esc(d.date)} · 强度 ${esc(d.level||'')}</small><h3>${esc(d.title)}</h3><p>${esc(d.desc||'')}</p></div><details class="backup-card"><summary>备选方案</summary><div>${esc(fallbackFor(d))}</div></details>${pts.map((s,i)=>tripStopHtml(s,i,d)).join('')}`}
function renderTripMap(d){const pts=routeFor(d.n);byId('trip-map-page').innerHTML=`<div class="provider"><span>导航地图</span><button type="button" data-provider="google" class="${provider==='google'?'active':''}">谷歌地图</button><button type="button" data-provider="apple" class="${provider==='apple'?'active':''}">苹果地图</button></div><div class="route-actions"><a class="btn" href="${provider==='apple'?routeApple(pts):routeGoogle(pts)}" target="_blank" rel="noopener">打开今日导航 ↗</a></div><div class="trip-map" id="tripLiveMap"><div id="tripMapFallback">${routeSvg(pts)}</div></div><div class="route-strip">${pts.map((s,i)=>`<a href="${esc(placeUrl(s))}" target="_blank" rel="noopener"><b>${i+1}</b> ${esc(s.name)}</a>`).join('')}</div><p style="font-size:10px;color:#697b74;margin-top:8px">编号表示站点顺序；在线底图可用时自动叠加，导航以 Google / Apple Maps 为准。</p>`;$$('[data-provider]',byId('trip-map-page')).forEach(b=>b.onclick=()=>{provider=b.dataset.provider;localStorage.setItem('project-bali-map-provider',provider);renderTrip()});startTripLeaflet(pts)}
function startTripLeaflet(pts){if(liveMap){try{liveMap.remove()}catch(e){}liveMap=null}if(!window.L||!pts.length)return;try{liveMap=L.map('tripLiveMap',{zoomControl:true});const tiles=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'});let loaded=false;tiles.on('tileload',()=>{if(loaded)return;loaded=true;const f=byId('tripMapFallback');if(f)f.style.display='none'});tiles.addTo(liveMap);const ll=pts.map(p=>[p.lat,p.lon]);L.polyline(ll,{color:'#197e8f',weight:4,opacity:.8}).addTo(liveMap);pts.forEach((p,i)=>L.circleMarker([p.lat,p.lon],{radius:10,color:'#fff',weight:3,fillColor:'#173f36',fillOpacity:1}).bindTooltip(String(i+1),{permanent:true,direction:'center',className:'number-label'}).addTo(liveMap));liveMap.fitBounds(L.latLngBounds(ll),{padding:[28,28]})}catch(e){liveMap=null}}
function photoPlan(d){const pts=routeFor(d.n);let cards=[];pts.forEach(s=>{const p=placeFor(s.name);if(Array.isArray(p?.shootingPlan))cards.push(...p.shootingPlan.map(x=>({place:p.name,moment:x.moment,how:x.how})));else if(p?.photo)cards.push({place:p.name,moment:'拍摄建议',how:p.photo})});if(!cards.length)cards=[{place:d.title,moment:'当天记录',how:'先拍一张环境全景，再拍人物与交通/酒店细节；高强度日不为了拍照额外折返。'}];return cards.slice(0,3)}
function renderTripPhoto(d){const cards=photoPlan(d);byId('trip-photo').innerHTML=`${cards.map(x=>`<article class="shot-card"><b>${esc(x.moment)}</b><strong>${esc(x.place)}</strong><p>${esc(x.how)}</p></article>`).join('')}<div class="photo-vault"><b>参考样片 · 当前设备</b><p style="font-size:11px;color:#697b74">上传想模仿的机位、穿搭或构图；支持点开大图、单张删除和清空当天。</p><label class="btn secondary">＋ 上传参考图<input type="file" id="tripPhotoInput" accept="image/*" multiple hidden></label><button class="btn secondary" type="button" id="clearTripPhotos">清空本日</button><div class="photo-grid" id="tripPhotoGrid"></div></div>`;bindTripPhotos(d.n)}

/* IndexedDB: stop vault + reference photos */
const DB='project-bali-handbook-v3';
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,2);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('vault'))db.createObjectStore('vault',{keyPath:'id'});if(!db.objectStoreNames.contains('photos'))db.createObjectStore('photos',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function allStore(store){return openDb().then(db=>new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)}))}
function putStore(store,obj){return openDb().then(db=>new Promise((res,rej)=>{const r=db.transaction(store,'readwrite').objectStore(store).put(obj);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)}))}
function delStore(store,id){return openDb().then(db=>new Promise((res,rej)=>{const r=db.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)}))}
const fileData=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(f)});
async function renderVaultChips(key){const items=(await allStore('vault')).filter(x=>x.placeKey===key);$$('[data-vault-chips="'+CSS.escape(key)+'"]').forEach(c=>{c.innerHTML=items.slice(0,3).map(x=>`<button type="button" class="attachment-chip" data-vault-view="${esc(x.id)}">${esc(x.title||'资料')}</button>`).join('')});$$('[data-vault-view]').forEach(b=>b.onclick=()=>openVaultItem(b.dataset.vaultView))}
function bindVaultButtons(){$$('[data-vault-open]',byId('tripMode')).forEach(b=>{renderVaultChips(b.dataset.vaultOpen);b.onclick=()=>openVault(b.dataset.vaultOpen,b.dataset.vaultName)})}
let vaultKey='',vaultName='';
async function openVault(key,name){vaultKey=key;vaultName=name;byId('vaultTitle').textContent=name+' · 资料仓';byId('vaultModal').classList.add('open');byId('vaultName').value='';byId('vaultUrl').value='';byId('vaultFile').value='';await renderVaultList()}
async function renderVaultList(){const items=(await allStore('vault')).filter(x=>x.placeKey===vaultKey).sort((a,b)=>a.createdAt-b.createdAt);byId('vaultList').innerHTML=items.length?items.map(x=>`<div class="custom-row"><button type="button" style="width:auto;padding:0 8px" data-vault-view="${esc(x.id)}">${esc(x.title||x.fileName||'资料')}</button><button type="button" data-vault-rename="${esc(x.id)}">✎</button><button type="button" data-vault-delete="${esc(x.id)}">×</button></div>`).join(''):'<p style="font-size:12px;color:#697b74">还没有保存资料。</p>';$$('[data-vault-view]',byId('vaultList')).forEach(b=>b.onclick=()=>openVaultItem(b.dataset.vaultView));$$('[data-vault-delete]').forEach(b=>b.onclick=async()=>{await delStore('vault',b.dataset.vaultDelete);await renderVaultList();renderVaultChips(vaultKey)});$$('[data-vault-rename]').forEach(b=>b.onclick=async()=>{const items=await allStore('vault'),x=items.find(i=>i.id===b.dataset.vaultRename);if(!x)return;const n=prompt('按钮名称',x.title||'资料');if(n){x.title=n.trim();await putStore('vault',x);await renderVaultList();renderVaultChips(vaultKey)}})}
async function openVaultItem(id){const x=(await allStore('vault')).find(i=>i.id===id);if(!x)return;if(x.dataUrl){const pv=byId('vaultPreview');pv.innerHTML=x.mime?.startsWith('image/')?`<img src="${esc(x.dataUrl)}" alt="${esc(x.title)}" style="width:100%;max-height:52vh;object-fit:contain">`:`<iframe src="${esc(x.dataUrl)}" style="width:100%;height:52vh;border:0"></iframe>`;return}if(x.url){if(/^https?:\/\//i.test(x.url))window.open(x.url,'_blank','noopener');else{try{await navigator.clipboard.writeText(x.url);toast('内容已复制')}catch(e){}}}}
byId('vaultClose').onclick=()=>{byId('vaultModal').classList.remove('open');byId('vaultPreview').innerHTML=''};byId('vaultCancel').onclick=byId('vaultClose').onclick;
byId('vaultSave').onclick=async()=>{const title=byId('vaultName').value.trim()||'资料',url=byId('vaultUrl').value.trim(),file=byId('vaultFile').files[0];if(!url&&!file){toast('请粘贴链接/分享文字或上传文件');return}if(file&&file.size>20*1024*1024){toast('单个附件上限 20 MB');return}let dataUrl=null,mime='';if(file){dataUrl=await fileData(file);mime=file.type}await putStore('vault',{id:'v-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),placeKey:vaultKey,placeName:vaultName,title,url,dataUrl,mime,fileName:file?.name||'',createdAt:Date.now()});byId('vaultName').value='';byId('vaultUrl').value='';byId('vaultFile').value='';await renderVaultList();renderVaultChips(vaultKey);toast('已保存到当前设备')};
async function bindTripPhotos(day){const grid=byId('tripPhotoGrid'),input=byId('tripPhotoInput'),clear=byId('clearTripPhotos');async function draw(){const arr=(await allStore('photos')).filter(x=>x.day===day).sort((a,b)=>a.createdAt-b.createdAt);grid.innerHTML=arr.length?arr.map(x=>`<figure data-photo="${esc(x.id)}"><img src="${esc(x.dataUrl)}" alt="参考样片"><button type="button" aria-label="删除">×</button></figure>`).join(''):'<p style="grid-column:1/-1;font-size:11px;color:#697b74">还没有参考样片。</p>';$$('figure',grid).forEach(f=>{const img=$('img',f),del=$('button',f);img.onclick=()=>showPhoto(img.src);del.onclick=async e=>{e.stopPropagation();await delStore('photos',f.dataset.photo);draw()}})}input.onchange=async()=>{const files=[...input.files].filter(f=>f.type.startsWith('image/')).slice(0,6);for(const [i,f] of files.entries()){await putStore('photos',{id:'p-'+Date.now()+'-'+i+'-'+Math.random().toString(36).slice(2,6),day,name:f.name,dataUrl:await fileData(f),createdAt:Date.now()+i})}input.value='';draw();toast('样片已保存到当前设备')};clear.onclick=async()=>{const arr=(await allStore('photos')).filter(x=>x.day===day);await Promise.all(arr.map(x=>delStore('photos',x.id)));draw()};draw()}
function showPhoto(src){byId('photoViewerImg').src=src;byId('photoViewer').classList.add('open')}byId('photoViewer').onclick=e=>{if(e.target===byId('photoViewer')||e.target.closest('[data-close-photo]')){byId('photoViewer').classList.remove('open');byId('photoViewerImg').src=''}};

/* ledger + FX */
const ledgerKey='project-bali-ledger';const ledger=()=>{try{return JSON.parse(localStorage.getItem(ledgerKey)||'[]')}catch(e){return[]}};const saveLedger=x=>localStorage.setItem(ledgerKey,JSON.stringify(x));
function currencyFor(day){if(day<=6)return'IDR';if(day===7)return'SGD';return'USD'}
function fxCacheKey(c){return'project-bali-fx:'+c+':CNY'}
async function refreshFx(c){try{const r=await fetch('https://open.er-api.com/v6/latest/'+encodeURIComponent(c));if(!r.ok)throw 0;const j=await r.json(),rate=Number(j?.rates?.CNY);if(!rate)throw 0;localStorage.setItem(fxCacheKey(c),JSON.stringify({rate,date:j.time_last_update_utc||new Date().toISOString()}));renderFx(currentDay);toast('参考汇率已刷新')}catch(e){toast('在线汇率刷新失败，可手动输入')}}
function renderFx(day){const c=currencyFor(day);let cache={};try{cache=JSON.parse(localStorage.getItem(fxCacheKey(c))||'{}')}catch(e){}const manual=localStorage.getItem(fxCacheKey(c)+':manual')||'',rate=Number(manual||cache.rate||0);byId('fxBox').innerHTML=`<details class="fx-box"><summary><b>汇率换算 · ${c} → CNY</b></summary><div class="fx-row"><input id="fxAmount" type="number" inputmode="decimal" placeholder="${c} 金额"><input id="fxResult" readonly placeholder="CNY 结果"></div><div class="fx-row"><input id="fxRate" type="number" inputmode="decimal" step="any" value="${rate||''}" placeholder="1 ${c} = ? CNY"><button class="btn secondary" id="fxRefresh" type="button">刷新参考汇率</button></div><p style="font-size:10px;color:#697b74;margin:6px 0 0">参考日期：${esc(cache.date||'待刷新')}；可手动改汇率，本页换算不改写记账。</p></details>`;const amount=byId('fxAmount'),rr=byId('fxRate'),out=byId('fxResult');const calc=()=>{const r=Number(rr.value)||0,a=Number(amount.value)||0;out.value=r&&a?(a*r).toFixed(2):''};amount.oninput=calc;rr.oninput=()=>{localStorage.setItem(fxCacheKey(c)+':manual',rr.value);calc()};byId('fxRefresh').onclick=()=>refreshFx(c)}
function renderLedger(d){if(!byId('trip-ledger'))return;byId('trip-ledger').innerHTML=`<div id="fxBox"></div><div class="ledger-box"><b>旅行记账 · 当前设备</b><div class="ledger-form"><input id="ledDesc" class="full" placeholder="项目，例如 晚餐 / Grab"><input id="ledAmount" type="number" inputmode="decimal" placeholder="金额"><select id="ledCurrency"><option>IDR</option><option>SGD</option><option>USD</option><option>CNY</option></select><select id="ledPayer"><option value="me">我付款</option><option value="partner">同行人付款</option></select><select id="ledSplit"><option value="equal">两人平分</option><option value="personal">付款人个人</option></select><button class="btn full" id="ledAdd" type="button">记一笔</button></div><div class="ledger-list" id="ledgerList"></div><div class="settlement" id="settlement"></div></div>`;byId('ledCurrency').value=currencyFor(d.n);renderFx(d.n);function draw(){const arr=ledger();byId('ledgerList').innerHTML=arr.length?arr.slice().reverse().map(x=>`<div class="ledger-item"><div><b>${esc(x.desc)}</b><br><span>${esc(x.currency)} ${Number(x.amount).toLocaleString()} · ${x.payer==='me'?'我付款':'同行人付款'} · ${x.split==='equal'?'平分':'个人'}</span></div><button type="button" data-led-del="${esc(x.id)}">×</button></div>`).join(''):'<p style="font-size:11px;color:#697b74">还没有记录开销。</p>';let balance=0;arr.filter(x=>x.split==='equal').forEach(x=>{const a=Number(x.amount)||0;if(x.currency!=='CNY')return;if(x.payer==='me')balance+=a/2;else balance-=a/2});byId('settlement').textContent=balance>0?'按已录入的 CNY 平分项目：同行人应还我 ¥'+balance.toFixed(2):balance<0?'按已录入的 CNY 平分项目：我应还同行人 ¥'+Math.abs(balance).toFixed(2):'当前 CNY 平分项目暂无待结算金额。';$$('[data-led-del]').forEach(b=>b.onclick=()=>{saveLedger(ledger().filter(x=>x.id!==b.dataset.ledDel));draw()})}byId('ledAdd').onclick=()=>{const desc=byId('ledDesc').value.trim(),amount=Number(byId('ledAmount').value);if(!desc||!amount){toast('请填写项目和金额');return}const arr=ledger();arr.push({id:'l-'+Date.now(),day:d.n,desc,amount,currency:byId('ledCurrency').value,payer:byId('ledPayer').value,split:byId('ledSplit').value,createdAt:Date.now()});saveLedger(arr);byId('ledDesc').value='';byId('ledAmount').value='';draw()};draw()}

/* trip shell */
byId('tripLaunch').onclick=()=>{byId('tripMode').classList.add('open');document.body.style.overflow='hidden';renderTrip()};byId('tripClose').onclick=()=>{byId('tripMode').classList.remove('open');document.body.style.overflow='';if(liveMap){try{liveMap.remove()}catch(e){}liveMap=null}};
$$('[data-trip-page]').forEach(b=>b.onclick=()=>{currentPage=b.dataset.tripPage;renderTrip()});

/* Leaflet lazy loader */
if(!window.L){const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js';s.async=true;s.onerror=()=>{const b=document.createElement('script');b.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';b.async=true;document.head.appendChild(b)};document.head.appendChild(s)}

/* automatic trip day */
const now=new Date(),key=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');days.forEach(d=>{const [m,dd]=d.date.split('/');if(key===`2026-${m.padStart(2,'0')}-${dd.padStart(2,'0')}`)currentDay=d.n});
wireXhs();
})();