import {PERSONAS} from '../content/personas';
import {scores,milestones,ACTIVITIES} from '../core/progression';
import type {Store,Command,Department} from '../state/types';
import {rooms,availableSuites,occupiedRooms} from '../state/selectors';
import {ROOM_STATUS} from '../content/place';
import {queue,weekday,clock,demand,DEPARTMENTS} from '../core/game';
import './gameplay.css';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(v:number)=>'¥'+Math.round(v).toLocaleString('en-US');
const action=(label:string,type:string,id='',value='')=>`<button class="game-action" data-action="${esc(type)}" data-id="${esc(id)}" data-value="${esc(value)}">${esc(label)}</button>`;
export function mountGameplay(root:HTMLElement,store:Store){
 const $=(q:string)=>root.querySelector<HTMLElement>(q)!;const dialog=root.querySelector<HTMLDialogElement>('dialog')!,content=$('#sheet-content'),eye=$('#sheet-eye');let view='',selected='',logFilter='全部',focusFloor:(id:string)=>void=()=>{},previousFocus:HTMLElement|null=null;
 $('.preview-badge').outerHTML='<button class="preview-badge score-button" data-open="score" aria-label="查看经营评分"></button>';$('.world-caption').textContent='轻点空间 · 处理今天的经营';$('.weather').title='切换日夜预览';
 $('.property-name small').id='game-time';$('.today-hint').setAttribute('data-open','tasks');$('.event-strip').removeAttribute('data-focus');$('.event-strip').setAttribute('data-open','events');
 $('.speed-control').insertAdjacentHTML('beforeend',action('Ⅱ','pause'));$('.speed-control').setAttribute('aria-label','经营速度');
 root.querySelectorAll('[data-speed]').forEach(el=>el.setAttribute('aria-label',el.getAttribute('data-speed')+'倍经营速度'));
 const close=()=>{view='';selected='';dialog.close();store.select(null);previousFocus?.focus();};
 const show=(title:string,body:string)=>{eye.textContent=title;content.innerHTML=body;if(!dialog.open){previousFocus=document.activeElement as HTMLElement;dialog.showModal();}};
 const roomView=(id:string)=>{const s=store.getState(),e=s.entities[id];if(!e)return;
  if(e.kind==='room'){const guest=s.guests.find(g=>g.id===e.guestId);show('HYATT PLACE · '+s.floors.find(f=>f.id===e.floorId)?.label,`<h2>${esc(e.number)}<span>${e.type==='suite'?'开放式套房':e.type==='twin'?'双床客房':'大床客房'} · Lv.${e.level??1}</span></h2><div class="status-chip">${ROOM_STATUS[e.status]}${e.timer?' · 还需 '+e.timer+' 分钟':''}</div><dl><div><dt>住客</dt><dd>${guest?esc(guest.name)+' · '+esc(guest.tier):'暂无'}</dd></div><div><dt>剩余住宿</dt><dd>${e.nightsLeft} 晚</dd></div><div><dt>每晚房费</dt><dd>${guest?money(guest.rate??s.game!.price):money(s.game!.price)+' 起'}</dd></div></dl>${guest?'<p>'+PERSONAS[guest.persona??'chill'].name+(guest.goh?' · GOH':'')+(guest.sua?' · SUA':'')+'</p><blockquote>'+esc(guest.thought)+'</blockquote>'+(!guest.serviceDone?action(({road:'安排发票与行程',family:'加床与早餐确认',points:'核对 QN 与 bonus',hunter:'一起核对套房库存',forum:'确认房型口径',creator:'安排拍摄与欢迎饮品',proposal:'安排求婚布置',planner:'安排团队动线考察',whale:'安排专属接待',auditplus:'安排客房巡检',chill:'补充饮水与用品'}[guest.persona??'chill'])+' ¥120','guest-service',guest.id):'<small>本次住宿已安排专属服务</small>')+(guest.late==='pending'?action('确认 4PM','late',guest.id,'honor')+action('协商 14:00','late',guest.id,'deny'):guest.late?'<p>退房时间：'+(guest.late==='honor'?'16:00':'14:00')+'</p>':''):''}<div class="action-row">${e.status==='dirty'?action('安排清洁 ¥90','clean',id):''}${e.status==='maintenance'&&!e.timer?action('安排维修 ¥180','repair',id):''}${e.status==='available'?(action('分配给住客','front')+((e.level??1)<5?action('装修 '+money(2500*(e.level??1)),'upgrade',id):'')+(e.type==='suite'?action('预留给会员','reserve',id):'')):''}${e.status==='reserved'?action('释放预留','release',id):''}</div>`);
  }else show('HYATT PLACE · 公共空间',`<h2>${esc(e.name)}</h2><dl><div><dt>使用 / 容量</dt><dd>${e.usage} / ${e.capacity}</dd></div><div><dt>维护状况</dt><dd>${Math.round(e.maintenance)}%</dd></div>${['breakfast','club'].includes(e.role)?`<div><dt>库存</dt><dd>${e.role==='club'?s.game!.clubStock:s.game!.stock} 份</dd></div>`:''}</dl><div class="action-row">${e.role==='lobby'?action('办理入住','front'):''}${e.role==='breakfast'?action('补充早餐 ¥300','stock','breakfast'):e.role==='club'?action('补充酒廊 ¥300','stock','club'):''}${action('维护设施 ¥200','repair',e.id)}${(e.level??1)<5?action('公区升级 '+money(3500*(e.level??1)),'invest',e.id):'已达 Lv.5'}</div>`);
  if(view&&s.game!.notice)content.insertAdjacentHTML('beforeend',`<p class="action-feedback">${esc(s.game!.notice)}</p>`);
 };
 const render=()=>{const s=store.getState(),g=s.game!;
  if(view==='entity'){roomView(selected);return;}
  if(view==='front')show('FRONT OFFICE',`<h2>前台 · ${queue(s).length} 位等候</h2><p>会员升套使用普通房价；房费日结入账。面板打开时经营暂停。</p>${queue(s).map(guest=>{const available=rooms(s).filter(r=>r.status==='available'||r.status==='reserved'&&guest.tier==='Globalist').sort((a,b)=>guest.tier==='Globalist'?Number(b.type==='suite')-Number(a.type==='suite'):Number(a.type==='suite')-Number(b.type==='suite'));return `<section class="guest-card"><strong>${esc(guest.name)} · ${esc(guest.tier)}</strong><blockquote>${esc(guest.thought)}</blockquote><p>${PERSONAS[guest.persona??'chill'].name}${guest.goh?' · GOH':''}${guest.sua?' · SUA':''} · ${esc(guest.segment)} · ${guest.stayLength} 晚 · 等候耐心 ${guest.patience} 分钟</p>${available.length?`<select aria-label="为${esc(guest.name)}选择房间" id="assign-${esc(guest.id)}">${available.map(r=>`<option value="${r.id}">${r.number} · ${r.type==='suite'?'套房':r.type==='twin'?'双床':'大床'}${guest.tier==='Globalist'&&r.type==='suite'?' · 免费升套':''}</option>`).join('')}</select>${action('确认入住','checkin',guest.id)}`:'<p>暂无可用房间：先清洁脏房或扩建。</p>'}${action('婉拒','reject',guest.id)}</section>`}).join('')||'<p class="empty">暂时没有排队住客，关上面板继续经营。</p>'}`);
  else if(view==='hotel')show('YOUR HOTEL',`<h2>酒店 · ${rooms(s).length} 间客房</h2><p>已解除 21 间客房上限，继续向上扩建；公区和屋顶同步上移。更多客房也会吸引更多客流。</p>${action('新增三间客房 '+money(10000+5000*(s.floors.filter(f=>f.role==='guest').length-3)),'expand')}<div class="action-row"><button class="game-action" data-open="development">投资与主题活动 ›</button></div><div class="floor-list">${[...s.floors].reverse().map(f=>`<button data-floor="${f.id}"><b>${f.label}</b><span>${f.name}</span><small>定位楼层 ›</small></button>`).join('')}</div><div class="room-grid">${rooms(s).map(r=>`<button data-entity="${r.id}">${r.number}<small>${ROOM_STATUS[r.status]}</small></button>`).join('')}</div><p class="phase-note">其他品牌需有独立空间与美术，目前尚未开放。</p>`);
  else if(view==='operations')show('OPERATIONS',`<h2>经营与授权</h2><button class="primary" data-open="development">投资、营销与主题活动 ›</button><p>${weekday(g.day)} · 预计需求 ${Math.round(demand(s)*100)}% · ${g.weather==='rain'?'有雨':'晴朗'}</p><div class="action-row">${action('早餐 +50 ¥300','stock','breakfast')}${action('酒廊 +50 ¥300','stock','club')}</div><p>库存：早餐 ${g.stock} · 酒廊 ${g.clubStock}</p><label>新客挂牌价 <input id="price-input" type="number" min="350" max="1800" step="50" value="${g.price}"></label>${action('调整价格','price')}<label>经营定位 <select id="position-input"><option value="business" ${g.positioning==='business'?'selected':''}>商务 / 机场</option><option value="resort" ${g.positioning==='resort'?'selected':''}>休闲 / 度假</option><option value="urban" ${g.positioning==='urban'?'selected':''}>城市混合</option></select></label>${action('调整定位','position')}<h3>部门负责人</h3><p>聘任 ¥3,800，每日工资 ¥180。客房自动翻房、工程自动维修、餐饮自动补货、前厅自动分房、收益自动定价。培训后：前厅耐心更长、客房与维修更快、餐饮采购更便宜、收益定价更积极；每级每日工资 ¥180。</p>${Object.entries(DEPARTMENTS).map(([id,name])=>`<div class="department"><span>${name}主管</span>${g.managers[id as Department]?`<span>Lv.${g.managers[id as Department]} ${g.managers[id as Department]<3?action('培训 '+money(4500*g.managers[id as Department]),'train',id):'已满级'}</span>`:action('聘任','hire',id)}</div>`).join('')}<div class="action-row">${action('最近日结','report')}${action('导出存档','export')}${action('新开存档','reset')}</div><p class="phase-note">自动保存于当前浏览器。旧版存档不受影响。非官方粉丝游戏，与 Hyatt 无隶属关系。</p>`);
  else if(view==='development'){const d=g.development;show('GROW YOUR HOTEL',`<h2>投资与新体验</h2><p>扩建之外，让每一层创造更多收入。客房可装修至 5 级，每级提升新客房价 10%。</p><h3>三日营销</h3><p>客流 +35%；推广持续到第 ${d?.campaignUntil??0} 天。满房时请谨慎投放。</p>${d&&d.campaignUntil>=g.day?'<small>推广进行中</small>':action('投放推广 ¥2,200','campaign')}<h3>今日主题活动</h3><p>每天一场，筹备两小时。参与人数取决于在住人数、公区容量与经营条件；成本可能高于收入。</p>${d?.activity?`<blockquote>正在筹备：${ACTIVITIES[d.activity.id as keyof typeof ACTIVITIES].name} · 还需 ${Math.max(0,d.activity.ends-g.day*1440-g.minute)} 分钟</blockquote>`:''}${Object.entries(ACTIVITIES).map(([id,a])=>`<section class="guest-card"><strong>${a.name}</strong><p>${a.description} 每人消费 ¥${a.fee} 起。</p>${d?.activityDay===g.day?'<small>今日档期已使用</small>':action('安排 '+money(a.cost),'activity',id)}</section>`).join('')}<h3>公共空间投资</h3>${!s.entities['facility-spa']?action('开设 Spa 水疗 ¥12,000','build-spa'):''}<p>每级增加 4 人容量，餐饮、健身与屋顶消费单价提升 20%，住客体验更好；大堂升级增加等候耐心。</p>${Object.values(s.entities).filter(e=>e.kind==='facility').map(f=>`<section class="guest-card"><strong>${esc(f.name)} · Lv.${f.level??1}</strong><p>容量 ${f.capacity} 人 · 维护 ${Math.round(f.maintenance)}%</p>${(f.level??1)<5?action('升级 '+money(3500*(f.level??1)),'invest',f.id):'<small>满级</small>'}</section>`).join('')}<button class="game-action" data-open="hotel">装修客房 / 继续扩建 ›</button><button class="game-action" data-open="operations">培训部门负责人 ›</button>`);}
  else if(view==='score'){const rating=scores(s);show('HOTEL SCORE',`<h2>酒店经营评分</h2><div class="score-hero"><div class="score-ring" style="--score:${rating.total}%"><strong>${rating.total}<small>/ 100</small></strong></div><div><strong>${rating.total>=90?'卓越酒店':rating.total>=75?'稳健经营':rating.total>=60?'成长中':'需要改善'}</strong><p>四项指标等权平均，实时更新。</p></div></div>${rating.parts.map(p=>`<div class="score-part"><span>${p.name}</span><b>${p.value}</b><progress max="100" value="${p.value}" aria-label="${p.name}"></progress></div>`).join('')}<p>及时处理诉求提升口碑；补货与活动改善体验；清洁维修改善房务；收支表现影响业主信心。</p><h3>最近 7 天评分</h3><div class="revenue-trend">${(g.development?.scores??[]).slice(-7).map(p=>`<div><small>${p.value} 分</small><i style="height:${p.value*.65}px"></i><small>D${p.day}</small></div>`).join('')||'<p>首次日结后记录评分趋势。</p>'}</div><button class="game-action" data-open="tasks">查看任务与里程碑 ›</button>`);}
  else if(view==='tasks')show('MISSIONS',`<h2>今日任务</h2><p>每天轮换经营目标，完成后及时领奖。长期里程碑不会随交班重置。</p>${g.tasks.map(t=>`<section class="guest-card"><strong>${esc(t.title)}</strong><p>${t.progress} / ${t.goal} · 奖励 ${money(t.reward)}</p><progress max="${t.goal}" value="${t.progress}" aria-label="${esc(t.title)}"></progress>${t.claimed?'<small>已领取</small>':t.progress>=t.goal?action('领取奖励','claim',t.id):`<button class="game-action" data-open="${t.target}">去完成 ›</button>`}</section>`).join('')}<h3>长期里程碑</h3><p>累计接待与活动次数从本次升级开始记录；已有客房与部门等级直接计入。</p>${milestones(s).map(t=>`<section class="guest-card"><strong>${t.title}</strong><p>${Math.min(t.progress,t.goal)} / ${t.goal} · ${money(t.reward)}</p><progress max="${t.goal}" value="${Math.min(t.progress,t.goal)}" aria-label="${t.title}"></progress>${t.claimed?'<small>已领取</small>':t.progress>=t.goal?action('领取里程碑奖励','claim-career',t.id):'<small>持续经营以解锁</small>'}</section>`).join('')}`);
  else if(view==='events')show('DUTY MANAGER',`<h2>待办 · ${g.events.length+s.guests.filter(v=>v.late==='pending').length}</h2>${s.guests.filter(v=>v.late==='pending'&&!v.departing).map(v=>`<section class="guest-card"><strong>${esc(v.name)} · 4PM 请求</strong><p>${PERSONAS[v.persona??'chill'].name}：晚退意味着翻房窗口更紧。</p>${action('确认 4PM','late',v.id,'honor')}${action('协商 14:00','late',v.id,'deny')}</section>`).join('')}${g.events.map(e=>`<section class="guest-card"><strong>${esc(e.title)}</strong><p>剩余 ${Math.max(0,e.expires-g.day*1440-g.minute)} 游戏分钟</p><div class="action-row"><button class="game-action" data-entity="${e.target}">定位现场</button>${action('亲自协调 ¥350','resolve',String(e.id),'gm')}${action('交给主管 ¥150','resolve',String(e.id),'sop')}</div></section>`).join('')||'<p class="empty">目前没有异常。部门成熟以后，常规问题会自动处理。</p>'}${queue(s).length?`<button class="primary" data-open="front">接待 ${queue(s).length} 位排队住客</button>`:''}`);
  else if(view==='log')show('HOTEL JOURNAL',`<h2>运营日志</h2><div class="filter-row">${['全部','入住','客诉','房态','部门','收益','升级'].map(c=>`<button class="${c===logFilter?'active':''}" data-filter="${c}">${c}</button>`).join('')}</div><div class="log-list">${[...g.logs].reverse().filter(l=>logFilter==='全部'||l.category===logFilter).map(l=>`<article><small>Day ${l.day} ${clock(l.minute)} · ${l.category}</small><p>${esc(l.text)}</p>${l.target?`<button data-entity="${esc(l.target)}">查看现场 ›</button>`:''}</article>`).join('')}</div>`);
  else if(view==='report'){const r=g.reports.at(-1);show('DAILY REVIEW',r?`<h2>Day ${r.day} · 日结</h2><button class="game-action" data-open="score">经营评分 ${r.score??scores(s).total} / 100 ›</button><dl><div><dt>收入 / 成本</dt><dd>${money(r.revenue)} / ${money(r.expense)}</dd></div><div><dt>ADR / RevPAR</dt><dd>${money(r.adr)} / ${money(r.revpar)}</dd></div><div><dt>入住率 / 房态损失</dt><dd>${r.occupancy}% / ${r.lost}%</dd></div><div><dt>升套 / 客诉</dt><dd>${r.upgrades} / ${r.complaints}</dd></div></dl><h3>最近 7 天收入</h3><div class="revenue-trend">${g.reports.slice(-7).map(d=>`<div><small>${money(d.revenue)}</small><i style="height:${Math.max(3,Math.round(d.revenue/Math.max(1,...g.reports.slice(-7).map(v=>v.revenue))*65))}px"></i><small>D${d.day}</small></div>`).join('')}</div><blockquote>${esc(r.recommendation)}</blockquote>${g.reportOpen?action('开始下一天','continue'):''}`:'<h2>第一天还没结束</h2><p>房费于午夜统一结算。关闭面板继续经营。</p>');}
 };
 root.addEventListener('click',ev=>{const b=(ev.target as HTMLElement).closest<HTMLElement>('button');if(!b)return;
  if(b.matches('.close-sheet')){if(store.getState().game!.reportOpen)store.dispatch({type:'continue'});close();return;}
  if(b.dataset.open){view=b.dataset.open;render();return;}
  if(b.dataset.speed){store.setSpeed(Number(b.dataset.speed) as 1|2|4);return;}
  if(b.dataset.entity){selected=b.dataset.entity;const e=store.getState().entities[selected];if(e)focusFloor(e.floorId);view='entity';store.select(selected);render();return;}
  if(b.dataset.floor){const id=b.dataset.floor;close();store.focusFloor(id);focusFloor(id);return;}
  if(b.dataset.filter){logFilter=b.dataset.filter;render();return;}
  if(b.matches('.weather')){const modes=['dusk','night','day'] as const;store.setAtmosphere(modes[(modes.indexOf(store.getState().atmosphere)+1)%3]);return;}
  const type=b.dataset.action;if(!type)return;
  if(['front','report'].includes(type)){view=type;render();return;}
  if(type==='reset'){document.dispatchEvent(new Event('new-game'));return;}
  if(type==='export'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(store.getState())],{type:'application/json'}));a.download='jinwan-v8-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);return;}
  const c:Command={type:type as Command['type'],id:b.dataset.id,value:b.dataset.value};
  if(type==='checkin')c.roomId=root.querySelector<HTMLSelectElement>('#assign-'+b.dataset.id)?.value;
  if(type==='price')c.value=Number(root.querySelector<HTMLInputElement>('#price-input')?.value);
  if(type==='position')c.value=root.querySelector<HTMLSelectElement>('#position-input')?.value;
  store.dispatch(c);if(type==='continue')close();else if(view){render();if(!content.querySelector('.action-feedback'))content.insertAdjacentHTML('beforeend',`<p class="action-feedback">${esc(store.getState().game!.notice)}</p>`);}
 });
 dialog.addEventListener('cancel',ev=>{ev.preventDefault();if(!store.getState().game!.reportOpen)close();});
 let lastSelection:string|null=null,lastFloors='',lastNotice='',lastReportDay=0;
 const update=()=>{const s=store.getState(),g=s.game!;
  $('.score-button').innerHTML=`<i style="--score:${scores(s).total}%"></i> ${scores(s).total} 分 ›`;$('#cash').textContent=money(s.metrics.cash);$('#reputation').textContent=String(s.metrics.reputation);$('#owner').textContent=String(s.metrics.owner);$('#suite-count').textContent=availableSuites(s)+' 间';$('#game-time').textContent=`${weekday(g.day)} · Day ${g.day} ${clock(g.minute)}${g.paused?' · 暂停':''}`;
  $('.today-hint span:nth-child(2)').textContent=g.tasks.find(t=>!t.claimed)?.title??'今日任务全部完成';$('#task-count').textContent=g.tasks.filter(t=>t.claimed).length+'/'+g.tasks.length;$('#occupancy').textContent=`${occupiedRooms(s)}/${rooms(s).length} 在住 · 收入 ${money(g.revenue)}`;
  $('.event-strip span').textContent=(s.guests.some(v=>v.late==='pending'&&!v.departing)?'住客希望确认 4PM 退房':undefined)??g.events[0]?.title??(queue(s).length?`${queue(s).length} 位住客等待办理入住`:'酒店运营平稳');$('.event-strip b').textContent=g.events.length?'处理 ›':'前台 ›';$('.event-strip').setAttribute('data-open',g.events.length||s.guests.some(v=>v.late==='pending'&&!v.departing)?'events':'front');$('.review-strip span').textContent=g.notice;$('.weather span').textContent=g.weather==='rain'?'有雨':'晴朗';
  root.querySelectorAll<HTMLElement>('[data-speed]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.speed)===s.speed);b.setAttribute('aria-pressed',String(Number(b.dataset.speed)===s.speed));});
  const floorKey=s.floors.map(f=>f.id).join(',');if(lastFloors!==floorKey){lastFloors=floorKey;$('.floor-rail').innerHTML=[...s.floors].reverse().map(f=>`<button data-floor="${f.id}" aria-label="前往${f.label} ${f.name}">${f.label}</button>`).join('');}
  if(s.selectedId&&s.selectedId!==lastSelection){selected=s.selectedId;view='entity';render();}lastSelection=s.selectedId;
  if(g.reportOpen&&lastReportDay!==g.day){lastReportDay=g.day;view='report';render();}
  if(lastNotice!==g.notice){lastNotice=g.notice;if(dialog.open){let n=content.querySelector<HTMLElement>('.action-feedback');if(!n){n=document.createElement('p');n.className='action-feedback';content.append(n);}n.textContent=g.notice;}}
 };store.subscribe(update);update();
 return {stage:$('.world-stage'),setFocusHandler:(fn:(id:string)=>void)=>{focusFloor=fn;},showError:(message:string)=>show('画面暂时不可用',`<h2>请重新载入酒店</h2><p>${esc(message)}</p>`)};
}
