import type {PreviewState,Department,Guest} from '../state/types';
import {rooms} from '../state/selectors';
import {roomName,standardSuite} from '../content/roomTypes';
import {portrait,personCard} from './portraits';
import {forecast} from '../core/operations';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const names={front:'前厅',house:'客房',engineering:'工程',fnb:'餐饮',revenue:'收益'};
export const go=(label:string,target:string)=>`<button class="game-action" data-open="${target}">${label} →</button>`;
export function advice(s:Readonly<PreviewState>,dept:Department,title:string,why:string,trade:string,actions=''){return `<aside class="head-advice">${portrait(dept)}<div><small>${names[dept]}主管 · ${s.game!.managers[dept]?'在岗建议':'筹备建议 · 尚未聘任'}</small><h3>${esc(title)}</h3><p>${esc(why)}</p>${trade?`<p class="trade-off">${esc(trade)}</p>`:''}${actions?`<div class="action-row">${actions}</div>`:''}</div></aside>`;}
export function priority(s:Readonly<PreviewState>,view:string){const g=s.game!,rs=rooms(s),waiting=s.guests.filter(v=>!v.staff&&!v.roomId&&!v.departing),dirty=rs.filter(r=>r.status==='dirty'),pending=s.guests.filter(v=>!v.departing&&(v.late==='pending'||v.challenge&&!v.challenge.resolved)).length+g.events.length;
 if(view==='front')return advice(s,'front',waiting.length?`${waiting.length} 位客人在等房`:'前台暂时不忙','先接待即将失去耐心的客人；SUA 客人优先核对已锁标准套。','免费升套占用套房库存；拒绝确认预订需支付 ¥600 安置费。');
 if(view==='events')return advice(s,'front',pending?`${pending} 项诉求需要决定`:'目前没有待办','先看客人的核心诉求，再决定亲自处理还是授权主管。','欢迎礼不能代替承诺；晚退让客人满意，也把翻房时间推迟。');
 if(view==='hotel'||view==='entity')return advice(s,'house',dirty.length?`${dirty.length} 间脏房还不能卖`:'让现有房间先创造收入',dirty.length?'建议先翻房，再考虑花钱扩建。':'空房可以接客，也可以停卖装修；先看今天还有多少人要来。','清洁 ¥90 / 间；装修停卖 90 分钟，扩建封闭 240 分钟。',view==='hotel'&&dirty[0]?`<button class="game-action" data-entity="${dirty[0].id}">先看 ${dirty[0].number} →</button>`:'');
 if(view==='operations')return g.stock<20||g.clubStock<20?advice(s,'fnb','餐台快见底了',`早餐 ${g.stock} 份，酒廊 ${g.clubStock} 份；先补短缺的餐台。`,'每次采购 ¥300 / 50 份；聘任后能自动配送，但要付每日工资。',`<button class="game-action" data-action="stock" data-id="${g.stock<20?'breakfast':'club'}">补足低库存 · ¥300</button>`):advice(s,'house',dirty.length?'翻房开始积压':'把重复工作交给团队',dirty.length?`还有 ${dirty.length} 间脏房；先比较自己处理与长期授权。`:'主管到岗后，员工会到现场接手常规工作。','首聘 ¥3,800，工资 ¥180 / 天；工作量少时先手动处理也合理。',go('看房态','hotel'));
 if(view==='development')return advice(s,'revenue','先判断酒店缺客，还是缺容量',`当前 ${rs.filter(r=>r.status==='occupied').length} / ${rs.length} 间在住。`,'推广增加客流但不保证成交；满房时投放可能增加拒客，装修则暂时减少可售房。',go('先看今日预订','bookings'));
 if(view==='bookings')return advice(s,'front','先认出今天难接待的客人','展开 SUA、特别关注和即将到店的预订，提前留房。','预订报价已锁定；Walk-in 不在预订表内。',go('接待到店客人','front'));
 if(view==='history')return advice(s,'front','上次没解决的事，客人还记得','先看回访客人的最近一条记录，再决定这次怎样接待。','持续兑现承诺会积累信任；单次送礼不保证挽回体验。',go('看当前诉求','events'));
 if(view==='tasks')return advice(s,'front','今天先完成一件有意义的事','先跟随三日带教，再选择与当前酒店问题一致的任务。','奖励是额外收入；别为了任务在满房时继续花钱获客。');
 if(view==='score'||view==='log')return advice(s,'revenue','用结果找到下一步','先检查待办和房态，再回看评分或日志中的变化。','改善服务需要时间与成本，单次分数变化不代表长期收益。',go('看待办','events')+go('看房态','hotel'));
 return '';
}
export function teachingSteps(s:Readonly<PreviewState>){const g=s.game!,logs=g.logs.filter(l=>l.day===g.day),has=(pattern:RegExp)=>logs.some(l=>pattern.test(l.text)),review=g.evening?.day===g.day&&!g.evening.open;
 if(g.day===1)return [{title:'接住第一位客人',done:has(/ 入住 /),target:'front',text:'前厅带你选房。比较常规房与升套，点房间卡直接入住。',trade:'房费午夜入账；留住套房库存，可能让会员失望。'}, {title:'让一项服务真正落地',done:has(/开始清洁|清洁完成|需求已兑现|未解决核心诉求|个性化服务已安排|已补货/),target:s.guests.some(v=>v.challenge&&!v.challenge.resolved)?'events':'operations',text:'处理一位客人的诉求；暂时没有诉求时，为餐台备货。',trade:'看清费用和条件，送欢迎礼不等于解决核心问题。'}, {title:'20:00 看决定的后果',done:review,target:'evening',text:'关上面板继续经营。20:00 自动复盘，核对入住、支出与客诉。',trade:'预计净额尚未入账，午夜结算才是最终结果。'}];
 if(g.day===2)return [{title:'备好今天的早餐',done:has(/已补货|晨会决策已确认/),target:'brief',text:'餐饮主管带你比较预计早餐人数和现有库存，补货或保留库存后开始营业。',trade:'备货不足会影响体验；已有足够库存时无需再买。'}, {title:'处理服务压力',done:has(/需求已兑现|未解决核心诉求|退房.*(确认|协商)|已确认 .*退房|同意.*退房|晚退|个性化服务已安排|开始清洁|主管到岗|按.*处理|已补货/),target:'events',text:'先看晚退与待办；没有待办时，可安排翻房、补货，或在运营页聘任主管。',trade:'亲自处理是单次支出；授权会持续付工资，但腾出你的注意力。'}, {title:'20:00 检查服务代价',done:review,target:'evening',text:'看看客诉是否解决、成本是否增加；必要时从总部建议直接返回现场。',trade:'今天的体验与现金，需要一起判断。'}];
 if(g.day===3)return [{title:'为今天的需求下注',done:has(/挂牌价调整|晨会决策已确认/),target:'brief',text:'收益主管带你看预订与预估入住率。选 ¥720、¥850，或保留现价开始营业。',trade:'高价提高单晚收入，也可能减少 Walk-in；确认预订不改价。'}, {title:'把客流变成入住',done:has(/ 入住 /),target:'front',text:'接待实际到店的客人，观察空房和套房是否足够。不要仅凭预估就扩建。',trade:'多留套房能照顾会员，开放销售则保留付费机会。'}, {title:'20:00 对账，独立接班',done:review,target:'evening',text:'对比晨会预估与晚间入住，再决定明天保价、调价还是改善房态。',trade:'一次预测偏差不足以证明策略好坏，也要看客诉与净额。'}];return [];
}
export function teachingView(s:Readonly<PreviewState>){const steps=teachingSteps(s);if(!steps.length)return '';const i=steps.findIndex(v=>!v.done),step=steps[i<0?steps.length-1:i],dept=s.game!.day===1?'front':s.game!.day===2?'fnb':'revenue';return `<section class="teaching"><small>DAY ${s.game!.day} / 3 · ${['接待与兑现','服务与授权','预测与复盘'][s.game!.day-1]}</small><div class="teaching-track">${steps.map((v,n)=>`<span class="${v.done?'done':n===i?'current':''}">${v.done?'✓':n+1} ${v.title}</span>`).join('')}</div>${i<0?'<p>今日带教完成。你可以自由经营，明天继续接班。</p>':advice(s,dept,step.title,step.text,step.trade,go('继续这一幕',step.target))}</section>`;}
export function roomChoices(s:Readonly<PreviewState>,guest:Guest){const available=rooms(s).filter(r=>r.status==='available'||r.status==='reserved'&&guest.tier==='Globalist'&&(!r.suaBookingId||r.suaBookingId===guest.reservationId)).sort((a,b)=>Number(b.suaBookingId===guest.reservationId&&!!b.suaBookingId)-Number(a.suaBookingId===guest.reservationId&&!!a.suaBookingId)||(guest.tier==='Globalist'?Number(standardSuite(b))-Number(standardSuite(a)):Number(a.type==='suite')-Number(b.type==='suite')));
 const card=(r:typeof available[number],i:number)=>`<button class="room-choice ${i===0?'recommended':''}" data-action="checkin" data-id="${esc(guest.id)}" data-room="${r.id}"><small>${i===0?'建议安排':'另一种选择'}</small><strong>${r.number} · ${roomName(r)}</strong><span>${r.suaBookingId?'兑现 SUA 锁房':guest.tier==='Globalist'&&standardSuite(r)?'免费升套 · 占用一间标准套':'保留其他房型库存'} · 点击入住</span></button>`;
 return `<div id="assign-${esc(guest.id)}" tabindex="-1">${available.length?`<div class="room-choice-list">${available.slice(0,2).map(card).join('')}</div>${available.length>2?`<details class="manager-card"><summary>其他 ${available.length-2} 间可用房</summary>${available.slice(2).map((r,i)=>card(r,i+2)).join('')}</details>`:''}`:go('暂无可售房 · 先看房态','hotel')}</div>`;
}
export function frontView(s:Readonly<PreviewState>){const q=s.guests.filter(v=>!v.staff&&!v.roomId&&!v.departing).sort((a,b)=>(a.patience??0)-(b.patience??0));return `<h2>客人到了</h2>${q.map((g,i)=>{const body=personCard(g,`<blockquote>${esc(g.thought)}</blockquote><p>${g.stayLength} 晚 · ${esc(g.tier)}${g.sua?' · SUA 已确认':''}</p>${roomChoices(s,g)}<details class="manager-card"><summary>客史、等候与其他处理</summary><p>${esc(g.segment)} · 耐心 ${g.patience} 分钟</p><p>拒绝确认预订会产生 ¥600 安置费。</p><button class="game-action" data-action="reject" data-id="${esc(g.id)}">婉拒本次入住</button></details>`);return i===0?body:`<details class="manager-card"><summary>${esc(g.name)} · 等候 ${g.patience} 分钟耐心</summary>${body}</details>`;}).join('')||'<p class="empty">暂时没有客人排队，关上面板继续经营。</p>'}`;}
export function morningLead(s:Readonly<PreviewState>){const g=s.game!,f=forecast(s);return g.day<=3?teachingView(s).replace('data-open="brief"','data-reveal="decisions"'):advice(s,f.breakfast>g.stock?'fnb':'revenue',f.breakfast>g.stock?'早餐预估超过库存':f.occupancy>=90?'今天可能接近满房':'今天还有接客空间',`预计入住 ${f.occupancy}%，早餐 ${f.breakfast} 人 / 库存 ${g.stock} 份。`,f.breakfast>g.stock?'先补货能降低断供风险；每次支出 ¥300。':'先保留现价也可以；高价提高单晚收入，但可能减少临时客流。');}
export function entityAdvice(s:Readonly<PreviewState>,id:string){const e=s.entities[id];if(!e)return '';if(e.construction)return advice(s,'engineering','这里正在封闭施工',`剩余 ${e.construction.remaining} 游戏分钟。`,'施工完成前无法出售或使用，先处理酒店其他区域。');if(e.kind==='room'){if(e.status==='occupied')return advice(s,'front','先看这位客人需要什么','优先兑现待办和晚退承诺，再考虑额外服务。','个性化服务 ¥120；特别诉求仍需在待办单独落实。',go('处理诉求','events'));if(e.status==='dirty')return advice(s,'house','这间房还不能接客','安排翻房，等清洁完成后再分配给新客。','手动清洁 ¥90 / 30 分钟；已有员工接手时可等待。');if(e.status==='maintenance')return advice(s,'engineering','故障房正在损失销售机会','先确认有没有工程员工或维修计时，再决定亲自安排。','手动维修 ¥180；主管到岗后可自动安排常规维修。');if(e.status==='unbuilt')return advice(s,'revenue','先决定这间房要服务谁','普通房控制投入；标准套房能兑现会员升套。','尊享套投入更高，按付费房价出售，不用于标准套免费升级。');return advice(s,'house','接客，还是暂时停卖升级？','有客人排队时先安排入住，客流空档再考虑装修。','升级提高后续新客房价，但房间要停卖 90 分钟。');}return advice(s,e.role==='lobby'?'front':'fnb',`${e.name} · ${e.usage} / ${e.capacity} 人`,e.usage>=e.capacity?'容量已满，留意排队客人的体验。':'先保证供应和维护，再考虑扩大容量。','升级需要封闭施工；补货和维护可以先解决眼前问题。');}
