import {personCard,portrait} from './portraits';
import type {PreviewState,Guest} from '../state/types';
import {forecast,EXTERNAL} from '../core/operations';
import {rooms} from '../state/selectors';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const clock=(n:number)=>Math.floor(n/60)+':'+String(n%60).padStart(2,'0');
const button=(label:string,type:string,id='',value='')=>`<button class="game-action" data-action="${type}" data-id="${esc(id)}" data-value="${value}">${label}</button>`;
const meter=(label:string,value:string)=>`<div><small>${label}</small><strong>${value}</strong></div>`;
export function briefView(s:Readonly<PreviewState>){const g=s.game!,o=g.operations!,f=forecast(s),n=o.bookings.length,weekend=(g.day-1)%7>=5,remaining=o.bookings.filter(b=>b.status==='confirmed').length;
 const rows=[['收益经理',g.managers.revenue,f.occupancy>=90?'预计接近满房，广告可能只带来更多拒客。':'仍有空房，比较低价获客和高价利润。'],['前厅经理',g.managers.front,`${f.suites} 位确认预订的 Globalist；已锁 SUA 必须保留。`],['客房经理',g.managers.house,`今天 ${f.housekeeping} 间预计翻房；员工需推车到场，晚退会挤压时间。`],['餐饮经理',g.managers.fnb,`早餐预计 ${f.breakfast} 人、库存 ${g.stock}；Happy Hour 预计 ${f.club} 人、库存 ${g.clubStock}。`],['工程经理',g.managers.engineering,`${rooms(s).filter(r=>r.status==='maintenance').length} 间封闭房；施工不接待，维修完成才能出售。`]];
 return `<h2>08:00 · 早班晨会</h2><p>Day ${g.day} · ${weekend?'周末':'工作日'} · ${g.positioning==='business'?'商务定位':g.positioning==='resort'?'度假定位':'城市混合'} · ${g.weather==='rain'?'有雨':'晴朗'}</p><blockquote>${EXTERNAL[o.event]}</blockquote><div class="brief-grid">${meter('确认预订 / 待到店',n+' / '+remaining)}${meter('预计 Walk-in',f.walkins+' 位')}${meter('预计晚间入住率',f.occupancy+'%')}${meter('商务 / 度假 / 团队',f.business+' / '+f.resort+' / '+f.group)}${meter('早餐人数 / 库存',f.breakfast+' / '+g.stock)}${meter('HK 翻房 / 标准套需求',f.housekeeping+' / '+f.suites)}</div><details class="manager-card"><summary>经理交班与建议</summary>${rows.map(([name,level,text],i)=>`<div class="person-card manager-brief">${portrait((['revenue','front','house','fnb','engineering'] as const)[i])}<div class="person-body"><b>${name} · ${level?'在岗':'待聘任'}</b><p>${text}</p></div></div>`).join('')}</details><details class="manager-card"><summary>今日决策 · 挂牌 ¥${g.price} / ${o.suitePolicy==='hold'?'留套':'开放销售'} <small>调整 ›</small></summary><div class="decision-line"><span>Walk-in 挂牌 ¥${g.price}</span>${button('¥720','price','','720')}${button('¥850','price','','850')}</div><div class="decision-line"><span>套房：${o.suitePolicy==='hold'?'保留一间给会员':'开放销售'}</span>${button('留一间','suite-policy','','hold')}${button('开放卖','suite-policy','','sell')}</div><div class="decision-line"><span>早餐 ${g.stock} 份 / 酒廊 ${g.clubStock} 份</span>${button('早餐 +50 · ¥300','stock','breakfast')}${button('酒廊 +50 · ¥300','stock','club')}</div><div class="decision-line"><span>${g.development&&g.development.campaignUntil>=g.day?'广告投放中':'广告未投放'}</span>${button('三日推广 ¥2,200','campaign')}</div></details><small>确认预订的报价已锁定；调价影响未预订客流。预估有波动，无法接待确认预订需支付 ¥600/单安置费；平台订单每晚收取 15% 佣金。</small><div class="action-row"><button class="game-action" data-open="bookings">查看预订</button><button class="game-action" data-open="history">客史记录</button></div>${o.briefOpen?'<div class="meeting-footer">'+button('确认决策 · 开始营业','brief-start')+'</div>':''}`;
}
export function bookingsView(s:Readonly<PreviewState>){const o=s.game!.operations!;return `<h2>今日预订</h2><div class="brief-grid">${['APP','团单','平台'].map(source=>meter(source,o.bookings.filter(b=>b.source===source).length+' 单')).join('')}</div><p>Walk-in 为额外临时到店，今天已到 ${o.walkinArrivals} 位。</p>${o.bookings.map(b=>{const p=o.profiles[b.profileId];return `<details class="manager-card"><summary class="person-summary">${portrait(p)}<span>${esc(p.name)} · ${b.source} · ${clock(b.eta)}<small>${({confirmed:'待到店',arrived:'在排队',checkedin:'已入住',lost:'安置离店'}[b.status])}</small></span></summary><p>${esc(p.tier)} · ${b.nights} 晚 · 锁定价 ¥${b.rate}${b.sua?' · SUA 锁套':''}</p><p>${b.challenge?'特别关注：'+({quiet:'需要安静房间',sua:'已确认标准套房',family:'早餐与加床需求',audit:'服务标准检查'}[b.challenge]):'常规接待'}</p><p>客史 ${p.visits} 次 · 信任 ${p.trust} · ${esc(p.history.at(-1)?.text??'首次来店')}</p></details>`;}).join('')}<button class="game-action" data-open="brief">返回晨会</button>`;}
export function historyView(s:Readonly<PreviewState>){return `<h2>客史与关系</h2>${Object.values(s.game!.operations!.profiles).filter(p=>p.visits>0||s.guests.some(g=>g.profileId===p.id)).sort((a,b)=>b.visits-a.visits).map(p=>`<details class="manager-card"><summary class="person-summary">${portrait(p)}<span>${esc(p.name)} · ${esc(p.tier)}<small>${p.visits} 次入住</small></span></summary><p>信任 ${p.trust} · 累计消费 ¥${Math.round(p.spend)}${p.referredBy?' · 由熟客介绍':''}</p>${p.history.map(h=>`<p>Day ${h.day} · ${esc(h.text)}</p>`).join('')||'<p>首次入住，等待这次故事。</p>'}</details>`).join('')}<button class="game-action" data-open="brief">返回晨会</button>`;}
export function challengeCards(s:Readonly<PreviewState>){return s.guests.filter(g=>g.challenge&&!g.challenge.resolved&&!g.departing).map(g=>{const req=g.challenge!.kind;
 const copy={quiet:['需要安静，不能被施工吵到','施工邻层需换到安静的空房。','落实安静安排'],sua:['SUA 确认的标准套，今天能兑现吗？','入住标准套房后核对权益。','核对已给标准套'],family:['早餐和加床，可以一起安排吗？',`需早餐库存 6 份 · 当前 ${s.game!.stock} 份`,'安排家庭服务'],audit:['想确认一下房间和服务流程。','需客房、工程主管在岗，且没有待修客房。','完成巡检']}[req];
 return personCard(g,`<blockquote>${copy[0]}</blockquote>${!g.roomId?`<p class="request-condition">尚未入住 · 先分房，再落实诉求</p><button class="game-action choice-primary" data-open="front" data-guest="${esc(g.id)}">为 ${esc(g.name)} 办理入住 →</button>`:`<p class="request-condition">${copy[1]}</p><div class="choice-grid">${button(copy[2]+' · ¥180','guest-choice',g.id,req==='sua'?'inventory':req==='audit'?'inspect':req)}${button('欢迎礼 · ¥100','guest-choice',g.id,'gift')}${button('不作安排','guest-choice',g.id,'decline')}</div><small class="choice-note">欢迎礼不替代诉求；不作安排会影响体验。</small>`}`);
 }).join('');}

export function eveningView(s:Readonly<PreviewState>){const r=s.game!.evening;if(!r)return '<h2>20:00 · 晚间复盘</h2><p>今晚 20:00 与总部一起回看经营与客诉。</p>';const money=(n:number)=>'¥'+Math.round(n).toLocaleString('en-US');return `<h2>20:00 · 晚间复盘</h2><p>Day ${r.day} · 截至 ${clock(r.minute)} 的经营快照</p><div class="brief-grid">${meter('入住率 / 晨会预估',r.occupancy+'% / '+(r.expected??'—')+'%')}${meter('今日办理入住',r.arrivals+' 位')}${meter('已入账收入',money(r.revenue))}${meter('已支出成本',money(r.expense))}${meter('预计待结房费',money(r.roomRevenue))}${meter('预计日结净额',money(r.projectedNet))}</div><p class="meeting-note">预估包含当前在住房费、平台佣金及日常成本；午夜才结算，后续入住和支出会改变结果。</p><details class="manager-card" ${r.pending||r.complaints?'open':''}><summary>客诉与服务记录 <small>${r.pending} 项待办 · ${r.complaints} 次客诉计数</small></summary><p>以下为今日客诉日志原文，包含请求、处理与结果；多条记录可能属于同一事件。</p>${r.logs.map(l=>`<article class="review-entry"><time>${clock(l.minute)}</time><div>${esc(l.text)}${l.target?`<button class="game-action" data-entity="${esc(l.target)}">查看现场 →</button>`:''}</div></article>`).join('')||'<p>今天尚无客诉日志。</p>'}<button class="game-action" data-open="events">处理当前待办 →</button></details><h3>总部 · 今晚优先改进</h3>${r.notes.map(n=>`<div class="person-card manager-brief">${portrait('revenue')}<div class="person-body"><strong>${n.title}</strong><p>${n.text}</p><button class="game-action" data-open="${n.target}">去落实 →</button></div></div>`).join('')}${r.open?'<div class="meeting-footer">'+button('交给夜班 · 继续经营','evening-close')+'</div>':''}`;}
