import type {PreviewState} from '../state/types';
import {rooms} from '../state/selectors';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const link=(title:string,detail:string,target:string)=>`<button class="hub-tile" data-open="${target}"><strong>${title}</strong><small>${detail}</small><span aria-hidden="true">↗</span></button>`;
export function workItems(s:Readonly<PreviewState>){const g=s.game!;return [
 ...g.events.map(e=>({key:'event-'+e.id,title:e.title,detail:`剩余 ${Math.max(0,e.expires-g.day*1440-g.minute)} 分钟`,urgent:true,button:`<button class="game-action" data-entity="${esc(e.target)}">现场</button><button class="game-action" data-action="resolve" data-id="${e.id}" data-value="gm">亲自处理 · ¥350</button>`,note:'直接协调支出较高；授权方案在待办详情中。'})),
 ...rooms(s).filter(r=>r.status==='dirty').map(r=>({key:r.id,title:r.number+' · 待翻房',detail:'客房部 · 清洁后才可出售',urgent:false,button:`<button class="game-action" data-action="clean" data-id="${r.id}">清洁 · ¥90</button>`,note:'约 30 游戏分钟；等待主管可节省手动清洁费。'})),
 ...s.guests.filter(v=>!v.staff&&!v.departing&&!v.roomId).map(v=>({key:v.id,title:v.name+' · 等待入住',detail:`${v.tier} · 耐心 ${v.patience??0} 分钟`,urgent:(v.patience??100)<45,button:`<button class="game-action" data-open="front" data-guest="${esc(v.id)}">为他选房 →</button>`,note:v.reservationId?'确认预订未兑现需支付 ¥600 安置费。':'临时到店客人，先比较空房与留套需要。'})),
 ...s.guests.filter(v=>!v.departing&&v.roomId&&(v.late==='pending'||v.challenge&&!v.challenge.resolved)).map(v=>({key:v.id,title:v.name+' · 服务待确认',detail:v.late==='pending'?'晚退请求':'特殊安排',urgent:false,button:`<button class="game-action" data-open="events" data-guest="${esc(v.id)}">处理诉求 →</button>`,note:'查看真实诉求与条件，欢迎礼不代替承诺。'})),
 ...(g.stock<20?[{key:'breakfast-stock',title:'早餐库存偏低',detail:`剩余 ${g.stock} 份`,urgent:true,button:'<button class="game-action" data-action="stock" data-id="breakfast">补 50 份 · ¥300</button>',note:'提前备货减少断供风险；先保留必要现金。'}]:[]),
 ...(g.clubStock<20?[{key:'club-stock',title:'酒廊库存偏低',detail:`剩余 ${g.clubStock} 份`,urgent:true,button:'<button class="game-action" data-action="stock" data-id="club">补 50 份 · ¥300</button>',note:'晚间服务仍在继续，补货会增加今天成本。'}]:[]),
 ].sort((a,b)=>Number(b.urgent)-Number(a.urgent));}
export function workList(s:Readonly<PreviewState>,limit=4){const all=workItems(s);return `<section class="work-list"><div class="hub-section-title"><h3>现在需要处理 <small>${all.length}</small></h3>${all.length>limit?'<button data-open="worklist">查看全部 →</button>':''}</div>${all.slice(0,limit).map(v=>`<article class="work-item" data-work-key="${esc(v.key)}"><div><strong>${esc(v.title)}</strong><small>${esc(v.detail)}</small></div>${v.urgent?'<span class="urgency">优先</span>':''}<div class="work-actions">${v.button}</div><small class="work-trade">${esc(v.note)}</small></article>`).join('')||'<p class="empty">没有积压事项，关上面板看看酒店里的客人。</p>'}</section>`;}
export function hubView(s:Readonly<PreviewState>){const g=s.game!,rs=rooms(s),pending=workItems(s).length;return `<h2>今天怎么经营？</h2><p class="hub-subtitle">Day ${g.day} · ${rs.filter(r=>r.status==='occupied').length} / ${rs.length} 间在住 · ${pending} 项现场事项</p><div class="hub-grid">${link('08:00 晨会','预订、需求与今天的决定','brief')}${link('20:00 复盘',g.evening?'回看客诉与总部建议':'晚间自动开会','evening')}${link('今日目标',g.tasks.filter(t=>t.claimed).length+' / '+g.tasks.length+' 项已领奖','tasks')}${link('财务与评分','收入、成本与经营表现','report')}</div>${workList(s)}<details class="manager-card"><summary>经营档案与长期计划</summary><div class="hub-grid">${link('客史记录','上次承诺，这次兑现','history')}${link('经营日志','追溯决定与结果','log')}${link('投资计划','扩建、营销与主题活动','development')}${link('今日预订','APP、团单与平台客人','bookings')}</div></details>`;}
