import type {Department} from '../state/types';
import {portrait} from './portraits';
export const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const money=(n:number)=>'¥'+Math.round(n).toLocaleString('en-US');
export const btn=(label:string,type:string,id='',value='',extra='')=>`<button class="game-action" data-action="${type}" data-id="${esc(id)}" data-value="${esc(value)}" ${extra}>${label}</button>`;
export const go=(label:string,target:string)=>`<button class="game-action" data-open="${target}">${label}</button>`;
export const choose=(label:string,key:string,value:string,active=false)=>`<button data-focus-key="${key}" data-focus-value="${esc(value)}" aria-pressed="${active}">${label}</button>`;
export const tabs=(body:string)=>`<div class="focus-tabs">${body}</div>`;
export const metrics=(values:[string,string][])=>`<div class="focus-metrics">${values.map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}</div>`;
export const head=(dept:Department,title:string,text:string)=>`<div class="focus-person">${portrait(dept)}<div><strong>${esc(title)}</strong><p>${esc(text)}</p></div></div>`;
export const frame=(title:string,body:string,actions:string)=>`<section class="focus-screen"><h2>${title}</h2><div class="focus-main">${body}</div></section><div class="focus-footer">${actions}</div>`;
export const pager=(key:string,index:number,total:number)=>`<div class="focus-pager">${choose('‹ 上一项',key,String(Math.max(0,index-1)))}<span>${total?index+1:0} / ${total}</span>${choose('下一项 ›',key,String(Math.min(Math.max(0,total-1),index+1)))}</div>`;
