import * as THREE from 'three';
import type { GameState } from '../core/types';
import type { EventBus } from '../core/EventBus';

export class ThreeBattlefield {
  private renderer:THREE.WebGLRenderer; private scene=new THREE.Scene(); private camera=new THREE.PerspectiveCamera(34,2.3,.1,60);
  private actors=new Map<string,THREE.Group>(); private disposeEvent:()=>void; private host:HTMLElement|null=null; private ro?:ResizeObserver;
  private portal?:THREE.Group; private clock=new THREE.Clock(); private transient:{o:THREE.Object3D;t:number;life:number}[]=[]; private shake=0;
  private palette:Record<string,number>={guard:0x4c7ac3,cavalry:0xd89b58,ranger:0x4d9b66,mage:0x8b63cb,prism:0xaecbff,crawler:0x697789,brute:0x806c5d,spitter:0x687856,seer:0x795b94,boss:0x994960};
  constructor(private getState:()=>GameState,bus:EventBus){this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,innerWidth<520?1.35:1.5));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.setClearColor(0x000000,0);this.camera.position.set(0,4.8,9.65);this.camera.lookAt(0,.72,0);this.buildWorld();this.disposeEvent=bus.on(e=>{if(e.type==='combat:fx')this.fx(e.src,e.tgt,e.kind);if(e.type==='unit:merge')this.mergeFx(e.src,e.tgt);if(e.type==='unit:level')this.levelFx(e.id,e.star);if(e.type==='jackpot')this.jackpotFx(e.lines);});}
  mount(){const host=document.querySelector<HTMLElement>('.stage');if(!host)return;if(this.host!==host){this.host=host;host.prepend(this.renderer.domElement);this.renderer.domElement.style.position='absolute';this.renderer.domElement.style.inset='0';this.renderer.domElement.style.width='100%';this.renderer.domElement.style.height='100%';this.renderer.domElement.style.zIndex='2';this.ro?.disconnect();this.ro=new ResizeObserver(()=>this.resize());this.ro.observe(host);this.resize();}}
  update(dt:number,elapsed:number){const s=this.getState();this.renderer.domElement.style.display=s.threeEnabled?'block':'none';if(!s.threeEnabled)return;this.mount();this.syncActors();if(this.portal)this.portal.rotation.z=elapsed*.15;for(const g of this.actors.values()){const homeX=g.userData.homeX??g.position.x,homeZ=g.userData.homeZ??g.position.z;g.position.x+=(homeX-g.position.x)*.18;g.position.z+=(homeZ-g.position.z)*.18;if(!g.userData.dead)g.position.y+=(Math.sin(elapsed*2.3+g.userData.idx)*.025-g.position.y)*.15;if(g.userData.hpBar){g.userData.hpBar.quaternion.copy(g.quaternion).invert().multiply(this.camera.quaternion)}if(g.userData.ring)g.userData.ring.rotation.z=elapsed*1.1}
    for(let i=this.transient.length-1;i>=0;i--){const x=this.transient[i]!;x.t+=dt;const q=Math.min(1,x.t/x.life);if((x.o as THREE.Mesh).material){const m=(x.o as THREE.Mesh).material as THREE.Material & {opacity?:number};if(m.opacity!=null)m.opacity=1-q}x.o.scale.setScalar(1+q*1.6);if(q>=1){this.scene.remove(x.o);this.disposeObj(x.o);this.transient.splice(i,1)}}
    if(this.shake>0){this.shake*=.82;const nx=Math.sin(elapsed*71.3)*.5,nz=Math.sin(elapsed*103.7+1.7)*.5;this.camera.position.set(nx*this.shake,4.8+nz*this.shake*.3,9.65)}else this.camera.position.lerp(new THREE.Vector3(0,4.8,9.65),.2);this.camera.lookAt(0,.72,0);this.renderer.render(this.scene,this.camera);}
  diagnostics(){const i=this.renderer.info;return{calls:i.render.calls,triangles:i.render.triangles,geometries:i.memory.geometries,textures:i.memory.textures};}
  dispose(){this.disposeEvent();this.ro?.disconnect();for(const g of this.actors.values())this.disposeObj(g);this.actors.clear();this.scene.traverse((o:THREE.Object3D)=>this.disposeObj(o,false));this.renderer.dispose();}
  private resize(){if(!this.host)return;const w=Math.max(1,this.host.clientWidth),h=Math.max(1,this.host.clientHeight);this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
  private buildWorld(){this.scene.fog=new THREE.FogExp2(0x0b111b,.055);this.scene.add(new THREE.HemisphereLight(0xa9c8ff,0x1b1521,2));const key=new THREE.DirectionalLight(0xffdfad,3.2);key.position.set(-3,7,5);this.scene.add(key);const floor=new THREE.Mesh(new THREE.PlaneGeometry(12,6),new THREE.MeshStandardMaterial({color:0x111b28,roughness:.9}));floor.rotation.x=-Math.PI/2;this.scene.add(floor);const castle=new THREE.Mesh(new THREE.BoxGeometry(1.35,2,1.55),new THREE.MeshStandardMaterial({color:0x182232,roughness:.95}));castle.position.set(-5.1,1,-.2);this.scene.add(castle);this.portal=new THREE.Group();this.portal.position.set(4.9,1.25,-.1);this.scene.add(this.portal);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.05,.12,12,32),new THREE.MeshStandardMaterial({color:0x7956bd,emissive:0x5d2bba,emissiveIntensity:2}));this.portal.add(ring);}
  private syncActors(){const s=this.getState(),items=s.phase==='battle'&&s.battle?[...s.battle.allies.map((data,i)=>({data,i,enemy:false})),...s.battle.enemies.map((data,i)=>({data,i,enemy:true}))]:s.units.slice(0,s.fieldCap).map((data,i)=>({data:{...data,maxHp:data.hp,hp:data.hp,shield:0,dead:false},i,enemy:false}));const keep=new Set<string>();for(const it of items){const d:any=it.data;keep.add(d.id);let g=this.actors.get(d.id);if(!g){g=this.buildActor(d,it.enemy);this.scene.add(g);this.actors.set(d.id,g)}const p=this.pos(it.i,it.enemy);g.userData.homeX=p.x;g.userData.homeZ=p.z;g.userData.idx=it.i;g.userData.dead=!!d.dead||d.hp<=0;g.position.x+=(p.x-g.position.x)*.24;g.position.z+=(p.z-g.position.z)*.24;const ratio=Math.max(0,Math.min(1,d.hp/(d.maxHp||d.hp||1)));if(g.userData.fill){g.userData.fill.scale.x=Math.max(.045,ratio);g.userData.fill.visible=ratio>0&&!g.userData.dead;g.userData.fill.material.color.setHex(it.enemy?(ratio>.6?0xdf6872:ratio>.3?0xf29b54:0xffe066):(ratio>.6?0x63d49b:ratio>.3?0xf0c75e:0xff8a70))}if(g.userData.hpBar)g.userData.hpBar.visible=s.phase==='battle'&&!g.userData.dead;}
    for(const [id,g] of this.actors)if(!keep.has(id)){this.scene.remove(g);this.disposeObj(g);this.actors.delete(id)}}
  private pos(i:number,enemy:boolean){const ally=[[-1.2,-1.5],[-1.2,1.5],[-2.4,-1],[-2.4,1],[-3.6,-.5],[-3.6,.5]],foe=[[1.2,-1.5],[1.2,1.5],[2.4,-1],[2.4,1],[3.6,-.5],[3.6,.5]],a=(enemy?foe:ally)[i]||[enemy?3.6:-3.6,0];return{x:a[0]!,z:a[1]!}}
  private buildActor(d:any,enemy:boolean){const g=new THREE.Group();g.userData.id=d.id;const body=new THREE.Mesh(new THREE.CylinderGeometry(.25,.31,.66,6),new THREE.MeshStandardMaterial({color:this.palette[d.type]||0x777777,roughness:.62}));body.position.y=.65;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.21,8,6),new THREE.MeshStandardMaterial({color:enemy?0x687181:0xd6a47f,roughness:.82}));head.position.y=1.15;g.add(head);const hp=new THREE.Group();hp.position.set(0,1.62,.02);hp.renderOrder=2000;g.add(hp);const bgm=new THREE.MeshBasicMaterial({color:0x10151e,depthTest:false,depthWrite:false});bgm.toneMapped=false;const bg=new THREE.Mesh(new THREE.PlaneGeometry(.68,.06),bgm);bg.renderOrder=2001;hp.add(bg);const fm=new THREE.MeshBasicMaterial({color:enemy?0xdf6872:0x63d49b,depthTest:false,depthWrite:false});fm.toneMapped=false;const geo=new THREE.PlaneGeometry(.62,.044);geo.translate(.31,0,0);const pivot=new THREE.Group();pivot.position.x=-.31;hp.add(pivot);const fill=new THREE.Mesh(geo,fm);fill.renderOrder=2002;pivot.add(fill);g.userData.hpBar=hp;g.userData.fill=fill;if(!enemy&&d.star>=2){const ring=new THREE.Mesh(new THREE.TorusGeometry(.37,.025,8,24),new THREE.MeshBasicMaterial({color:d.star>=3?0xf2cf72:0x78baff,transparent:true,opacity:.72}));ring.rotation.x=Math.PI/2;ring.position.y=.06;g.add(ring);g.userData.ring=ring}if(d.type==='boss')g.scale.setScalar(1.42);return g;}
  private fx(src:string,tgt:string,kind:string){const a=this.actors.get(src),b=this.actors.get(tgt);if(!a||!b)return;const color=kind.includes('Magic')||kind==='magic'?0xb983ff:kind==='heal'?0x6ce0a9:kind.startsWith('enemy')?0xff817d:0xf4d47d;const ring=new THREE.Mesh(new THREE.RingGeometry(.1,.24,18),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.copy(b.position);ring.position.y=.05;this.scene.add(ring);this.transient.push({o:ring,t:0,life:.45});if(kind.includes('boss')||kind==='enemyMagic')this.shake=Math.max(this.shake,.08);}
  private mergeFx(_src:string,tgt:string){const g=this.actors.get(tgt);if(g)this.fx(tgt,tgt,'magic')}
  private levelFx(id:string,star:number){const g=this.actors.get(id);if(g){this.fx(id,id,'magic');if(star>=3)this.shake=.12}}
  private jackpotFx(lines:number){this.shake=Math.max(this.shake,.08+lines*.02)}
  private disposeObj(o:THREE.Object3D,recursive=true){if(recursive)o.traverse((x:THREE.Object3D)=>this.disposeObj(x,false));const x=o as THREE.Mesh;x.geometry?.dispose?.();const m=x.material;if(m)(Array.isArray(m)?m:[m]).forEach(mm=>mm.dispose())}
}
