const state={data:null,view:'all',filters:{area:false,rent:false,direct:true,commute:true,split:false},sort:'score'};
const fmtMoney=n=>`HK$${Number(n||0).toLocaleString('en-HK')}`;
const fmtDate=s=>{if(!s)return '—';const d=new Date(s);return Number.isNaN(d.getTime())?s:new Intl.DateTimeFormat('zh-HK',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)};
const ER_PROFILE={'红磡':{leave:'约06:05',risk:'excellent',bonus:14},'大围':{leave:'约05:50–05:55',risk:'excellent',bonus:12},'沙田':{leave:'约05:45–05:50',risk:'safe',bonus:9},'火炭':{leave:'约05:40–05:45',risk:'safe',bonus:6},'大学':{leave:'约05:45前',risk:'medium',bonus:2},'大埔墟':{leave:'约05:40前',risk:'medium',bonus:0},'太和':{leave:'约05:35–05:40',risk:'medium',bonus:-1},'粉岭':{leave:'约05:30–05:35',risk:'early',bonus:-5},'上水':{leave:'约05:25–05:30',risk:'early',bonus:-7}};
const IS_PROFILE={'坚尼地城':{leave:'约05:45–05:50',risk:'safe',bonus:7},'香港大学':{leave:'约05:48–05:53',risk:'safe',bonus:8},'西营盘':{leave:'约05:50–05:55',risk:'safe',bonus:9},'湾仔':{leave:'约06:08–06:12',risk:'excellent',bonus:16},'天后':{leave:'约06:00',risk:'excellent',bonus:13},'炮台山':{leave:'约05:58–06:02',risk:'excellent',bonus:12},'北角':{leave:'约05:55–06:00',risk:'excellent',bonus:11},'鰂鱼涌':{leave:'约05:50–05:55',risk:'excellent',bonus:10},'太古':{leave:'约05:50',risk:'safe',bonus:8},'西湾河':{leave:'约05:45–05:50',risk:'safe',bonus:7},'筲箕湾':{leave:'约05:40–05:45',risk:'safe',bonus:5},'杏花邨':{leave:'约05:40前',risk:'medium',bonus:2},'柴湾':{leave:'约05:35–05:40',risk:'medium',bonus:0}};
const SIL_PROFILE={'黄竹坑':{leave:'约05:58–06:02',risk:'excellent',bonus:13},'利东':{leave:'约05:55–06:00',risk:'excellent',bonus:14},'海怡半岛':{leave:'约05:52–05:58',risk:'excellent',bonus:12}};
const TW_FRAGILE=new Set(['荃湾','大窝口','葵兴','葵芳','荔景','美孚','荔枝角','长沙湾','深水埗']);
const TW_MID=new Set(['太子','旺角','油麻地','佐敦','尖沙咀']);
const WEST_KOWLOON=new Set(['深水埗','长沙湾','荔枝角','南昌','大角咀','奥运']);
const PRIORITY_AREAS=new Set(['北角','鰂鱼涌','西湾河','长沙湾','鸭脷洲','大围','沙田','红磡','柴湾','粉岭','坚尼地城','湾仔','西营盘','天后/大坑']);
const FALLBACK_WATCH=['惠利大廈','金海大廈','中興大廈','東發大廈','形品','長興大樓','譽東','柏匯','曉悅','睿峰','美居中心','嘉裕居','黃金大廈','昌遠大廈','喜居','柏傲莊','金獅花園','薈蕎','沙田中心','紅磡灣中心','環海東岸','The Haddon','必嘉坊迎匯','雅麗閣','粉嶺名都','粉嶺中心','牽晴間','海都樓','錦興大廈','青蓮閣','美菲閣','李節花園','壹嘉','維峯','維峯浚匯'];
const FALLBACK_PREMIUM=['柏傲莊','睿峰','壹嘉','維峯','維峯浚匯'];
function estateText(x){return String(x.estate||x.title||'')}
function watchNames(){return state.data?.meta?.watchlist_estates||FALLBACK_WATCH}
function premiumNames(){return state.data?.meta?.premium_watchlist_estates||FALLBACK_PREMIUM}
function isWatchlist(x){const s=estateText(x);return watchNames().some(n=>s.includes(n))}
function isPremiumWatch(x){const s=estateText(x);return premiumNames().some(n=>s.includes(n))}
function badge(label,cls=''){return `<span class="badge ${cls}">${label}</span>`}
function commute(x){const route=x.admiralty_route||'',st=x.mtr_station||'';if(route.includes('南港岛线')){const p=SIL_PROFILE[st]||{leave:'约05:55–06:00',risk:'excellent',bonus:12};return {ok:true,...p,label:`06:30稳达 · 建议${p.leave}出门`}}if(route.includes('港岛线')){const p=IS_PROFILE[st]||{leave:'约05:45–05:55',risk:'safe',bonus:6};return {ok:true,...p,label:`06:30稳达 · 建议${p.leave}出门`}}if(route.includes('东铁线')){const p=ER_PROFILE[st]||{leave:'约05:45–05:55',risk:'safe',bonus:5};return {ok:true,...p,label:`06:30可达 · 建议${p.leave}出门`}}if(route.includes('荃湾线')){if(TW_FRAGILE.has(st))return {ok:true,risk:'fragile',leave:'约06:00前',label:'06:30理论可达 · 基本依赖首班，误一班可能迟到',bonus:-10};if(TW_MID.has(st))return {ok:true,risk:'tight',leave:'约06:05前',label:'06:30可达 · 仍偏依赖首班，容错较低',bonus:-4};return {ok:true,risk:'tight',leave:'约06:00前',label:'06:30可达 · 早班容错一般',bonus:-3}}return {ok:false,risk:'fail',leave:'—',label:'06:30到达未验证',bonus:-20}}
function verifiedBase(x){return x.type_verified===true&&x.mtr_verified===true&&x.shared!==true}
function tier(x){const c=commute(x);if(!verifiedBase(x)||!c.ok)return 'D';if(x.area>=300&&x.rent<=15000&&x.mtr_walk_min<=5&&x.lift===true&&x.split_ac===true&&!['fragile','early'].includes(c.risk))return 'A';if(x.area>=260&&x.rent<=18000&&x.mtr_walk_min<=10&&!['fail'].includes(c.risk))return 'B';if(x.area>=250&&x.rent<=22000&&x.mtr_walk_min<=12)return 'C';return 'D'}
function budgetBonus(x){if(x.rent<=14000)return 6;if(x.rent<=15000)return 3;if(x.rent<=16000)return 0;if(x.rent<=18000)return -5;if(x.rent<=20000)return -10;return -16}
function areaBonus(x){if(x.area>=400)return 8;if(x.area>=350)return 6;if(x.area>=300)return 3;if(x.area>=280)return 0;return -5}
function adjustedScore(x){const zone=WEST_KOWLOON.has(x.district)?3:0,area=PRIORITY_AREAS.has(x.district)?3:0,watch=isWatchlist(x)?5:0,tierB=tier(x)==='A'?8:tier(x)==='B'?2:-4;return Math.max(0,Math.min(99,(x.score||0)+commute(x).bonus+budgetBonus(x)+areaBonus(x)+zone+area+watch+tierB))}
function tradeoffs(x){const c=commute(x),a=[];if(x.rent>18000)a.push('租金明显超预算');else if(x.rent>15000)a.push(`租金高于15k ${fmtMoney(x.rent-15000)}`);if(x.area<300)a.push(`面积不足300呎（${x.area}呎）`);if(x.mtr_walk_min>5)a.push(`步行港铁${x.mtr_walk_min}分钟`);if(c.risk==='fragile'||c.risk==='tight')a.push('早班容错低');if(c.risk==='early')a.push('需要很早出门');if(x.split_ac!==true)a.push(x.ac_present?'冷气类型待确认':'冷气待确认');if(x.lift!==true)a.push('电梯待确认');if(x.wet_dry!==true)a.push('干湿分离待确认');if(x.age_years>=45)a.push(`楼龄${x.age_years}年`);return a.slice(0,4)}
function upsides(x){const base=state.data?.baseline||{rent:11000,area:224},c=commute(x),a=[];if(x.area-base.area>=100)a.push(`比基安多${x.area-base.area}呎`);else if(x.area>=300)a.push(`${x.area}呎空间升级`);if(x.rent<=14000)a.push('租金仍在原预算附近');if(c.risk==='excellent')a.push('早班通勤明显更好');if(x.split_ac===true)a.push('分体冷气已确认');if(x.wet_dry===true)a.push('干湿分离');if(isWatchlist(x))a.push('重点屋苑');if(x.age_years!=null&&x.age_years<=15)a.push('楼龄较新');return a.slice(0,3)}
function statusBadges(x){const out=[],c=commute(x),t=tier(x);out.push(badge(t==='A'?'A 核心':t==='B'?'B 权衡':'C 机会',t==='A'?'good':t==='B'?'warn':'neutral'));if(x.is_new)out.push(badge('新盘','new'));if(x.price_drop>0)out.push(badge(`降价 ${fmtMoney(x.price_drop)}`,'new'));if(isWatchlist(x))out.push(badge(isPremiumWatch(x)?'重点屋苑·机会观察':'重点屋苑','good'));if(c.risk==='excellent')out.push(badge('早班通勤优','good'));else if(c.risk==='safe')out.push(badge('06:30稳达','good'));else if(c.risk==='fragile'||c.risk==='tight')out.push(badge('早班容错低','warn'));else if(c.risk==='early')out.push(badge('需很早出门','warn'));if(x.split_ac===true)out.push(badge('分体冷气','good'));else if(x.ac_present)out.push(badge('冷气类型待确认','warn'));if(x.wet_dry===true)out.push(badge('干湿分离','good'));if(x.lift===true)out.push(badge('有电梯','good'));return out.join('')}
function passes(x){if(tier(x)==='D')return false;if(state.view==='core'&&tier(x)!=='A')return false;if(state.view==='tradeoff'&&tier(x)!=='B')return false;if(state.view==='watch'&&!isWatchlist(x))return false;if(state.view==='new'&&!x.is_new&&!(x.price_drop>0))return false;if(state.filters.area&&x.area<300)return false;if(state.filters.rent&&x.rent>16000)return false;if(state.filters.direct&&!x.direct_to_admiralty)return false;if(state.filters.commute&&!commute(x).ok)return false;if(state.filters.split&&x.split_ac!==true)return false;return true}
function sorted(items){return [...items].sort((a,b)=>{if(state.sort==='area')return b.area-a.area;if(state.sort==='rent')return a.rent-b.rent;if(state.sort==='fresh')return String(b.last_seen).localeCompare(String(a.last_seen));return adjustedScore(b)-adjustedScore(a)||a.rent-b.rent})}
function card(x){const base=state.data.baseline,c=commute(x),areaGain=x.area-base.area,rentGain=x.rent-base.rent,tr=tradeoffs(x),up=upsides(x);return `<article class="listing"><div class="listing-top"><div class="listing-title"><h2>${x.estate||x.title}</h2><p>${x.district}${x.unit?` · ${x.unit}`:''}${x.rooms?` · ${x.rooms}房`:''}</p></div><div class="score">${adjustedScore(x)}</div></div><div class="badges">${statusBadges(x)}</div><div class="metrics"><div class="metric"><b>${fmtMoney(x.rent)}</b><span>月租</span></div><div class="metric"><b>${x.area} 呎</b><span>实用面积</span></div><div class="metric"><b>${x.age_years??'—'}${x.age_years!=null?' 年':''}</b><span>楼龄</span></div></div><div class="facts"><div class="fact"><span>早班 / 金钟</span>${c.label}</div><div class="fact"><span>港铁</span>${x.mtr_station||x.district}${x.mtr_walk_min!=null?` · 步行${x.mtr_walk_min}分钟`:''} · ${x.admiralty_route||'路线待确认'}</div><div class="fact"><span>值得看</span>${up.length?up.join(' · '):'综合条件有可比性'}</div><div class="fact"><span>主要取舍</span>${tr.length?tr.join(' · '):'暂无明显短板'}</div><div class="fact"><span>最后确认</span>${fmtDate(x.last_seen)}</div></div><div class="upgrade"><span>相比基安</span><strong>${rentGain>=0?'+':''}${fmtMoney(rentGain).replace('HK$-','-HK$')}/月 · ${areaGain>=0?'+':''}${areaGain}呎</strong></div><div class="listing-actions"><a class="open-link" href="${x.url}" target="_blank" rel="noopener">打开当前房源</a><span class="source">${x.source}</span></div></article>`}
function render(){if(!state.data)return;const verified=state.data.listings.filter(x=>tier(x)!=='D'),items=sorted(verified.filter(passes));document.querySelector('#listings').innerHTML=items.map(card).join('');document.querySelector('#empty').hidden=items.length>0;document.querySelector('#resultMeta').textContent=`${items.length} 套`;document.querySelector('#coreCount').textContent=verified.filter(x=>tier(x)==='A').length;document.querySelector('#tradeoffCount').textContent=verified.filter(x=>tier(x)==='B').length;document.querySelector('#watchCount').textContent=verified.filter(isWatchlist).length;document.querySelector('#newCount').textContent=verified.filter(x=>x.is_new||x.price_drop>0).length;document.querySelector('#resultTitle').textContent=state.view==='core'?'A 核心盘':state.view==='tradeoff'?'B 权衡盘':state.view==='watch'?'重点屋苑':state.view==='new'?'新盘 / 降价':'全部可权衡候选';document.querySelector('#updatedAt').textContent=state.data.meta?.updated_at?`更新 ${fmtDate(state.data.meta.updated_at)}`:'等待首次刷新';document.querySelector('#refreshStatus').textContent=state.data.meta?.algorithm_version?.startsWith('3.')?(state.data.meta?.status==='ok'?'监控正常':state.data.meta?.status==='partial'?'部分来源异常':'等待刷新'):'等待新版筛选刷新'}
async function boot(){try{const r=await fetch(`./data/listings.json?v=${Date.now()}`,{cache:'no-store'});state.data=await r.json()}catch(e){state.data={meta:{status:'pending'},baseline:{rent:11000,area:224},listings:[]}}render()}
document.addEventListener('click',e=>{const seg=e.target.closest('.seg');if(seg){document.querySelectorAll('.seg').forEach(x=>x.classList.remove('active'));seg.classList.add('active');state.view=seg.dataset.view;render();return}const chip=e.target.closest('.chip');if(chip){const k=chip.dataset.filter;state.filters[k]=!state.filters[k];chip.classList.toggle('active',state.filters[k]);render()}});document.querySelector('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;render()});boot();
