const state={data:null,view:'all',filters:{area:false,rent:false,direct:true,commute:true,split:false},sort:'score'};
const money=n=>`HK$${Number(n||0).toLocaleString('en-HK')}`;
const date=s=>{if(!s)return'—';const d=new Date(s);return Number.isNaN(d.getTime())?s:new Intl.DateTimeFormat('zh-HK',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)};
const er={红磡:['约06:05','excellent',14],大围:['约05:50–05:55','excellent',12],沙田:['约05:45–05:50','safe',9],火炭:['约05:40–05:45','safe',6],大埔墟:['约05:40前','medium',0],太和:['约05:35–05:40','medium',-1],粉岭:['约05:30–05:35','early',-5],上水:['约05:25–05:30','early',-7]};
const isl={坚尼地城:['约05:45–05:50','safe',7],香港大学:['约05:48–05:53','safe',8],西营盘:['约05:50–05:55','safe',9],湾仔:['约06:08–06:12','excellent',16],天后:['约06:00','excellent',13],炮台山:['约05:58–06:02','excellent',12],北角:['约05:55–06:00','excellent',11],鰂鱼涌:['约05:50–05:55','excellent',10],太古:['约05:50','safe',8],西湾河:['约05:45–05:50','safe',7],筲箕湾:['约05:40–05:45','safe',5],柴湾:['约05:35–05:40','medium',0]};
const sil={黄竹坑:['约05:58–06:02','excellent',13],利东:['约05:55–06:00','excellent',14],海怡半岛:['约05:52–05:58','excellent',12]};
const fragile=new Set(['荃湾','大窝口','葵兴','葵芳','荔景','美孚','荔枝角','长沙湾','深水埗']);
const midTW=new Set(['太子','旺角','油麻地','佐敦','尖沙咀']);
const priority=new Set(['北角','鰂鱼涌','西湾河','长沙湾','鸭脷洲','大围','沙田','红磡','柴湾','粉岭','坚尼地城','西营盘','湾仔']);
const fallbackWatch=['惠利大廈','金海大廈','中興大廈','東發大廈','曉悅','睿峰','美居中心','嘉裕居','黃金大廈','昌遠大廈','喜居','柏傲莊','金獅花園','沙田中心','紅磡灣中心','環海東岸','雅麗閣','粉嶺名都','粉嶺中心','牽晴間','海都樓','錦興大廈','李節花園','壹嘉','維峯','維峯浚匯'];
const estate=x=>String(x.estate||x.title||'');
const watch=x=>(state.data?.meta?.watchlist_estates||fallbackWatch).some(n=>estate(x).includes(n));
const badge=(s,c='')=>`<span class="badge ${c}">${s}</span>`;
function commute(x){const r=x.admiralty_route||'',s=x.mtr_station||'';let p;if(r.includes('南港岛线')){p=sil[s]||['约05:55–06:00','excellent',12];return{ok:true,leave:p[0],risk:p[1],bonus:p[2],label:`06:30稳达 · 建议${p[0]}出门`}}if(r.includes('港岛线')){p=isl[s]||['约05:45–05:55','safe',6];return{ok:true,leave:p[0],risk:p[1],bonus:p[2],label:`06:30稳达 · 建议${p[0]}出门`}}if(r.includes('东铁线')){p=er[s]||['约05:45–05:55','safe',5];return{ok:true,leave:p[0],risk:p[1],bonus:p[2],label:`06:30可达 · 建议${p[0]}出门`}}if(r.includes('荃湾线')){if(fragile.has(s))return{ok:true,risk:'fragile',bonus:-10,label:'06:30理论可达 · 基本依赖首班'};if(midTW.has(s))return{ok:true,risk:'tight',bonus:-4,label:'06:30可达 · 首班容错较低'};return{ok:true,risk:'tight',bonus:-3,label:'06:30可达 · 早班容错一般'}}return{ok:false,risk:'fail',bonus:-20,label:'06:30到达未验证'}}
const baseOK=x=>x.type_verified===true&&x.mtr_verified===true&&x.shared!==true;
function tier(x){const c=commute(x);if(!baseOK(x)||!c.ok)return'D';if(x.area>=300&&x.rent<=15000&&x.mtr_walk_min<=5&&x.lift===true&&x.window_ac!==true&&!['fragile','early','fail'].includes(c.risk))return'A';if(x.area>=260&&x.rent<=18000&&x.mtr_walk_min<=10&&c.risk!=='fail')return'B';if(x.area>=250&&x.rent<=22000&&x.mtr_walk_min<=12)return'C';return'D'}
function score(x){let s=x.score||0;s+=commute(x).bonus;s+=x.rent<=14000?6:x.rent<=15000?3:x.rent<=16000?0:x.rent<=18000?-5:-10;s+=x.area>=400?8:x.area>=350?6:x.area>=300?3:x.area<280?-5:0;s+=priority.has(x.district)?3:0;s+=watch(x)?5:0;s+=tier(x)==='A'?8:tier(x)==='B'?2:-4;s+=x.split_ac===true?6:x.ac_present?1:0;return Math.max(0,Math.min(99,s))}
function tradeoffs(x){const a=[],c=commute(x);if(x.rent>18000)a.push('租金明显超预算');else if(x.rent>15000)a.push(`比15k高${money(x.rent-15000)}`);if(x.area<300)a.push(`面积${x.area}呎`);if(x.mtr_walk_min>5)a.push(`港铁步行${x.mtr_walk_min}分钟`);if(['fragile','tight'].includes(c.risk))a.push('早班容错低');if(c.risk==='early')a.push('需要很早出门');if(x.split_ac!==true)a.push(x.ac_present?'冷气类型待确认':'冷气待确认');if(x.wet_dry!==true)a.push('干湿分离待确认');if(x.age_years>=45)a.push(`楼龄${x.age_years}年`);return a.slice(0,4)}
function upsides(x){const b=state.data?.baseline||{rent:11000,area:224},a=[],c=commute(x);if(x.area-b.area>=100)a.push(`比基安多${x.area-b.area}呎`);else if(x.area>=300)a.push(`${x.area}呎空间升级`);if(x.rent<=14000)a.push('租金接近原预算');if(c.risk==='excellent')a.push('早班通勤明显更好');if(x.split_ac===true)a.push('分体冷气已确认');if(watch(x))a.push('重点屋苑');return a.slice(0,3)}
function badges(x){const a=[],t=tier(x),c=commute(x);a.push(badge(t==='A'?'A 核心候选':t==='B'?'B 权衡':'C 机会',t==='A'?'good':t==='B'?'warn':'neutral'));if(x.is_new)a.push(badge('新盘','new'));if(x.price_drop>0)a.push(badge(`降价 ${money(x.price_drop)}`,'new'));if(watch(x))a.push(badge('重点屋苑','good'));if(c.risk==='excellent')a.push(badge('早班通勤优','good'));else if(['fragile','tight','early'].includes(c.risk))a.push(badge(c.risk==='early'?'需很早出门':'早班容错低','warn'));if(x.split_ac===true)a.push(badge('分体冷气已确认','good'));else a.push(badge(x.ac_present?'有冷气·类型待确认':'冷气待确认','warn'));if(x.wet_dry===true)a.push(badge('干湿分离','good'));if(x.lift===true)a.push(badge('有电梯','good'));return a.join('')}
function passes(x){if(tier(x)==='D')return false;if(state.view==='core'&&tier(x)!=='A')return false;if(state.view==='tradeoff'&&tier(x)!=='B')return false;if(state.view==='watch'&&!watch(x))return false;if(state.view==='new'&&!x.is_new&&!(x.price_drop>0))return false;if(state.filters.area&&x.area<300)return false;if(state.filters.rent&&x.rent>16000)return false;if(state.filters.direct&&!x.direct_to_admiralty)return false;if(state.filters.commute&&!commute(x).ok)return false;if(state.filters.split&&x.split_ac!==true)return false;return true}
function sort(items){return[...items].sort((a,b)=>state.sort==='area'?b.area-a.area:state.sort==='rent'?a.rent-b.rent:state.sort==='fresh'?String(b.last_seen).localeCompare(String(a.last_seen)):score(b)-score(a)||a.rent-b.rent)}
function card(x){const b=state.data.baseline,c=commute(x),rg=x.rent-b.rent,ag=x.area-b.area;return`<article class="listing"><div class="listing-top"><div class="listing-title"><h2>${estate(x)}</h2><p>${x.district}${x.unit?` · ${x.unit}`:''}${x.rooms?` · ${x.rooms}房`:''}</p></div><div class="score">${score(x)}</div></div><div class="badges">${badges(x)}</div><div class="metrics"><div class="metric"><b>${money(x.rent)}</b><span>月租</span></div><div class="metric"><b>${x.area} 呎</b><span>实用面积</span></div><div class="metric"><b>${x.age_years??'—'}${x.age_years!=null?' 年':''}</b><span>楼龄</span></div></div><div class="facts"><div class="fact"><span>早班 / 金钟</span>${c.label}</div><div class="fact"><span>港铁</span>${x.mtr_station||x.district}${x.mtr_walk_min!=null?` · ${x.mtr_walk_min}分钟`:''} · ${x.admiralty_route||'路线待确认'}</div><div class="fact"><span>值得看</span>${upsides(x).join(' · ')||'综合条件有可比性'}</div><div class="fact"><span>主要取舍</span>${tradeoffs(x).join(' · ')||'暂无明显短板'}</div><div class="fact"><span>最后确认</span>${date(x.last_seen)}</div></div><div class="upgrade"><span>相比基安</span><strong>${rg>=0?'+':''}${money(rg).replace('HK$-','-HK$')}/月 · ${ag>=0?'+':''}${ag}呎</strong></div><div class="listing-actions"><a class="open-link" href="${x.url}" target="_blank" rel="noopener">打开当前房源</a><span class="source">${x.source}</span></div></article>`}
function render(){if(!state.data)return;const all=state.data.listings.filter(x=>tier(x)!=='D'),items=sort(all.filter(passes));document.querySelector('#listings').innerHTML=items.map(card).join('');document.querySelector('#empty').hidden=items.length>0;document.querySelector('#resultMeta').textContent=`${items.length} 套`;document.querySelector('#coreCount').textContent=all.filter(x=>tier(x)==='A').length;document.querySelector('#tradeoffCount').textContent=all.filter(x=>tier(x)==='B').length;document.querySelector('#watchCount').textContent=all.filter(watch).length;document.querySelector('#newCount').textContent=all.filter(x=>x.is_new||x.price_drop>0).length;document.querySelector('#resultTitle').textContent=state.view==='core'?'A 核心候选':state.view==='tradeoff'?'B 权衡盘':state.view==='watch'?'重点屋苑':state.view==='new'?'新盘 / 降价':'全部可权衡候选';document.querySelector('#updatedAt').textContent=state.data.meta?.updated_at?`更新 ${date(state.data.meta.updated_at)}`:'等待首次刷新';document.querySelector('#refreshStatus').textContent=state.data.meta?.status==='ok'?'监控正常':state.data.meta?.status==='partial'?'部分来源异常':'等待刷新'}
async function boot(){try{state.data=await(await fetch(`./data/listings.json?v=${Date.now()}`,{cache:'no-store'})).json()}catch(e){state.data={meta:{status:'pending'},baseline:{rent:11000,area:224},listings:[]}}render()}
document.addEventListener('click',e=>{const s=e.target.closest('.seg');if(s){document.querySelectorAll('.seg').forEach(x=>x.classList.remove('active'));s.classList.add('active');state.view=s.dataset.view;render();return}const c=e.target.closest('.chip');if(c){const k=c.dataset.filter;state.filters[k]=!state.filters[k];c.classList.toggle('active',state.filters[k]);render()}});document.querySelector('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;render()});boot();