import type { GameState, ReelSymbol, Unit, UnitType } from '../core/types';
import { ENEMIES, EVOLUTION, MAX_UNITS, MAX_WAVE, UNIT_TYPES } from '../data/gameData';

export type ActionHandler=(action:string,data:DOMStringMap)=>void;
export class UiRenderer {
  private debugHidden=true;
  constructor(private root:HTMLElement, private onAction:ActionHandler, private shopPrice:(offer:{price:number})=>number=(o)=>o.price){root.addEventListener('click',e=>{const el=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');if(el&&!el.hasAttribute('disabled'))this.onAction(el.dataset.action||'',el.dataset)});}
  setDebugHidden(v:boolean){this.debugHidden=v;const d=document.querySelector('.debug-diag');d?.classList.toggle('hidden',v)}
  render(s:GameState, diagnostics?:string){
    const live=this.root.querySelector<HTMLElement>('main.game');
    const overlay=s.screen==='reward'||!!s.absorb||s.screen==='over';
    if(live&&s.screen==='game'&&!overlay&&(s.reel.spinning||s.phase==='battle')){this.patchLive(s,diagnostics);return}
    this.root.innerHTML=s.screen==='menu'?this.menu():this.game(s)+(s.screen==='reward'?this.reward(s):'')+(s.absorb?this.absorb(s):'')+(s.screen==='over'?this.over(s):'');
    if(diagnostics)this.root.insertAdjacentHTML('beforeend',`<div class="debug-diag ${this.debugHidden?'hidden':''}">${diagnostics}</div>`)
  }
  private patchLive(s:GameState,diagnostics?:string){
    const vals=this.root.querySelectorAll<HTMLElement>('.hudbox .v');if(vals[0])vals[0].textContent=`${s.wave}/12`;if(vals[1])vals[1].textContent=String(s.base);if(vals[2])vals[2].textContent=String(s.gold);
    const machine=this.root.querySelector<HTMLElement>('.machine');if(machine)machine.outerHTML=this.machine(s);
    const stage=this.root.querySelector<HTMLElement>('.stage');if(stage){
      stage.dataset.three=s.threeEnabled?'on':'off';
      const msg=stage.querySelector<HTMLElement>('.stage-msg');if(msg)msg.textContent=s.phase==='battle'&&s.battle?s.battle.msg:s.toast;
      const allies=s.phase==='battle'&&s.battle?s.battle.allies:s.units.slice(0,s.fieldCap).map((u,i)=>({...u,idx:i,maxHp:u.hp,shield:0,cd:0,dead:false}));
      const enemies=s.phase==='battle'&&s.battle?s.battle.enemies:[];
      const combat=stage.querySelector<HTMLElement>('.combat-layer');if(combat)combat.innerHTML=allies.map((x,i)=>this.combatant(x,i,false)).join('')+enemies.map((x,i)=>this.combatant(x,i,true)).join('');
      const forecast=stage.querySelector<HTMLElement>('.forecast');if(forecast)forecast.innerHTML=s.phase==='prep'?this.previewEnemies(s.wave):'';
      const toggle=stage.querySelector<HTMLButtonElement>('.three-toggle');if(toggle){toggle.classList.toggle('active',s.threeEnabled);toggle.textContent=s.threeEnabled?'3D ON':'2D'}
      const speed=stage.querySelector<HTMLButtonElement>('.speed-cta');if(speed){speed.textContent=`${s.battleSpeed}×`;speed.disabled=s.phase!=='battle'}
      const battle=stage.querySelector<HTMLButtonElement>('.battle-cta');if(battle){battle.textContent=s.phase==='battle'?'战斗中':'迎战';battle.disabled=s.phase!=='prep'||!s.units.length}
    }
    const toast=this.root.querySelector<HTMLElement>('.toast');if(toast)toast.innerHTML=`<strong>当前：</strong>${s.toast}`;
    let diag=this.root.querySelector<HTMLElement>('.debug-diag');if(diagnostics){if(!diag){diag=document.createElement('div');diag.className='debug-diag';this.root.appendChild(diag)}diag.textContent=diagnostics;diag.classList.toggle('hidden',this.debugHidden)}
  }
  private menu(){const demo:UnitType[]=['guard','cavalry','ranger','mage','guard','cavalry','mage','ranger','guard'];return`<div class="menu"><section class="menu-card"><div class="menu-hero"><div class="moon"></div><div class="menu-title"><div class="eyebrow">THREEJS-GAME-SKILLS REFACTOR</div><h1>命运<span>守线</span></h1><p>Warrior / Cavalry / Archer / Mage reels → Nudge → Random Stats → Absorb / Evolve → Shop / Cores → Formation → Auto Battle.</p></div><div class="menu-machine"><div class="menu-reels">${demo.map(k=>`<div>${this.sigil(k)}</div>`).join('')}</div></div></div><div class="menu-copy"><div class="menu-features"><div class="feature"><b>Replica loop preserved</b><p>v0.10 gameplay is the behavior baseline.</p></div><div class="feature"><b>Single game owner</b><p>No more v06→v10 global override chain.</p></div><div class="feature"><b>Seeded RNG</b><p>Reels, stats, shop and combat are deterministic in tests.</p></div><div class="feature"><b>Three.js renderer isolated</b><p>3D consumes state/events; it never owns combat rules.</p></div></div><button class="big-cta" data-action="start">开始这一局</button><div class="version">v0.11 Architecture Refactor · behavior-preserving</div></div></section></div>`}
  private game(s:GameState){return`<main class="game"><header class="hud"><div class="brand"><b>REEL WARDENS</b><span>命运守线 · v0.11 REFACTOR</span></div><div class="hudbox"><div class="k">WAVE</div><div class="v">${s.wave}/12</div></div><div class="hudbox hp"><div class="k">HEART</div><div class="v">${s.base}</div></div><div class="hudbox gold"><div class="k">GOLD</div><div class="v">${s.gold}</div></div></header><div class="wavebar"><span class="label">RUN</span><div class="wave-dots">${Array.from({length:MAX_WAVE},(_,i)=>`<i class="wave-dot ${i+1<s.wave?'done':''} ${i+1===s.wave?'current':''} ${i+1===6||i+1===12?'boss':''}"></i>`).join('')}</div></div>${this.stage(s)}${this.machine(s)}${s.phase==='prep'?this.shop(s)+this.formation(s):''}${this.roster(s)}${this.loadout(s)}<div class="toast"><strong>当前：</strong>${s.toast}</div><div class="arch-badge">single Game owner · seeded RNG · explicit update order · Three render-only</div></main>`}
  private stage(s:GameState){const label=s.wave===12?'BOSS':s.wave===6?'JUDGEMENT':'WAVE';const allies=s.phase==='battle'&&s.battle?s.battle.allies:s.units.slice(0,s.fieldCap).map((u,i)=>({...u,idx:i,maxHp:u.hp,shield:0,cd:0,dead:false}));const enemies=s.phase==='battle'&&s.battle?s.battle.enemies:[];return`<section class="stage" data-three="${s.threeEnabled?'on':'off'}"><div class="moon"></div><div class="castle"></div><div class="portal"></div><div class="lane"></div><div class="stage-title"><span class="stage-pill ${s.wave===6||s.wave===12?'boss':''}">${label} ${s.wave}</span></div><div class="stage-msg">${s.phase==='battle'&&s.battle?s.battle.msg:s.toast}</div><div class="combat-layer">${allies.map((x,i)=>this.combatant(x,i,false)).join('')}${enemies.map((x,i)=>this.combatant(x,i,true)).join('')}</div><div class="stage-footer"><div class="forecast">${s.phase==='prep'?this.previewEnemies(s.wave):''}</div><div class="stage-actions"><button class="three-toggle ${s.threeEnabled?'active':''}" data-action="three">${s.threeEnabled?'3D ON':'2D'}</button><button class="speed-cta" data-action="speed" ${s.phase!=='battle'?'disabled':''}>${s.battleSpeed}×</button><button class="battle-cta" data-action="battle" ${s.phase!=='prep'||!s.units.length?'disabled':''}>${s.phase==='battle'?'战斗中':'迎战'}</button></div></div></section>`}
  private combatant(x:any,i:number,enemy:boolean){const row=Math.floor(i/2),col=i%2,ys=[86,128,170],left=enemy?(col?69:83):(col?31:17),hp=x.maxHp?Math.max(0,x.hp/x.maxHp*100):100;return`<div class="combatant ${enemy?'enemy-side':''} ${x.dead?'dead':''}" data-cid="${x.id}" style="left:${left}%;top:${(ys[row]||170)-48}px"><span class="star">${enemy?'':`${x.star}★`}</span><div class="sprite ${enemy?'enemy ':''}${x.type}"><i class="head"></i><i class="body"></i><i class="leg a"></i><i class="leg b"></i><i class="weapon"></i></div><div class="unit-name">${x.name}</div><div class="mini-hp"><i style="width:${hp}%"></i></div></div>`}
  private previewEnemies(w:number){const ks=w===12?['boss','seer','brute']:w===6?['brute','seer','spitter','brute','seer']:['crawler','spitter','brute'];return ks.map(k=>`<span class="enemy-icon">${ENEMIES[k as keyof typeof ENEMIES].icon}</span>`).join('')}
  private machine(s:GameState){let reels='';for(let c=0;c<3;c++){reels+='<div class="reelcol">';for(let r=0;r<3;r++){const i=r*3+c;reels+=this.cell(s.reel.board[i]!,i,s)}reels+='</div>'}return`<section class="machine"><div class="machine-head"><div class="machine-title"><b>命运转轮</b><span>3×3 · 8 PAYLINES</span></div><div class="machine-meta"><span class="odds">NUDGE ${s.nudge}</span><span class="cost">NEXT ${s.spinCost}</span></div></div><div class="reels-wrap"><div class="reels">${reels}</div>${s.lines.length?`<svg class="paylines" viewBox="0 0 100 100" preserveAspectRatio="none">${s.lines.map(l=>`<polyline class="payline" points="${l.pts}"/>`).join('')}</svg>`:''}<div class="lever"><div class="lever-stick"><i class="lever-knob"></i></div></div>${s.jack?`<div class="jackpot ${s.lines.length>=5?'prism':''}"><div>${s.lines.length>=5?'PRISM JACKPOT':'JACKPOT'} ×${s.lines.length}</div></div>`:''}</div><div class="match-row">${s.lines.length?s.lines.map(l=>`<span class="match-chip">${l.name} · ${UNIT_TYPES[l.key].name}</span>`).join(''):`<span class="match-chip dim">3 symbols / line recruit a unit</span>`}</div><div class="machine-actions"><button class="btn utility ${s.reel.nudgeArmed?'armed':''}" data-action="nudge" ${s.nudge<=0||s.reel.nudgeArmed||s.phase!=='prep'?'disabled':''}>${s.reel.nudgeArmed?'NUDGE READY':`NUDGE ×${s.nudge}`}</button><button class="btn spin" data-action="spin" ${s.phase!=='prep'||s.gold<s.spinCost||s.reel.spinning?'disabled':''}>SPIN · ${s.spinCost} GOLD</button></div></section>`}
  private cell(k:ReelSymbol,i:number,s:GameState){const spinning=s.reel.spinning&&!s.reel.stopped[i%3],golden=s.reel.goldenCell===i&&!spinning;const hit=s.hitCells.includes(i);if(k==='jester')return`<div class="cell ${spinning?'spinning':''} ${hit?'hit':''} ${golden?'golden-symbol':''}"><div class="sym"><div class="sigil">♜</div><small>Jester</small><div class="rare">WILD</div></div></div>`;const t=UNIT_TYPES[k];return`<div class="cell ${spinning?'spinning':''} ${hit?'hit':''} ${golden?'golden-symbol':''}" style="background:linear-gradient(180deg,${this.alpha(t.color,.16)},#0f151e)"><div class="sym"><div class="sigil">${this.sigil(k)}</div><small>${t.name}</small><div class="rare">${k.toUpperCase()}</div></div></div>`}
  private roster(s:GameState){const cards=s.units.map((u,i)=>`<div class="ucard replica ${u.type==='prism'?'legendary':''} ${s.selected===u.id?'selected':''}"><button class="ucard-hit" data-action="unit" data-id="${u.id}"><div class="top"><span class="mini-sigil">${this.sigil(u.type)}</span><span class="stars">${'★'.repeat(u.star)}${'☆'.repeat(3-u.star)}</span></div><div class="uname">${u.name} · LV.${u.level}</div><div class="ustats"><span>⚔ ${u.atk}</span><span>♥ ${u.hp}</span><span>SPD ${u.spd}</span></div><div class="random-stats">${u.randomStats.slice(0,4).map(x=>`<span class="rstat">${x.label} +${x.value}${x.suffix}</span>`).join('')}</div><div class="imprint-line"><b>${u.imprint}</b><span>${u.imprints[0]?.desc||''}</span></div><div class="evo-line">${this.evoText(u)}</div></button><button class="mini-action" data-action="lock" data-id="${u.id}">${u.locked?'UNLOCK':'LOCK'}</button><small>${i<s.fieldCap?'FIELD':'BENCH'}</small></div>`).join('');return`<section class="section roster-replica"><div class="section-head"><b>ROSTER · RANDOM STATS</b><span>${s.selected?'选择目标以预览吸收':`FIELD ${Math.min(s.units.length,s.fieldCap)}/${s.fieldCap} · BENCH ${Math.max(0,s.units.length-s.fieldCap)}`}</span></div><div class="bench">${cards}${Array.from({length:Math.max(0,MAX_UNITS-s.units.length)},()=>`<div class="empty-card">EMPTY</div>`).join('')}</div></section>`}
  private evoText(u:Unit){const path=EVOLUTION[u.type];if(!path)return`吸收进度 ${u.evoProgress}/10`;const next=path.find(x=>x.progress>u.evoProgress);return next?`${u.name} → ${next.name} · ${u.evoProgress}/${next.progress}`:`MAX · ${path.at(-1)!.name}`}
  private shop(s:GameState){return`<section class="section replica-panel shop-panel"><div class="section-head"><b>SHOP</b><button class="mini-action" data-action="reroll">REROLL ${20+s.shopRerolls*10}</button></div><div class="shop-row">${s.shopOffers.map(o=>`<div class="shop-card ${o.offerKind} ${o.sold?'sold':''}"><div class="shop-tag">${o.tag}</div><b>${o.name}</b><p>${o.desc}</p><button data-action="buy" data-id="${o.offerId}" ${o.sold?'disabled':''}>${o.sold?'SOLD':`${this.shopPrice(o)} GOLD`}</button></div>`).join('')}</div></section>`}
  private formation(s:GameState){const slots=Array.from({length:6},(_,i)=>{const u=s.units[i],sel=s.formationSelected===i,active=i<s.fieldCap;return`<button class="formation-slot ${sel?'selected':''} ${u?'filled':'empty'} ${active?'':'bench-slot'}" data-action="formation" data-index="${i}" ${u?'':'disabled'}><small>${i<2?'FRONT':i<4?'MID':'BACK'} ${i%2+1}</small>${u?`<b>${u.name}</b><span>${active?'FIELD':'BENCH'}</span>`:'<b>EMPTY</b>'}</button>`}).join('');return`<section class="section replica-panel formation-panel"><div class="section-head"><b>FORMATION</b><span>点两个位置交换 · Boss 会打后排</span></div><div class="formation-grid">${slots}</div></section>`}
  private loadout(s:GameState){return`<details class="loadout-drawer" open><summary><b>CORES ${s.cores.length} · ITEMS ${s.items.length}</b><span>no artificial Core cap</span></summary><div class="core-loadout rw10-core-scroll">${s.cores.length?s.cores.map(c=>`<div class="load-core filled"><small>${c.tag}</small><b>${c.name}</b><span>${c.desc}</span></div>`).join(''):`<div class="load-core empty"><b>NO CORE</b></div>`}</div><div class="item-inventory">${s.items.length?s.items.map(it=>`<div class="inv-item"><div><small>${it.tag}</small><b>${it.name}</b><span>${it.desc}</span></div><button data-action="item" data-id="${it.instanceId}">USE</button></div>`).join(''):`<div class="inv-empty">No Items</div>`}</div></details>`}
  private reward(s:GameState){return`<div class="overlay"><div class="sheet"><div class="eyebrow">MILESTONE REWARD</div><h1>Item / Core / Gold</h1><div class="choices">${s.rewardChoices.map(r=>`<button class="choice" data-action="reward" data-id="${r.rewardId}"><span class="tag">${r.tag}</span><h3>${r.name}</h3><p>${r.desc}</p><div class="bonus">选择</div></button>`).join('')}</div></div></div>`}
  private absorb(s:GameState){const a=s.absorb!,src=s.units.find(u=>u.id===a.src),tgt=s.units.find(u=>u.id===a.tgt);if(!src||!tgt)return'';return`<div class="overlay absorb-overlay"><div class="sheet absorb-sheet"><div class="eyebrow">ABSORPTION PREVIEW</div><h1>${src.name} → ${tgt.name}</h1><p>素材会永久消失。${a.preview.same?'同职业转移效率更高。':'跨职业只继承部分成长。'}</p><div class="transfer-grid"><div><span>基础继承</span><b>ATK +${a.preview.gainAtk} · HP +${a.preview.gainHp}</b></div><div><span>进化</span><b>+${a.preview.progress}</b></div><div class="wide"><span>Random Stats</span><b>${a.preview.statTransfers.slice(0,4).map(x=>`${x.label}+${x.value}${x.suffix}`).join(' · ')}</b></div><div class="wide"><span>Imprint</span><b>${a.preview.imprintNames.join(' · ')||'不转移'}</b></div></div><div class="absorb-actions"><button class="btn utility" data-action="absorb-cancel">取消</button><button class="btn spin" data-action="absorb-confirm">确认吸收</button></div></div></div>`}
  private over(s:GameState){return`<div class="overlay"><div class="sheet"><div class="eyebrow">RUN COMPLETE</div><h1>${s.base>0?'守线成功':'防线崩溃'}</h1><p>最终分数 ${s.score} · 本机最高 ${s.high}</p><button class="big-cta" data-action="restart">再来一局</button></div></div>`}
  private sigil(k:UnitType){const c=UNIT_TYPES[k].color,common=`fill="none" stroke="${c}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"`;let p='';if(k==='guard')p=`<path ${common} d="M12 3l7 3v6c0 5-3 8-7 10-4-2-7-5-7-10V6l7-3z"/><path ${common} d="M8 10h8M12 6v12"/>`;else if(k==='ranger')p=`<path ${common} d="M7 4c6 4 6 12 0 16M17 4c-6 4-6 12 0 16M7 12h10"/><path ${common} d="M14 9l3 3-3 3"/>`;else if(k==='mage')p=`<path ${common} d="M12 3l3 6 6 3-6 3-3 6-3-6-6-3 6-3 3-6z"/><circle ${common} cx="12" cy="12" r="2.5"/>`;else if(k==='cavalry')p=`<path ${common} d="M5 17c2-6 4-10 9-11l4 3-3 2 2 6H5z"/><path ${common} d="M9 17v4M15 17v4"/>`;else p=`<path ${common} d="M12 2l6 5-2 9-4 6-4-6-2-9 6-5z"/>`;return`<svg viewBox="0 0 24 24">${p}</svg>`}
  private alpha(hex:string,a:number){const v=parseInt(hex.slice(1),16),r=v>>16,g=v>>8&255,b=v&255;return`rgba(${r},${g},${b},${a})`}
}
