import type { Combatant, Enemy, EnemyType, GameState, Unit } from '../core/types';
import type { Rng } from '../core/rng';
import { chance, pick } from '../core/rng';
import { ENEMIES, MAX_WAVE } from '../data/gameData';
import type { EventBus } from '../core/EventBus';
import type { UnitSystem } from './UnitSystem';
import type { ShopSystem } from './ShopSystem';
import { writeHigh } from '../core/storage';

export class CombatSystem {
  private accum=0;
  constructor(private state:GameState, private rng:()=>Rng, private units:UnitSystem, private shop:ShopSystem, private bus:EventBus){}
  private hasCore(id:string){return this.state.cores.some(c=>c.id===id)}
  start(){
    if(this.state.phase!=='prep'||!this.state.units.length)return false;
    this.state.phase='battle';this.accum=0;
    this.state.battle={allies:this.state.units.slice(0,this.state.fieldCap).map((u,i)=>this.mkAlly(u,i)),enemies:this.enemyPool(this.state.wave).map((k,i)=>this.mkEnemy(k,i)),msg:this.state.wave===12?'BOSS begins':this.state.wave===6?'JUDGEMENT begins':`Wave ${this.state.wave} begins`,elapsed:0};
    if(this.state.guardNext&&this.state.battle.allies.length){this.state.battle.allies[0]!.invulnTicks=30;this.state.guardNext=false;}
    (this.state as any).nextAtkBuff=0;(this.state as any).nextHpBuff=0;
    return true;
  }
  update(dt:number){if(this.state.phase!=='battle'||!this.state.battle)return;const b=this.state.battle,speed=this.state.battleSpeed;this.accum+=dt*speed;b.elapsed+=dt*speed;while(this.accum>=.23){this.accum-=.23;for(const a of b.allies)if(a.hp>0){if(a.invulnTicks&&a.invulnTicks>0)a.invulnTicks--;a.cd-=.23*a.spd}for(const e of b.enemies)if(e.hp>0)e.cd-=.23*e.spd;for(const a of b.allies)if(a.hp>0&&a.cd<=0){a.cd=1;this.allyAct(a);if(this.checkEnd())return}for(const e of b.enemies)if(e.hp>0&&e.cd<=0){e.cd=1;this.enemyAct(e);if(this.checkEnd())return}}}
  private enemyPool(w:number):EnemyType[]{if(w===12)return['boss','seer','brute'];if(w===6)return['brute','seer','spitter','brute','seer'];const n=Math.min(5,2+Math.floor((w+1)/2));const pool:EnemyType[]=w%4===0?['brute','spitter','seer']:['crawler','crawler','spitter','brute'];return Array.from({length:n},()=>pick(this.rng(),pool));}
  private mkEnemy(type:EnemyType,i:number):Enemy{const t=ENEMIES[type],w=this.state.wave,s=1+(w-1)*.13+(type==='boss'?.5:0);const e:Enemy={id:`e${++this.state.serial}`,type,name:type==='boss'?'Beholder':t.name,idx:i,maxHp:Math.round(t.hp*s),hp:Math.round(t.hp*s),atk:Math.round(t.atk*(1+(w-1)*.1+(type==='boss'?.35:0))),spd:t.spd,cd:this.rng()()*.65,shield:0,dead:false};if(w===6){e.elite=true;e.name=`Elite ${e.name}`;e.maxHp=Math.round(e.maxHp*1.34);e.hp=e.maxHp;e.atk=Math.round(e.atk*1.24);e.spd=+(e.spd*1.06).toFixed(2)}return e;}
  private mkAlly(u:Unit,i:number):Combatant{let atk=u.atk*(1+(u.star-1)*.34),hp=u.hp*(1+(u.star-1)*.38),spd=u.spd;const atkBuff=(this.state as any).nextAtkBuff||0,hpBuff=(this.state as any).nextHpBuff||0;atk*=1+atkBuff;hp*=1+hpBuff;if(this.hasCore('vanguard')&&i<2)hp*=1.2;const a:Combatant={...structuredClone(u),idx:i,maxHp:Math.round(hp),hp:Math.round(hp),atk:+atk.toFixed(1),spd:+spd.toFixed(2),crit:u.crit,cd:this.rng()()*.6,shield:0,dead:false};if(u.name==='Paladin')a.shield+=Math.round(a.maxHp*.24);if(u.name==='Veil'){a.shield+=Math.round(a.maxHp*.42);a.veilSave=true}return a;}
  private alive<T extends {hp:number}>(a:T[]){return a.filter(x=>x.hp>0)}
  private targetEnemy(){return this.state.battle?this.alive(this.state.battle.enemies)[0]||null:null}
  private lowestAlly(){return this.state.battle?this.alive(this.state.battle.allies).sort((a,b)=>(a.hp/a.maxHp)-(b.hp/b.maxHp))[0]||null:null}
  private frontTarget(){if(!this.state.battle)return null;const xs=this.alive(this.state.battle.allies).sort((a,b)=>a.idx-b.idx);const front=xs.filter(x=>x.idx<2),pool=front.length?front:xs;return pool.find(x=>x.type==='guard')||pool[0]||null}
  private rearTarget(){if(!this.state.battle)return null;const xs=this.alive(this.state.battle.allies).sort((a,b)=>b.idx-a.idx);return xs[0]||null}
  private damage(t:{hp:number;shield:number;dead:boolean;maxHp?:number;invulnTicks?:number;veilSave?:boolean},n:number){if(t.invulnTicks&&t.invulnTicks>0)return 0;const before=t.hp;let v=n;if(t.shield>0){const b=Math.min(t.shield,v);t.shield-=b;v-=b}v=Math.max(0,Math.round(v));t.hp=Math.max(0,t.hp-v);if(t.hp<=0&&t.veilSave&&t.maxHp){t.veilSave=false;t.hp=Math.max(1,Math.round(t.maxHp*.18));t.shield+=Math.round(t.maxHp*.28)}else if(t.hp<=0)t.dead=true;return Math.max(0,before-t.hp);}
  private heal(t:{hp:number;maxHp:number},n:number){const old=t.hp;t.hp=Math.min(t.maxHp,t.hp+Math.round(n));return t.hp-old}
  private allyAct(a:Combatant){const b=this.state.battle!;const t=this.targetEnemy();if(!t)return;let n=a.atk*(a.type==='mage'?(1+a.spellPower):1);let critChance=a.crit+(this.units.hasImprint(a,'spellCrit')&&a.type==='mage'?.08:0);const crit=chance(this.rng(),Math.min(.85,critChance));if(crit)n*=1.72;if(a.type==='ranger'&&this.units.hasImprint(a,'execute')&&t.hp/t.maxHp<.35)n*=1.24;if(a.type==='cavalry'&&this.units.hasImprint(a,'charge')&&b.elapsed<2.5)n*=1.28;const d=this.damage(t,n);if(a.lifesteal>0)this.heal(a,d*a.lifesteal);if(a.type==='mage'&&this.units.hasImprint(a,'arcaneEcho')){const t2=this.alive(b.enemies)[1];if(t2)this.damage(t2,d*.42)}if(a.type==='ranger'&&this.units.hasImprint(a,'doubleShot')&&chance(this.rng(),.18)){const t2=this.targetEnemy();if(t2)this.damage(t2,d*.46)}b.msg=`${a.name} → ${t.name} ${d}${crit?' CRIT':''}`;this.bus.emit({type:'combat:fx',src:a.id,tgt:t.id,kind:a.type==='mage'?'magic':a.type==='guard'||a.type==='cavalry'?'melee':'shot',good:false});}
  private enemyAct(e:Enemy){const b=this.state.battle!;if(e.type==='seer'&&chance(this.rng(),.38)){const t=this.alive(b.enemies).sort((a,c)=>(a.hp/a.maxHp)-(c.hp/c.maxHp))[0];if(t){const h=this.heal(t,e.atk*.82);b.msg=`${e.name} 治疗同伴 +${h}`;return}}let t:Combatant|null;if(e.type==='boss'){e.bossAct=(e.bossAct||0)+1;if(e.bossAct%3===0)t=this.rearTarget();else t=this.frontTarget();}else t=this.frontTarget();if(!t)return;const mult=e.type==='boss'&&e.bossAct&&e.bossAct%3===0?1.35:1;const before=t.hp,d=this.damage(t,e.atk*mult);if(this.units.hasImprint(t,'thorns')&&before>t.hp)this.damage(e,d*.14);b.msg=e.type==='boss'&&mult>1?`Beholder 锁定后排 → ${t.name} ${d}`:`${e.name} → ${t.name} ${d}`;this.bus.emit({type:'combat:fx',src:e.id,tgt:t.id,kind:e.type==='boss'?'enemyMagic':'enemy',good:false});}
  private checkEnd(){const b=this.state.battle!;if(this.alive(b.enemies).length&&this.alive(b.allies).length)return false;if(!this.alive(b.enemies).length)this.winWave();else this.loseWave();return true;}
  private resetPrep(){this.state.phase='prep';this.state.battle=null;this.state.spinCount=0;this.state.spinCost=24;this.state.nudge=1;this.state.reel.nudgeArmed=false;this.state.lines=[];this.state.hitCells=[];this.state.fieldCap=this.state.wave>=6?6:5;this.state.shopWave=0;this.shop.roll(true);}
  private winWave(){const done=this.state.wave,g=55+done*9;this.state.gold+=g;this.state.score+=120+done*42+this.alive(this.state.battle!.allies).length*15;if(done>=MAX_WAVE){this.state.high=Math.max(this.state.high,this.state.score);writeHigh(this.state.high);this.state.screen='over';this.state.phase='over';this.state.battle=null;return}this.state.wave++;this.resetPrep();this.state.toast=`Wave ${done} clear · +${g} Gold · Nudge restored`;if(done%3===0){this.state.rewardChoices=this.shop.rewardChoices();this.state.screen='reward'}}
  private loseWave(){const rem=this.alive(this.state.battle!.enemies).length,loss=Math.min(9,Math.max(2,rem*2+(this.state.wave>=10?2:0)));this.state.base=Math.max(0,this.state.base-loss);if(this.state.base<=0){this.state.high=Math.max(this.state.high,this.state.score);writeHigh(this.state.high);this.state.screen='over';this.state.phase='over';this.state.battle=null;return}const done=this.state.wave;this.state.wave++;this.resetPrep();this.state.toast=`Wave ${done} leak · HEART -${loss} · Nudge restored`;}
}
