import type { GameState, ItemDef, ItemInstance, RewardChoice, ShopOffer, UnitType } from '../core/types';
import type { Rng } from '../core/rng';
import { chance, pick, shuffle } from '../core/rng';
import { CORES, ITEMS } from '../data/gameData';

export class ShopSystem {
  constructor(private state:GameState, private rng:()=>Rng){}
  hasCore(id:string){return this.state.cores.some(c=>c.id===id)}
  price(x:{price:number}){return Math.max(1,Math.ceil(x.price*(this.hasCore('merchant')?.85:1)))}
  roll(force=false){if(!force&&this.state.shopWave===this.state.wave&&this.state.shopOffers.length)return;const itemPool=shuffle(this.rng(),ITEMS),corePool=shuffle(this.rng(),CORES.filter(c=>!this.hasCore(c.id)));const raw:(ItemDef|typeof CORES[number])[]=[itemPool[0]!,itemPool[1]!,chance(this.rng(),.48)&&corePool.length?corePool[0]!:itemPool[2]!];this.state.shopOffers=raw.map((x,i)=>({...x,offerId:`o${++this.state.serial}`,offerKind:('kind' in x?'item':'core') as 'item'|'core',sold:false} as ShopOffer));this.state.shopWave=this.state.wave;this.state.shopRerolls=0;}
  reroll(){if(this.state.phase!=='prep')return;const cost=20+this.state.shopRerolls*10;if(this.state.gold<cost){this.state.toast='Gold 不足，无法刷新 Shop。';return}this.state.gold-=cost;this.state.shopRerolls++;const itemPool=shuffle(this.rng(),ITEMS),corePool=shuffle(this.rng(),CORES.filter(c=>!this.hasCore(c.id)));const raw=[itemPool[0]!,itemPool[1]!,chance(this.rng(),.48)&&corePool.length?corePool[0]!:itemPool[2]!];this.state.shopOffers=raw.map((x,i)=>({...x,offerId:`o${++this.state.serial}`,offerKind:('kind' in x?'item':'core') as 'item'|'core',sold:false} as ShopOffer));this.state.toast=`Shop 刷新 -${cost} Gold。`;}
  buy(offerId:string){const o=this.state.shopOffers.find(x=>x.offerId===offerId&&!x.sold);if(!o||this.state.phase!=='prep')return;const cost=this.price(o);if(this.state.gold<cost){this.state.toast='Gold 不足。';return}this.state.gold-=cost;o.sold=true;if(o.offerKind==='core'){if(!this.hasCore(o.id))this.state.cores.push({id:o.id,name:o.name,desc:o.desc,tag:o.tag,price:o.price});this.state.toast=`装备 Core「${o.name}」。`}else{this.state.items.push({...o,instanceId:`i${++this.state.serial}`} as unknown as ItemInstance);this.state.toast=`购买 Item「${o.name}」。`;}}
  use(instanceId:string){if(this.state.phase!=='prep')return;const i=this.state.items.findIndex(x=>x.instanceId===instanceId);if(i<0)return;const it=this.state.items[i]!;if(it.kind==='repair'){this.state.base=Math.min(30,this.state.base+5);this.state.toast='Repair Kit：HEART +5。'}else if(it.kind==='atk'){(this.state as any).nextAtkBuff=Math.max((this.state as any).nextAtkBuff||0,.18);this.state.toast='War Tonic：下一战 ATK +18%。'}else if(it.kind==='hp'){(this.state as any).nextHpBuff=Math.max((this.state as any).nextHpBuff||0,.22);this.state.toast='Armor Plate：下一战 HP +22%。'}else if(it.kind==='first_guard'){this.state.guardNext=true;this.state.toast='Guardian Charm：下一战首个承伤单位短暂无敌。'}else if(it.kind==='bias'){(this.state as any).itemBias={type:it.classId as UnitType,spins:2};this.state.toast=`${it.name}：接下来 2 次 Spin 偏向对应职业。`;}this.state.items.splice(i,1);}
  rewardChoices():RewardChoice[]{const item=pick(this.rng(),ITEMS),corePool=CORES.filter(c=>!this.hasCore(c.id)),core=corePool.length?pick(this.rng(),corePool):null;const out:RewardChoice[]=[{kind:'item',id:item.id,rewardId:`r${++this.state.serial}`,name:item.name,desc:item.desc,tag:item.tag},core?{kind:'core',id:core.id,rewardId:`r${++this.state.serial}`,name:core.name,desc:core.desc,tag:core.tag}:{kind:'gold',id:'gold',rewardId:`r${++this.state.serial}`,name:'+140 Gold',desc:'直接获得 140 Gold。',tag:'RESOURCE'},{kind:'gold',id:'gold',rewardId:`r${++this.state.serial}`,name:'+140 Gold',desc:'直接获得 140 Gold。',tag:'RESOURCE'}];return shuffle(this.rng(),out)}
  chooseReward(rewardId:string){const r=this.state.rewardChoices.find(x=>x.rewardId===rewardId);if(!r)return;if(r.kind==='core'){const c=CORES.find(x=>x.id===r.id);if(c&&!this.hasCore(c.id))this.state.cores.push({...c});this.state.toast=`Milestone：获得 Core「${r.name}」。`}else if(r.kind==='item'){const it=ITEMS.find(x=>x.id===r.id);if(it)this.state.items.push({...it,instanceId:`i${++this.state.serial}`});this.state.toast=`Milestone：获得 Item「${r.name}」。`}else{this.state.gold+=140;this.state.toast='Milestone：+140 Gold。'}this.state.rewardChoices=[];this.state.screen='game';}
}
