export type RoomStatus = 'available'|'reserved'|'occupied'|'dirty'|'cleaning'|'maintenance'|'unbuilt';
export type FacilityRole = 'lobby'|'breakfast'|'club'|'gym'|'spa'|'rooftop';
export interface Room {extraBed?:boolean;construction?:Construction;suaBookingId?:string;category?:'standard'|'view'|'suite'|'premium';bed?:'king'|'twin';id:string; kind:'room'; floorId:string; number:string; type:'king'|'twin'|'suite'; status:RoomStatus; guestId?:string; nightsLeft:number; timer?:number; level?:number;}
export interface Facility {construction?:Construction;id:string; kind:'facility'; floorId:string; role:FacilityRole; name:string; capacity:number; usage:number; staffing:number; quality:number; maintenance:number;level?:number;}
export type Entity = Room|Facility;
export interface Floor {construction?:Construction;id:string; number:number; label:string; name:string; role:'guest'|FacilityRole; entityIds:string[];}
export type Persona='chill'|'road'|'family'|'points'|'hunter'|'forum'|'creator'|'proposal'|'planner'|'whale'|'auditplus';
export interface WalkPoint {x:number;z:number;level:number;phase:'room'|'corridor'|'elevator'|'public'|'exit';}
export interface GuestMovement {position:WalkPoint;steps:WalkPoint[];destination:string;arrived:boolean;nextDecision:number;trail:WalkPoint[];revision:number;}
export interface Guest {waitingFor?:string;waitSince?:number;profileId?:string;reservationId?:string;bookedRate?:number;source?:Booking['source'];spend?:number;challenge?:{kind:'quiet'|'sua'|'family'|'audit';resolved:boolean;outcome?:string};staffRole?:Department;job?:{kind:'clean'|'repair'|'stock'|'front'|'patrol';target:string;remaining:number;eventId?:number};experience?:{place:string;kind:'served'|'shortage'|'full';at:number};serviceDone?:boolean;persona?:Persona;movement?:GuestMovement;departing?:boolean;exitAt?:number;denied?:boolean;sua?:boolean;goh?:boolean;lateHour?:14|16;late?:'pending'|'honor'|'deny';speech?:{context?:string;next:number;recent:{text:string;at:number}[];event?:string;eventUntil?:number};lastVisit?:string;id:string; name:string; tier:string; roomId?:string; floorId:string; thought:string; color:number; route:number[]; z?:number; staff?:boolean; segment?:string; stayLength?:number; patience?:number; rate?:number; checkoutDay?:number; visitUntil?:number; satisfaction?:number; upgrades?:boolean;}
export interface PreviewState {schemaVersion:8; mode:'visual-slice'|'game'; brandId:'place'; metrics:{cash:number;reputation:number;owner:number}; floors:Floor[]; entities:Record<string,Entity>; guests:Guest[]; selectedId:string|null; focusedFloorId:string|null; speed:1|2|4; atmosphere:'dusk'|'night'|'day'; visited:string[]; game?:Simulation;}
export interface Store {getState():Readonly<PreviewState>; subscribe(fn:(state:Readonly<PreviewState>)=>void):()=>void; select(id:string|null):void; focusFloor(id:string):void; setSpeed(speed:1|2|4):void; setAtmosphere(value:PreviewState['atmosphere']):void; dispatch(command:Command):void; advance(minutes:number):void; reset():void;}
export type Department='front'|'house'|'engineering'|'fnb'|'revenue';
export type LogCategory='入住'|'客诉'|'房态'|'部门'|'收益'|'升级';
export interface LogEntry {id:number;day:number;minute:number;category:LogCategory;text:string;target?:string;}
export interface HotelEvent {id:number;kind:'repair'|'complaint'|'supplies'|'vip';title:string;target:string;expires:number;}
export interface DayReport {day:number;revenue:number;expense:number;adr:number;occupancy:number;revpar:number;upgrades:number;complaints:number;lost:number;recommendation:string;forecastOccupancy?:number;actualEveningOccupancy?:number;bookingsLost?:number;score?:number;}
export interface Task {id:string;title:string;goal:number;progress:number;reward:number;claimed:boolean;target:string;}
export interface Development {counts:Record<string,number>;claimed:string[];campaignUntil:number;activityDay:number;activity?:{id:string;ends:number};scores:{day:number;value:number}[];}
export interface Simulation {operations?:Operations;upgradeEffect?:{id:number;entityId:string};dialogueRecent?:Record<string,number>;guestMemory?:Record<string,{visits:number;satisfaction:number;denied:boolean}>;development?:Development;day:number;minute:number;paused:boolean;seed:number;nextId:number;nextArrival:number;nextEvent:number;price:number;positioning:'business'|'resort'|'urban';weather:'sunny'|'rain';stock:number;clubStock:number;managers:Record<Department,number>;logs:LogEntry[];events:HotelEvent[];tasks:Task[];reports:DayReport[];reportOpen:boolean;revenue:number;expense:number;nights:number;arrivals:number;upgrades:number;complaints:number;lost:number;repLoss:number;roomMinutes:number;soldMinutes:number;closedMinutes:number;memory:Record<string,number>;level:number;notice:string;}
export interface Command {type:'brief-start'|'suite-policy'|'guest-choice'|'configure-room'|'late'|'guest-service'|'build-spa'|'invest'|'train'|'campaign'|'activity'|'claim-career'|'checkin'|'reject'|'clean'|'repair'|'upgrade'|'reserve'|'release'|'hire'|'stock'|'resolve'|'expand'|'price'|'position'|'pause'|'continue'|'claim';id?:string;roomId?:string;value?:number|string;}

export interface Construction {remaining:number;total:number;targetLevel?:number;}
export interface Booking {id:string;profileId:string;source:'APP'|'团单'|'平台'|'Walk-in';eta:number;nights:number;rate:number;segment:'商务'|'度假'|'团队';status:'confirmed'|'arrived'|'lost'|'checkedin';sua?:boolean;roomId?:string;challenge?:'quiet'|'sua'|'family'|'audit';}
export interface GuestProfile {id:string;name:string;persona:Persona;tier:string;visits:number;trust:number;spend:number;history:{day:number;text:string}[];referredBy?:string;}
export interface Forecast {occupancy:number;walkins:number;breakfast:number;housekeeping:number;suites:number;club:number;business:number;resort:number;group:number;price:number;}
export interface Operations {day:number;briefOpen:boolean;event:'normal'|'expo'|'flights'|'storm';bookings:Booking[];profiles:Record<string,GuestProfile>;forecast?:Forecast;suitePolicy:'sell'|'hold';lostBookings:number;confirmedArrivals:number;walkinArrivals:number;hkCompleted:number;stockDelivered:number;}
