export type RoomStatus = 'available'|'reserved'|'occupied'|'dirty'|'cleaning'|'maintenance'|'unbuilt';
export type FacilityRole = 'lobby'|'breakfast'|'club'|'gym'|'spa'|'rooftop';
export interface Room {category?:'standard'|'view'|'suite'|'premium';bed?:'king'|'twin';id:string; kind:'room'; floorId:string; number:string; type:'king'|'twin'|'suite'; status:RoomStatus; guestId?:string; nightsLeft:number; timer?:number; level?:number;}
export interface Facility {id:string; kind:'facility'; floorId:string; role:FacilityRole; name:string; capacity:number; usage:number; staffing:number; quality:number; maintenance:number;level?:number;}
export type Entity = Room|Facility;
export interface Floor {id:string; number:number; label:string; name:string; role:'guest'|FacilityRole; entityIds:string[];}
export type Persona='chill'|'road'|'family'|'points'|'hunter'|'forum'|'creator'|'proposal'|'planner'|'whale'|'auditplus';
export interface WalkPoint {x:number;z:number;level:number;phase:'room'|'corridor'|'elevator'|'public'|'exit';}
export interface GuestMovement {position:WalkPoint;steps:WalkPoint[];destination:string;arrived:boolean;nextDecision:number;trail:WalkPoint[];revision:number;}
export interface Guest {experience?:{place:string;kind:'served'|'shortage'|'full';at:number};serviceDone?:boolean;persona?:Persona;movement?:GuestMovement;departing?:boolean;exitAt?:number;denied?:boolean;sua?:boolean;goh?:boolean;lateHour?:14|16;late?:'pending'|'honor'|'deny';speech?:{context?:string;next:number;recent:{text:string;at:number}[];event?:string;eventUntil?:number};lastVisit?:string;id:string; name:string; tier:string; roomId?:string; floorId:string; thought:string; color:number; route:number[]; z?:number; staff?:boolean; segment?:string; stayLength?:number; patience?:number; rate?:number; checkoutDay?:number; visitUntil?:number; satisfaction?:number; upgrades?:boolean;}
export interface PreviewState {schemaVersion:8; mode:'visual-slice'|'game'; brandId:'place'; metrics:{cash:number;reputation:number;owner:number}; floors:Floor[]; entities:Record<string,Entity>; guests:Guest[]; selectedId:string|null; focusedFloorId:string|null; speed:1|2|4; atmosphere:'dusk'|'night'|'day'; visited:string[]; game?:Simulation;}
export interface Store {getState():Readonly<PreviewState>; subscribe(fn:(state:Readonly<PreviewState>)=>void):()=>void; select(id:string|null):void; focusFloor(id:string):void; setSpeed(speed:1|2|4):void; setAtmosphere(value:PreviewState['atmosphere']):void; dispatch(command:Command):void; advance(minutes:number):void; reset():void;}
export type Department='front'|'house'|'engineering'|'fnb'|'revenue';
export type LogCategory='入住'|'客诉'|'房态'|'部门'|'收益'|'升级';
export interface LogEntry {id:number;day:number;minute:number;category:LogCategory;text:string;target?:string;}
export interface HotelEvent {id:number;kind:'repair'|'complaint'|'supplies'|'vip';title:string;target:string;expires:number;}
export interface DayReport {day:number;revenue:number;expense:number;adr:number;occupancy:number;revpar:number;upgrades:number;complaints:number;lost:number;recommendation:string;score?:number;}
export interface Task {id:string;title:string;goal:number;progress:number;reward:number;claimed:boolean;target:string;}
export interface Development {counts:Record<string,number>;claimed:string[];campaignUntil:number;activityDay:number;activity?:{id:string;ends:number};scores:{day:number;value:number}[];}
export interface Simulation {upgradeEffect?:{id:number;entityId:string};dialogueRecent?:Record<string,number>;guestMemory?:Record<string,{visits:number;satisfaction:number;denied:boolean}>;development?:Development;day:number;minute:number;paused:boolean;seed:number;nextId:number;nextArrival:number;nextEvent:number;price:number;positioning:'business'|'resort'|'urban';weather:'sunny'|'rain';stock:number;clubStock:number;managers:Record<Department,number>;logs:LogEntry[];events:HotelEvent[];tasks:Task[];reports:DayReport[];reportOpen:boolean;revenue:number;expense:number;nights:number;arrivals:number;upgrades:number;complaints:number;lost:number;repLoss:number;roomMinutes:number;soldMinutes:number;closedMinutes:number;memory:Record<string,number>;level:number;notice:string;}
export interface Command {type:'configure-room'|'late'|'guest-service'|'build-spa'|'invest'|'train'|'campaign'|'activity'|'claim-career'|'checkin'|'reject'|'clean'|'repair'|'upgrade'|'reserve'|'release'|'hire'|'stock'|'resolve'|'expand'|'price'|'position'|'pause'|'continue'|'claim';id?:string;roomId?:string;value?:number|string;}
