function makeBoard(force){let a=Array.from({length:9},()=>weightedKey());const should=force||(st&&st.spinCount>=1&&chance(own('loaded')?.62:.34));if(should){const l=pick(LINES);const k=weightedKey();l.cells.forEach(i=>a[i]=k)}return a}
function analyze(a){const lines=[],cells=new Set();for(const l of LINES){const [x,y,z]=l.cells;if(a[x]===a[y]&&a[x]===a[z]){lines.push({...l,key:a[x]});l.cells.forEach(i=>cells.add(i))}}return{lines,cells:[...cells]}}
function sigil(k){const c=TYPES[k].color;const common=`fill="none" stroke="${c}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"`;let p='';if(k==='guard')p=`<path ${common} d="M12 3l7 3v6c0 5-3 8-7 10-4-2-7-5-7-10V6l7-3z"/><path ${common} d="M8 10h8M12 6v12"/>`;if(k==='ranger')p=`<path ${common} d="M7 4c6 4 6 12 0 16M17 4c-6 4-6 12 0 16M7 12h10"/><path ${common} d="M14 9l3 3-3 3"/>`;if(k==='mage')p=`<path ${common} d="M12 3l3 6 6 3-6 3-3 6-3-6-6-3 6-3 3-6z"/><circle ${common} cx="12" cy="12" r="2.5"/>`;if(k==='medic')p=`<path ${common} d="M9 3h6v6h6v6h-6v6H9v-6H3V9h6V3z"/>`;if(k==='rogue')p=`<path ${common} d="M17 3l4 4-11 11-5 1 1-5L17 3z"/><path ${common} d="M14 6l4 4M5 19l-2 2"/>`;if(k==='prism')p=`<path ${common} d="M12 2l6 5-2 9-4 6-4-6-2-9 6-5z"/><path ${common} d="M6 7h12M8 16l4-9 4 9"/>`;return`<svg viewBox="0 0 24 24" aria-hidden="true">${p}</svg>`}
function createUnit(k){const t=TYPES[k],im=pick(t.imprints),bonus=1+(Math.random()*.18-.05);return{id:`u${Date.now()}${Math.random().toString(36).slice(2,5)}`,type:k,name:t.name,star:1,feed:0,atk:Math.max(1,Math.round(t.atk*bonus)),hp:Math.max(1,Math.round(t.hp*(.95+Math.random()*.15))),spd:+(t.spd*(.96+Math.random()*.12)).toFixed(2),crit:t.crit+Math.random()*.04,imprint:im,evo:null}}
function recruit(k){const u=createUnit(k);if(st.units.length<MAX_UNITS){st.units.push(u);st.toast=`招募 ${u.name} · 印记「${u.imprint}」`;return}let target=st.units.find(x=>x.type===k)||st.units.slice().sort((a,b)=>a.star-b.star)[0];target.atk+=Math.max(1,Math.floor(u.atk*.25));target.hp+=Math.max(1,Math.floor(u.hp*.12));target.feed++;recalcStar(target);st.toast=`阵容已满：${u.name} 转化为 ${target.name} 的成长。`}
function recruitLegendary(){
 const existing=st.units.find(x=>x.type==='prism');
 if(existing){existing.atk+=8;existing.hp+=12;existing.feed+=2;recalcStar(existing);st.toast='虹晶共鸣再次触发：虹晶使徒获得额外成长。';return}
 const u=createUnit('prism');u.star=3;u.feed=5;u.name='虹晶使徒';u.atk=26;u.hp=52;u.spd=1.28;u.crit=.28;u.imprint='折光';
 if(st.units.length<MAX_UNITS)st.units.push(u);else{const target=st.units.slice().sort((a,b)=>a.star-b.star||a.atk-b.atk)[0];target.atk+=10;target.hp+=16;target.feed+=2;recalcStar(target)}
 st.legendary=true;
}
function recalcStar(u){const before=u.star;u.star=u.feed>=5?3:u.feed>=2?2:1;if(u.star>before){u.name=(u.star===3?'觉醒·':u.star===2?'进阶·':'')+TYPES[u.type].name}if(u.star===3&&!u.evo&&!st.evo&&EVOS[u.type]){st.evo={unitId:u.id,choices:EVOS[u.type]}}}
function merge(aid,bid){const ai=st.units.findIndex(x=>x.id===aid),bi=st.units.findIndex(x=>x.id===bid);if(ai<0||bi<0||ai===bi)return;const a=st.units[ai],b=st.units[bi],same=a.type===b.type;const bonus=own('fusion')?.18:0;b.atk+=Math.max(1,Math.floor(a.atk*((same?.56:.30)+bonus)));b.hp+=Math.max(1,Math.floor(a.hp*((same?.34:.18)+bonus*.65)));b.feed+=same?2:1;b.crit+=same?.015:.006;st.units.splice(ai,1);recalcStar(b);st.selected=null;st.toast=`${b.name} 吸收了 ${a.name}${same?'，同系融合获得额外成长。':'。'}`;render()}
function chooseEvo(id){const e=st.evo;if(!e)return;const u=st.units.find(x=>x.id===e.unitId),opt=e.choices.find(x=>x.id===id);if(!u||!opt)return;u.evo=opt.id;u.name=`${opt.name}·${TYPES[u.type].name}`;u.atk=Math.round(u.atk*opt.atk);u.hp=Math.round(u.hp*opt.hp);u.spd=+(u.spd*opt.spd).toFixed(2);u.crit+=opt.crit;st.evo=null;st.toast=`职业分支完成：${u.name}。`;render()}
function start(){st.screen='game';render()}
function clearSpin(){timers.spin.forEach(clearTimeout);timers.spin=[]}
function spin(){if(st.phase!=='prep'||st.gold<st.spinCost||st.spinning)return;if(st.gold<st.spinCost){st.toast='补给不足，建议直接迎战。';render();return}st.spinning=true;const cost=st.spinCost;st.gold-=cost;st.spinCount++;st.spinCost=5+st.spinCount*3;const force=st.calArmed;st.calArmed=false;if(force)st.cal--;st.lines=[];st.hitCells=[];st.jack=false;const cols=[0,1,2];for(let c=0;c<3;c++)for(let r=0;r<3;r++)st.board[r*3+c]=weightedKey();render();const machine=$('.lever');if(machine)machine.classList.add('pulled');let frames=0;const interval=setInterval(()=>{frames++;for(let i=0;i<9;i++)st.board[i]=weightedKey();updateReels(true,[]);if(frames>=5){clearInterval(interval);const final=makeBoard(force);const stops=[420,610,800];const temp=st.board.slice();cols.forEach((c,idx)=>{timers.spin.push(setTimeout(()=>{for(let r=0;r<3;r++)temp[r*3+c]=final[r*3+c];st.board=temp.slice();updateReels(idx<2,[]);if(idx===2){timers.spin=[];resolveSpin(cost);const lever=$('.lever');if(lever)lever.classList.remove('pulled')}},stops[idx]))})}},75)}
