function resolveSpin(cost){st.spinning=false;const res=analyze(st.board);st.lines=res.lines;st.hitCells=res.cells;if(!res.lines.length){st.blankStreak++;let refund=0;if(own('echo'))refund=3+(st.blankStreak>=2?1:0);st.gold+=refund;st.toast=refund?`空转。回声引擎返还 ${refund} 补给。`:`空转，消耗 ${cost} 补给。下一转成本更高。`}else{st.blankStreak=0;for(const l of res.lines){recruit(l.key);if(own('surge')&&chance(.20))recruit(l.key)}st.jack=res.lines.length>=2;if(res.lines.length>=3){recruitLegendary();st.toast=`PRISM JACKPOT！${res.lines.length} 条线同时命中，虹晶使徒降临。`;}else{st.toast=res.lines.length>=2?`JACKPOT！同时命中 ${res.lines.length} 条线。`:`共鸣成功：${res.lines[0].name} · ${TYPES[res.lines[0].key].name}`;}}render();if(st.jack)setTimeout(()=>{st.jack=false;render()},900)}
function arm(){if(st.phase!=='prep'||st.cal<=0||st.calArmed)return;st.calArmed=true;st.toast='校准器已装载：下一转保证至少一条共鸣线。';render()}
function openReward(){const pool=REWARDS.filter(x=>!own(x.id)).sort(()=>Math.random()-.5);st.rewardChoices=pool.slice(0,3);st.screen='reward';render()}
function enemyPool(w){if(w===12)return['boss','seer','brute'];if(w===6)return['brute','seer','spitter','brute'];const n=Math.min(5,2+Math.floor((w+1)/2));const pool=w%4===0?['brute','spitter','seer']:['crawler','crawler','spitter','brute'];return Array.from({length:n},()=>pick(pool))}
function mkEnemy(k,i){const t=ETYPE[k],w=st.wave,s=1+(w-1)*.13+(k==='boss'?.5:0);return{id:`e${w}${i}${Math.random()}`,type:k,name:t.name,maxHp:Math.round(t.hp*s),hp:Math.round(t.hp*s),atk:Math.round(t.atk*(1+(w-1)*.1+(k==='boss'?.35:0))),spd:t.spd,cd:Math.random()*.65,shield:0,dead:false}}
function mkAlly(u,i){let atk=u.atk*(1+(u.star-1)*.34),hp=u.hp*(1+(u.star-1)*.38),spd=u.spd,crit=u.crit;if(own('overclock')){atk*=1.16;spd*=1.06}if(own('bulwark'))hp*=1.22;if(u.type==='guard'&&own('bulwark'))hp*=1.10;return{...u,idx:i,maxHp:Math.round(hp),hp:Math.round(hp),atk:+atk.toFixed(1),spd:+spd.toFixed(2),crit,cd:Math.random()*.6,shield:0,dead:false}}
function battle(){if(st.phase!=='prep')return;if(!st.units.length){st.toast='至少需要 1 名单位。';render();return}st.phase='battle';st.battle={allies:st.units.map(mkAlly),enemies:enemyPool(st.wave).map(mkEnemy),msg:`第 ${st.wave} 波开始`};render();timers.battle=setInterval(tick,230)}
function alive(a){return a.filter(x=>x.hp>0)}
function targetEnemy(){return alive(st.battle.enemies)[0]||null}
function targetAlly(){const g=alive(st.battle.allies).filter(x=>x.type==='guard');return g[0]||alive(st.battle.allies)[0]||null}
function lowestAlly(){return alive(st.battle.allies).sort((a,b)=>(a.hp/a.maxHp)-(b.hp/b.maxHp))[0]||null}
function dmg(t,n){if(!t)return 0;let v=n;if(t.shield>0){const b=Math.min(t.shield,v);t.shield-=b;v-=b}v=Math.max(0,Math.round(v));t.hp=Math.max(0,t.hp-v);if(t.hp<=0)t.dead=true;return v}
function heal(t,n){if(!t)return 0;const old=t.hp;t.hp=Math.min(t.maxHp,t.hp+Math.round(n));return t.hp-old}
function tick(){if(!st.battle)return;const b=st.battle;const mult=st.battleSpeed||1;for(const a of b.allies)if(a.hp>0)a.cd-=.23*a.spd*mult;for(const e of b.enemies)if(e.hp>0)e.cd-=.23*e.spd*mult;
 for(const a of b.allies){if(a.hp<=0||a.cd>0)continue;a.cd=.82+Math.random()*.38;allyAct(a);if(checkEnd())return}
 for(const e of b.enemies){if(e.hp<=0||e.cd>0)continue;e.cd=.9+Math.random()*.4;enemyAct(e);if(checkEnd())return}
 updateStage();updateHUD()}
function allyAct(a){const b=st.battle;if(a.type==='medic'){const t=lowestAlly();if(t&&t.hp/t.maxHp<.86){let amount=a.atk*(own('clinic')?1.72:1.28);if(a.imprint==='祝佑')amount*=1.18;const h=heal(t,amount);if(own('clinic')&&t.hp===t.maxHp)t.shield+=Math.round(amount*.28);b.msg=`${a.name} 治疗 ${t.name} +${h}`;fx(a,t,'heal',h,true);return}}
 const t=targetEnemy();if(!t)return;let n=a.atk;const crit=chance(a.crit);if(crit)n*=1.72;if(a.type==='ranger'&&own('hunt')){if(t.hp/t.maxHp<.35)n*=1.28}const d=dmg(t,n);if(a.type==='mage'&&own('arcane')){const t2=alive(b.enemies)[1];if(t2)dmg(t2,d*.46)}if(a.type==='rogue'&&own('shadow')&&crit&&chance(.7)){const t2=targetEnemy();if(t2)dmg(t2,d*.55)}b.msg=`${a.name} → ${t.name} ${d}${crit?' CRIT':''}`;fx(a,t,a.type==='mage'?'magic':'shot',d,false);if(a.type==='ranger'&&own('hunt')&&t.hp<=0){const t2=targetEnemy();if(t2)dmg(t2,d*.42)} }
