function enemyAct(e){const b=st.battle;if(e.type==='seer'&&chance(.38)){const t=alive(b.enemies).sort((a,c)=>(a.hp/a.maxHp)-(c.hp/c.maxHp))[0];if(t){const h=heal(t,e.atk*.82);b.msg=`${e.name} 治疗同伴 +${h}`;return}}const t=targetAlly();if(!t)return;const d=dmg(t,e.atk);if(t.type==='guard'&&own('thorns'))dmg(e,d*.24);b.msg=`${e.name} → ${t.name} ${d}`;fx(e,t,'enemy',d,false)}
function fx(src,tgt,kind,num,good){try{window.dispatchEvent(new CustomEvent("rwfx",{detail:{src:src.id,tgt:tgt.id,kind:kind,good:!!good}}))}catch(e){}const stage=$('.stage');if(!stage)return;const sEl=$(`[data-cid="${src.id}"]`),tEl=$(`[data-cid="${tgt.id}"]`);if(!sEl||!tEl)return;const sr=sEl.getBoundingClientRect(),tr=tEl.getBoundingClientRect(),rr=stage.getBoundingClientRect();const x1=sr.left-rr.left+sr.width/2,y1=sr.top-rr.top+28,x2=tr.left-rr.left+tr.width/2,y2=tr.top-rr.top+28;const p=document.createElement('i');p.className=`projectile ${kind==='magic'?'magic':kind==='heal'?'heal':''}`;p.style.left=`${x1}px`;p.style.top=`${y1}px`;stage.appendChild(p);requestAnimationFrame(()=>{p.style.transform=`translate(${x2-x1}px,${y2-y1}px)`;p.style.opacity='.2'});setTimeout(()=>p.remove(),310);setTimeout(()=>{const f=document.createElement('b');f.className=`floatnum ${good?'good':'bad'}`;f.textContent=good?`+${Math.round(num)}`:`-${Math.round(num)}`;f.style.left=`${x2-8}px`;f.style.top=`${y2-10}px`;stage.appendChild(f);setTimeout(()=>f.remove(),680)},240)}
function checkEnd(){const b=st.battle;if(alive(b.enemies).length&&alive(b.allies).length)return false;clearInterval(timers.battle);timers.battle=null;if(!alive(b.enemies).length){const g=10+st.wave*2+(own('salvage')?5:0)+(st.wave===12&&own('salvage')?8:0);st.gold+=g;st.score+=120+st.wave*42+alive(b.allies).length*15;const doneWave=st.wave;if(st.wave>=MAX_WAVE){st.high=Math.max(st.high,st.score);saveHigh();st.screen='over';st.runDone=true;st.phase='over';render();return true}st.wave++;st.phase='prep';st.battle=null;st.spinCount=0;st.spinCost=5;st.lines=[];st.hitCells=[];st.toast=`第 ${doneWave} 波胜利，+${g} 补给。`;if(doneWave%2===0){openReward();return true}else render()}else{const rem=alive(b.enemies).length,loss=Math.min(9,Math.max(2,rem*2+(st.wave>=10?2:0)));st.base=Math.max(0,st.base-loss);if(st.base<=0){st.high=Math.max(st.high,st.score);saveHigh();st.screen='over';st.runDone=true;st.phase='over';render();return true}const done=st.wave;st.wave++;st.phase='prep';st.battle=null;st.spinCount=0;st.spinCost=5;st.lines=[];st.hitCells=[];st.toast=`第 ${done} 波失守，基地 -${loss}。下一波前优先融合。`;render()}return true}
function selectUnit(id){if(st.phase!=='prep')return;if(!st.selected){st.selected=id;const u=st.units.find(x=>x.id===id);st.toast=`已选素材 ${u.name}，再点另一单位即可吸收。`;render();return}if(st.selected===id){st.selected=null;st.toast='已取消融合选择。';render();return}merge(st.selected,id)}
function rewardScore(r){const counts=Object.fromEntries(TYPE_KEYS.map(k=>[k,st.units.filter(u=>u.type===k).length]));let n=0;if(r.id==='hunt')n+=counts.ranger*3;if(r.id==='arcane')n+=counts.mage*3;if(r.id==='clinic')n+=counts.medic*3;if(r.id==='thorns')n+=counts.guard*3;if(r.id==='shadow')n+=counts.rogue*3;if(['fusion','overclock','bulwark'].includes(r.id))n+=st.units.length;if(['loaded','echo','surge'].includes(r.id))n+=Math.max(0,3-st.rewards.length);return n}
function chooseReward(id){const r=REWARDS.find(x=>x.id===id);if(!r)return;st.rewards.push(r);st.screen='game';st.toast=`获得「${r.name}」`;render()}
function restart(){clearSpin();if(timers.battle)clearInterval(timers.battle);st=fresh();st.screen='game';render()}
function colorAlpha(hex,a){const v=parseInt(hex.slice(1),16),r=v>>16,g=v>>8&255,b=v&255;return`rgba(${r},${g},${b},${a})`}
function cellHTML(k,i,spinning=false){const t=TYPES[k];return`<div class="cell ${st.hitCells.includes(i)?'hit':''} ${spinning?'spinning':''}" style="background:linear-gradient(180deg,${colorAlpha(t.color,.16)},#0f151e)"><div class="sym"><div class="sigil">${sigil(k)}</div><small>${t.name}</small><div class="rare">${k.toUpperCase()}</div></div></div>`}
function updateReels(spinning=false){const grid=$('.reels');if(!grid)return;let html='';for(let c=0;c<3;c++){html+='<div class="reelcol">';for(let r=0;r<3;r++){const i=r*3+c;html+=cellHTML(st.board[i],i,spinning)}html+='</div>'}grid.innerHTML=html}
