function updateHUD(){const hp=$('[data-hud=hp]'),gold=$('[data-hud=gold]');if(hp)hp.textContent=st.base;if(gold)gold.textContent=st.gold}
function spriteHTML(x,isEnemy=false){const cls=isEnemy?`enemy ${x.type}`:x.type;return`<div class="sprite ${cls}"><i class="head"></i><i class="body"></i><i class="leg a"></i><i class="leg b"></i><i class="weapon"></i></div>`}
function stagePos(i,count,enemy){const row=Math.floor(i/2),col=i%2;const ys=[86,128,170];const x=enemy?(col?69:83):(col?31:17);return{x,y:ys[row]||170}}
function combatantHTML(x,i,count,enemy=false){const p=stagePos(i,count,enemy),hp=Math.max(0,x.hp/x.maxHp*100);return`<div class="combatant ${enemy?'enemy-side':''} ${x.dead?'dead':''}" data-cid="${x.id}" style="left:${p.x}%;top:${p.y-48}px"><span class="star">${enemy?'':`${x.star}★`}</span>${x.shield>0?'<span class="mini-shield">◆</span>':''}${spriteHTML(x,enemy)}<div class="unit-name">${x.name}</div><div class="mini-hp"><i style="width:${hp}%"></i></div></div>`}
function previewEnemy(){return enemyPool(st.wave).slice(0,5).map(k=>`<span class="enemy-icon">${ETYPE[k].icon}</span>`).join('')}
function updateStage(){const box=$('.combat-layer');if(!box||!st.battle)return;box.innerHTML=st.battle.allies.map((x,i)=>combatantHTML(x,i,st.battle.allies.length,false)).join('')+st.battle.enemies.map((x,i)=>combatantHTML(x,i,st.battle.enemies.length,true)).join('');const msg=$('.stage-msg');if(msg)msg.textContent=st.battle.msg}
function renderStage(){const boss=st.wave===12||st.wave===6;let layer='';if(st.phase==='battle'&&st.battle)layer=st.battle.allies.map((x,i)=>combatantHTML(x,i,st.battle.allies.length,false)).join('')+st.battle.enemies.map((x,i)=>combatantHTML(x,i,st.battle.enemies.length,true)).join('');else layer=st.units.map((u,i)=>{const temp={...u,maxHp:u.hp,hp:u.hp,shield:0,dead:false};return combatantHTML(temp,i,st.units.length,false)}).join('');const threeReady=!!(window.RW3D&&window.RW3D.ready),threeOn=!!(threeReady&&window.RW3D.enabled);return`<section class="stage"><div class="moon"></div><div class="castle"></div><div class="portal"></div><div class="lane"></div><div class="three-layer" aria-hidden="true"></div><div class="stage-title"><span class="stage-pill ${boss?'boss':''}">${boss?'JUDGEMENT':'WAVE'} ${st.wave}</span></div><div class="stage-msg">${st.phase==='battle'&&st.battle?st.battle.msg:st.toast}</div><div class="combat-layer">${layer}</div><div class="stage-footer"><div class="forecast">${st.phase==='battle'?'':previewEnemy()}</div><div class="stage-actions"><button class="three-toggle ${threeOn?'active':''}" data-action="three" ${threeReady?'':'disabled'}>${threeReady?(threeOn?'3D ON':'2D'):'3D …'}</button><button class="speed-cta" data-action="speed" ${st.phase!=='battle'?'disabled':''}>${st.battleSpeed===2?'2×':'1×'}</button><button class="battle-cta" data-action="battle" ${st.phase!=='prep'||!st.units.length?'disabled':''}>${st.phase==='battle'?'战斗中':'迎战'}</button></div></div></section>`}
function paylineSVG(){return st.lines.length?`<svg class="paylines" viewBox="0 0 100 100" preserveAspectRatio="none">${st.lines.map(l=>`<polyline class="payline" points="${l.pts}"/>`).join('')}</svg>`:''}
function renderMachine(){let reels='';for(let c=0;c<3;c++){reels+='<div class="reelcol">';for(let r=0;r<3;r++){const i=r*3+c;reels+=cellHTML(st.board[i],i,false)}reels+='</div>'}return`<section class="machine"><div class="machine-head"><div class="machine-title"><b>命运转轮</b><span>3×3 · 8 PAYLINES</span></div><div class="machine-meta"><span class="odds">FATE ${Math.min(99,34+st.blankStreak*12+(own('loaded')?28:0))}%</span><span class="cost">NEXT ${st.spinCost}</span></div></div><div class="reels-wrap"><div class="reels">${reels}</div>${paylineSVG()}<div class="lever"><div class="lever-stick"><i class="lever-knob"></i></div></div>${st.jack?`<div class="jackpot ${st.lines.length>=3?'prism':''}"><div>${st.lines.length>=3?'PRISM JACKPOT':'JACKPOT'} ×${st.lines.length}</div></div>`:''}</div><div class="match-row">${st.lines.length?st.lines.map(l=>`<span class="match-chip">${l.name} · ${TYPES[l.key].name}</span>`).join(''):`<span class="match-chip dim">命中三枚相同符号即可招募</span>`}</div><div class="machine-actions"><button class="btn utility ${st.calArmed?'armed':''}" data-action="arm" ${st.cal<=0||st.calArmed||st.phase!=='prep'?'disabled':''}>${st.calArmed?'校准已装载':`校准器 ×${st.cal}`}</button><button class="btn spin" data-action="spin" ${st.phase!=='prep'||st.gold<st.spinCost?'disabled':''}>拉杆 · ${st.spinCost} 补给</button></div></section>`}
