import type {Store} from '../state/types';
/** Quiet, locally synthesized hotel sounds; opt-in, no downloads or autoplay. */
export function mountHotelAudio(root:HTMLElement,store:Store){const button=document.createElement('button');button.className='sound-toggle';button.textContent='♪';button.title='开启酒店环境声';button.setAttribute('aria-label','开启酒店环境声');button.setAttribute('aria-pressed','false');root.querySelector('.property-row')?.append(button);
 let ctx:AudioContext|undefined,enabled=false,last=0,arrivals=store.getState().game?.arrivals??0,cash=store.getState().metrics.cash,noise:AudioBufferSourceNode|undefined,rain:GainNode|undefined;
 const tone=(frequency:number,duration=.13,delay=0)=>{if(!ctx||!enabled)return;const o=ctx.createOscillator(),gain=ctx.createGain(),at=ctx.currentTime+delay;o.frequency.value=frequency;gain.gain.setValueAtTime(.016,at);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);o.connect(gain);gain.connect(ctx.destination);o.start(at);o.stop(at+duration);o.onended=()=>{o.disconnect();gain.disconnect();};};
 button.onclick=async()=>{enabled=!enabled;if(enabled){ctx??=new AudioContext();await ctx.resume();if(!noise){const buffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()-.5)*.08;noise=ctx.createBufferSource();noise.buffer=buffer;noise.loop=true;rain=ctx.createGain();rain.gain.value=.01;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=700;noise.connect(filter);filter.connect(rain);rain.connect(ctx.destination);noise.start();}tone(660,.25);tone(880,.25,.12);}else await ctx?.suspend();button.setAttribute('aria-pressed',String(enabled));button.title=enabled?'关闭酒店环境声':'开启酒店环境声';button.setAttribute('aria-label',button.title);};
 const unsub=store.subscribe(s=>{const now=Date.now();if(ctx&&rain)rain.gain.setTargetAtTime(s.game?.weather==='rain'?.12:.015,ctx.currentTime,.5);if(enabled&&!document.hidden&&now-last>1800){if((s.game?.arrivals??0)>arrivals){tone(660,.25);tone(880,.3,.12);last=now;}else if(s.metrics.cash>cash){tone(1046,.1);last=now;}}arrivals=s.game?.arrivals??0;cash=s.metrics.cash;});
 const visibility=()=>{if(document.hidden)void ctx?.suspend();else if(enabled)void ctx?.resume();};document.addEventListener('visibilitychange',visibility);window.addEventListener('pagehide',()=>{unsub();void ctx?.close();},{once:true});
}
