import * as T from 'three';
import {materials as m} from './materials';
export const geometries={box:new T.BoxGeometry(1,1,1),cylinder:new T.CylinderGeometry(1,1,1,12),sphere:new T.SphereGeometry(1,12,8),leaf:new T.SphereGeometry(1,8,6),cone:new T.ConeGeometry(1,1,16),plane:new T.PlaneGeometry(1,1)};
export function box(g:T.Object3D,x:number,y:number,z:number,w:number,h:number,d:number,mat:T.Material=m.wood){const mesh=new T.Mesh(geometries.box,mat);mesh.position.set(x,y,z);mesh.scale.set(w,h,d);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh;}
export function cyl(g:T.Object3D,x:number,y:number,z:number,r:number,h:number,mat:T.Material=m.gold){const mesh=new T.Mesh(geometries.cylinder,mat);mesh.position.set(x,y,z);mesh.scale.set(r,h,r);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh;}
export function orb(g:T.Object3D,x:number,y:number,z:number,rx:number,ry:number,rz:number,mat:T.Material=m.leaf){const mesh=new T.Mesh(geometries.sphere,mat);mesh.position.set(x,y,z);mesh.scale.set(rx,ry,rz);mesh.castShadow=true;g.add(mesh);return mesh;}
export function shadow(g:T.Object3D,x:number,z:number,w:number,d:number,y=.022){const mesh=new T.Mesh(geometries.plane,m.ao);mesh.rotation.x=-Math.PI/2;mesh.position.set(x,y,z);mesh.scale.set(w,d,1);g.add(mesh);}
export function plant(g:T.Object3D,x:number,z:number,scale=1,y=0){const p=new T.Group();p.position.set(x,y,z);p.scale.setScalar(scale);g.add(p);cyl(p,0,.21,0,.21,.42,m.stone);cyl(p,0,.76,0,.027,1.1,m.walnut);for(let i=0;i<9;i++){const a=i*2.4,h=.65+i*.073;const l=orb(p,Math.sin(a)*.2,h,Math.cos(a)*.17,.24,.095,.12,i%2?m.leaf:m.green);l.rotation.set(.3,a,Math.sin(a)*.65);}shadow(p,0,0,.7,.55);return p;}
export function lamp(g:T.Object3D,x:number,y:number,z:number,scale=1){const p=new T.Group();p.position.set(x,y,z);p.scale.setScalar(scale);g.add(p);cyl(p,0,.035,0,.11,.045,m.gold);cyl(p,0,.21,0,.019,.36,m.gold);cyl(p,0,.42,0,.16,.22,m.shade);cyl(p,0,.315,0,.135,.015,m.glow);return p;}
export function chair(g:T.Object3D,x:number,z:number,rot=0,mat:T.Material=m.teal){const p=new T.Group();p.position.set(x,0,z);p.rotation.y=rot;g.add(p);box(p,0,.43,0,.55,.14,.56,mat);box(p,0,.71,-.23,.55,.48,.1,mat);for(const sx of [-1,1])for(const sz of [-1,1])cyl(p,sx*.2,.2,sz*.2,.025,.4,m.walnut);return p;}
export function sofa(g:T.Object3D,x:number,z:number,rot=0,width=1.5,mat:T.Material=m.teal){const p=new T.Group();p.position.set(x,0,z);p.rotation.y=rot;g.add(p);box(p,0,.32,0,width,.42,.64,mat);box(p,0,.66,-.29,width,.65,.18,mat);for(const s of [-1,1]){box(p,s*(width/2-.08),.56,0,.16,.4,.7,mat);box(p,s*width*.23,.55,-.17,.35,.28,.11,m.white);}
 box(p,0,.58,.04,width-.3,.11,.44,mat);shadow(p,0,0,width+.15,.95);return p;}
export function table(g:T.Object3D,x:number,z:number,r=.42){cyl(g,x,.37,z,.055,.74,m.gold);cyl(g,x,.75,z,r,.07,m.stone);cyl(g,x,.04,z,r*.5,.06,m.walnut);}
export function cups(g:T.Object3D,x:number,y:number,z:number){cyl(g,x,y,z,.07,.13,m.white);cyl(g,x,y-.065,z,.12,.018,m.white);}
export function artwork(g:T.Object3D,x:number,y:number,z:number,w=1.15,h=.65,variant=0){box(g,x,y,z,w+.07,h+.07,.06,m.gold);box(g,x,y,z+.04,w,h,.015,m.white);box(g,x,y-h*.14,z+.06,w*.93,h*.37,.012,variant%2?m.teal:m.window);box(g,x-w*.2,y+h*.02,z+.07,w*.27,h*.25,.014,m.stone);orb(g,x+w*.25,y+h*.19,z+.075,h*.13,h*.13,.006,m.rust);}
/** Static geometry is merged into instanced batches while entity groups retain colliders / anchors. */
export function batchStatic(root:T.Group){root.updateMatrixWorld(true);const buckets=new Map<string,{geometry:T.BufferGeometry;material:T.Material;matrices:T.Matrix4[];meshes:T.Mesh[]}>();root.traverse(o=>{if(!(o instanceof T.Mesh)||o.userData.interactive||Array.isArray(o.material)||o.material.transparent)return;const key=o.geometry.uuid+o.material.uuid;let b=buckets.get(key);if(!b){b={geometry:o.geometry,material:o.material,matrices:[],meshes:[]};buckets.set(key,b);}b.matrices.push(o.matrixWorld.clone());b.meshes.push(o);});for(const b of buckets.values()){const mesh=new T.InstancedMesh(b.geometry,b.material,b.matrices.length);b.matrices.forEach((matrix,i)=>mesh.setMatrixAt(i,matrix));mesh.castShadow=true;mesh.receiveShadow=true;mesh.instanceMatrix.needsUpdate=true;mesh.computeBoundingSphere();b.meshes.forEach(m=>m.removeFromParent());root.add(mesh);}}
