from pathlib import Path
p=Path('games/jinwan-youtao/index.html')
text=p.read_text(encoding='utf-8')

def r(old,new,label):
    global text
    if old not in text:
        raise SystemExit('missing '+label)
    text=text.replace(old,new,1)

text=text.replace('<title>今晚有套吗？ v5.2</title>','<title>今晚有套吗？ v5.3</title>',1)
text=text.replace('GM Dashboard · v5.1','GM Dashboard · v5.3',1)
text=text.replace("$('victorySummary').textContent='GM 终局进度 '+victoryCount()+'/5。v5.2：放慢前期节奏、修复日志关闭、重做高清 3D 场景与可行动结算复盘。';","$('victorySummary').textContent='GM 终局进度 '+victoryCount()+'/5。v5.3：新开档入口、稳定 3D、差异化事件 Playbook 与实质部门授权。';",1)
r('.stage.mode3d .scene3d{opacity:1;transform:scale(1)}','.stage.mode3d .scene3d{opacity:1;transform:scale(1)}.scene3d>svg{display:block;width:100%;height:100%}','scene css')
r('.rolechip{display:inline-block;padding:2px 6px;border-radius:999px;background:#e7dfd4;color:#5d554e;font-size:8px;font-weight:950;white-space:nowrap}', '.rolechip{display:inline-block;padding:2px 6px;border-radius:999px;background:#e7dfd4;color:#5d554e;font-size:8px;font-weight:950;white-space:nowrap}.newgamechip{margin-left:5px;border:1px solid var(--line);background:#fff;border-radius:999px;padding:2px 6px;color:#8b4b42;font-size:7.7px;font-weight:950;white-space:nowrap}.visual3d .newgamechip{background:#24333e;border-color:#465563;color:#e6c2bb}','new game css')
r('.managercard.hired{border-color:#a8bdab;background:#f7fbf7}', '.managercard.hired{border-color:#a8bdab;background:#f7fbf7}.manager-impact{display:block;margin-top:5px;font-size:7.6px;font-weight:850;color:#5f7563}.visual3d .manager-impact{color:#9fc2a8}','manager css')
r('<span class="rolechip" id="roleLabel">Duty Manager</span><span class="secondary-meta"> · 房晚 <b id="nights">0</b></span>','<span class="rolechip" id="roleLabel">Duty Manager</span><button class="newgamechip" id="newGameBtn" type="button">🆕 新档</button><span class="secondary-meta"> · 房晚 <b id="nights">0</b></span>','new game ui')
r('eventLog:[],lastMaintenanceDay:0,streak:0','eventLog:[],lastMaintenanceDay:0,recentVipKeys:[],departmentImpact:{},streak:0','state extras')
r("if(!state.eventLog)state.eventLog=[];if(typeof state.lastMaintenanceDay!=='number')state.lastMaintenanceDay=0;if(!state.stats)state.stats={};","if(!state.eventLog)state.eventLog=[];if(typeof state.lastMaintenanceDay!=='number')state.lastMaintenanceDay=0;if(!state.recentVipKeys)state.recentVipKeys=[];if(!state.departmentImpact)state.departmentImpact={};if(!state.stats)state.stats={};",'ensure extras')
r("function sceneData(key){return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(sceneSvg(key))}\nvar sceneAssets={place:sceneData('place'),regency:sceneData('regency'),grand:sceneData('grand'),andaz:sceneData('andaz'),alila:sceneData('alila'),park:sceneData('park')};","function sceneData(key){return sceneSvg(key)}\nvar sceneAssets={place:sceneData('place'),regency:sceneData('regency'),grand:sceneData('grand'),andaz:sceneData('andaz'),alila:sceneData('alila'),park:sceneData('park')};",'scene data')
r("if(scene.getAttribute('data-brand')!==b){scene.style.backgroundImage='url('+sceneAssets[b]+')';scene.setAttribute('data-brand',b)}","if(scene.getAttribute('data-brand')!==b||!scene.firstElementChild){scene.style.backgroundImage='none';scene.innerHTML=sceneAssets[b]||sceneAssets.place;scene.setAttribute('data-brand',b)}",'scene render')
r("function managerHired(k){return !!(state.managers&&state.managers[k])}\nfunction hiredManagerCount()","function managerHired(k){return !!(state.managers&&state.managers[k])}\nfunction noteDepartment(k,n){ensureDaily();if(!state.departmentImpact)state.departmentImpact={};state.departmentImpact[k]=(state.departmentImpact[k]||0)+(n||1)}\nfunction departmentImpactText(k){var n=(state.departmentImpact&&state.departmentImpact[k])||0;if(k==='front')return '已接管 '+n+' 次前台判断';if(k==='house')return '已抢救 / 翻房 '+n+' 次';if(k==='revenue')return '已执行 '+n+' 次收益策略';if(k==='fb')return '已自动补货 '+n+' 次';if(k==='chef')return '已缓冲 '+n+' 次餐饮高峰';if(k==='events')return '已接管 '+n+' 次团体 / 宴会';if(k==='engineering')return '已修复 '+n+' 次设施故障';if(k==='wellness')return '已接管 '+n+' 次 Spa / 康体高峰';return '已接管 '+n+' 次'}\nfunction hiredManagerCount()",'dept helpers')
old="html+='<button class=\"'+cls+'\" data-manager=\"'+k+'\" '+(!u||h?'disabled':'')+'><strong>'+d.icon+' '+d.name+'</strong><small><span class=\"manager-name\">'+(h?d.person:'职位空缺')+'</span> · '+d.desc+'</small><span class=\"tag '+(h?'green':u?'gold':'')+'\">'+status+'</span></button>'"
new="html+='<button class=\"'+cls+'\" data-manager=\"'+k+'\" '+(!u||h?'disabled':'')+'><strong>'+d.icon+' '+d.name+'</strong><small><span class=\"manager-name\">'+(h?d.person:'职位空缺')+'</span> · '+d.desc+'</small>'+(h?'<span class=\"manager-impact\">'+departmentImpactText(k)+'</span>':'')+'<span class=\"tag '+(h?'green':u?'gold':'')+'\">'+status+'</span></button>'"
r(old,new,'manager card')
for a,b,label in [
("function autoFrontArrival(gu){","function autoFrontArrival(gu){noteDepartment('front');",'front1'),
("function autoFrontLate(gu){","function autoFrontLate(gu){noteDepartment('front');",'front2'),
("function applyRevenueAutomation(){if(!managerHired('revenue'))return;","function applyRevenueAutomation(){if(!managerHired('revenue'))return;noteDepartment('revenue');",'rev'),
("state.breakfastStock=100;recordAuto('F&B Director 自动补早餐')","state.breakfastStock=100;noteDepartment('fb');recordAuto('F&B Director 自动补早餐')",'fb1'),
("state.loungeStock=100;recordAuto('F&B Director 自动补 Lounge')","state.loungeStock=100;noteDepartment('fb');recordAuto('F&B Director 自动补 Lounge')",'fb2'),
("if(active[i].cleaning<=0){active[i].dirty=false;active[i].cleaning=0;if(!managerHired('house')||Math.random()<.18)showToast","if(active[i].cleaning<=0){active[i].dirty=false;active[i].cleaning=0;if(managerHired('house'))noteDepartment('house');if(!managerHired('house')||Math.random()<.18)showToast",'house'),
("var min=state.minute,p=personaOf(gu),diff=themedDifficulty(),fbLoad=diff.fb*(managerHired('chef') ? .78 : 1);","var min=state.minute,p=personaOf(gu),diff=themedDifficulty(),fbLoad=diff.fb*(managerHired('chef') ? .78 : 1);if(managerHired('chef')&&!gu.chefCounted){gu.chefCounted=true;noteDepartment('chef')}",'chef'),
("recordAuto('Engineering 在客人发现前修好了 OOO · -¥90')","noteDepartment('engineering');recordAuto('Engineering 在客人发现前修好了 OOO · -¥90')",'eng'),
("if(managerHired('events'))recordAuto('Events Manager 接管会议团 · +¥'+er);","if(managerHired('events')){noteDepartment('events');recordAuto('Events Manager 接管会议团 · +¥'+er);}",'events'),
("if(managerHired('wellness'))state.rep=Math.min(100,state.rep+1);showToast('🌧️ 下雨了。Spa '","if(managerHired('wellness')){state.rep=Math.min(100,state.rep+1);noteDepartment('wellness')}showToast('🌧️ 下雨了。Spa '",'wellness')]: r(a,b,label)

start=text.index('function executiveVipPool()')
end=text.index('function leadershipBriefLines()')
text=text[:start]+r'''function executiveVipPool(){var p=['chairman'];if(careerLevel()>=3)p.push('owner');if(state.brand==='andaz'||state.brand==='park')p.push('celebrity');if(state.brand==='regency'||state.brand==='grand'||state.brand==='park')p.push('delegation');if(state.brand==='park')p.push('auditor','owner');return p}
function pickExecutiveVipKey(){var pool=executiveVipPool(),recent=(state.recentVipKeys||[]).slice(-2),fresh=pool.filter(function(k){return recent.indexOf(k)<0});if(fresh.length)pool=fresh;return pool[Math.floor(Math.random()*pool.length)]}
function departmentLeadLabel(k,item){var key=item.key,map={maintenance:{engineering:'Engineering 快修隔离',house:'Housekeeping 腾挪可售房'},group:{events:'Events 分波到店',fb:'F&B 先开餐分流',front:'Front Office 团队专线'},chairman:{revenue:'Revenue 锁住最后一套',front:'Front Office 私密预排房',house:'Housekeeping 抢房'},owner:{front:'Front Office 私密接待',house:'Housekeeping Owner Room Check',fb:'F&B 定制晚餐'},auditor:{house:'Housekeeping 全房巡检',engineering:'Engineering 预防性巡检',front:'Front Office SOP 演练'},celebrity:{front:'Front Office 无痕入住',events:'Events 清空动线',house:'Housekeeping 隐私楼层'},delegation:{events:'Events Command Center',fb:'F&B 闭门餐叙',engineering:'Engineering 备援保障',front:'Front Office 分组入住'}};return(map[key]&&map[key][k])||(departmentDefs[k].name+' Lead')}
function departmentLeadSub(k,item){var key=item.key,map={maintenance:{engineering:'先隔离故障点并抢修，直接决定这间房今晚还能不能卖。',house:'把 Stayover / Clean Room 重新排优先级，先救一间今晚可售房。'},group:{events:'把几十人拆成几波到店，会议团不再一次性淹没 Lobby。',fb:'让团体先去餐饮 / Lounge，给前台换出处理时间。',front:'单开团体柜台，降低普通散客一起排队的连锁反应。'},chairman:{revenue:'保护最后一间套房，牺牲部分当晚可卖高价机会。',front:'先做房型、欢迎礼与电梯动线，减少到店临时政治。',house:'跳过普通翻房顺序，先把 Chairman 房做出来。'},owner:{front:'不在大堂讨论身份与房型，直接转私密动线。',house:'把 Owner Room 当作今天最高优先级做最终检查。',fb:'用定制餐饮把硬件短板变成体验补偿。'},auditor:{house:'先把最容易被审计抓住的客房细节一次性扫掉。',engineering:'把 OOO、异味、空调与照明隐患提前关掉。',front:'先统一所有前台口径，避免一问三不知。'},celebrity:{front:'绕开大堂主流线，降低围观与信息泄漏。',events:'把 KOL / 团体活动从同一动线上挪开。',house:'封住一段楼层，减少敲错门与隐私事故。'},delegation:{events:'把房间、会议、车辆与安保放进同一个 run sheet。',fb:'把早餐和闭门餐叙变成独立时段，不和普通客抢资源。',engineering:'提前做供电、空调、电梯和会议设备备援。',front:'拆分名单，先发房卡后核证件，减少大堂堵塞。'}};return(map[key]&&map[key][k])||'让这个部门真正承担事件主责，而不是只贡献一个覆盖数字。'}
function resolveDepartmentLead(item,k){var v=vipDefs[item.key],req=executiveRequirements(item.key),sreq=vipSpaceRequirements(item.key),cover=departmentCoverage(req),scover=vipSpaceCoverage(item.key),support=cover+scover,relevant=req.indexOf(k)>=0,cost={front:140,house:130,revenue:90,fb:180,chef:150,events:170,engineering:160,wellness:180}[k]||150,need=Math.max(2,req.length+sreq.length-(item.level>=4?1:2)),success=relevant&&managerHired(k)&&support>=need;if(state.cash<cost){state.stats.vipFailed++;state.owner=Math.max(0,state.owner-1);showToast('⚠️ '+departmentDefs[k].name+' 想接，但现场预算不够。');return}state.cash-=cost;state.stats.totalExpense+=cost;noteDepartment(k);if(k==='engineering'||k==='house'){var rr=state.rooms.filter(function(r){return r.dirty&&!r.occupied})[0];if(rr){rr.dirty=false;rr.cleaning=0}}if(k==='fb'){state.breakfastStock=Math.min(100,state.breakfastStock+45);state.loungeStock=Math.min(100,state.loungeStock+45)}if(k==='revenue')recordRevenue(220+item.level*40);if(k==='events')recordRevenue(180+item.level*55);if(k==='wellness')recordRevenue(180+item.level*45);if(success){state.stats.vipResolved++;state.rep=Math.min(100,state.rep+2.5+item.level*.45);state.owner=Math.min(100,state.owner+1.5);recordRevenue(140+item.level*70);state.daily.highlight='✅ '+v.icon+' '+v.name+'：'+departmentLeadLabel(k,item)+' 接住了事件。';showToast(state.daily.highlight)}else{state.stats.vipFailed++;state.rep=Math.max(0,state.rep-(1.5+item.level*.55));state.owner=Math.max(0,state.owner-.5);state.daily.highlight='⚠️ '+v.icon+' '+v.name+'：'+departmentLeadLabel(k,item)+' 只解决了局部，支持部门 / 空间仍不够。';showToast(state.daily.highlight)}}
function queueExecutiveVip(key){var v=vipDefs[key],item={key:key,level:v.level,title:v.name},req=executiveRequirements(key),sreq=vipSpaceRequirements(key),cover=departmentCoverage(req),scover=vipSpaceCoverage(key);state.recentVipKeys=state.recentVipKeys||[];state.recentVipKeys.push(key);if(state.recentVipKeys.length>4)state.recentVipKeys.shift();if(v.level<=2&&cover===req.length&&scover===sreq.length){resolveExecutiveVip(item,'delegate');recordAuto(v.name+' 已由 '+req.map(function(k){return departmentDefs[k].name.replace(' Manager','')}).join(' + ')+' 自动结案');return}state.executiveQueue.push(item);state.stats.gmEscalations++;state.daily.escalated++;if(v.level>=4)state.stats.l4Escalations++;$('frontBtn').classList.add('alert');$('hint').style.display='block';$('hint').textContent=escalationName(v.level)+'：'+v.name+' 已升级到 GM Desk。';showToast(v.icon+' '+escalationName(v.level)+' · '+v.name+' 需要你')}
function maybeExecutiveVip(){if(state.scenario&&state.scenario.active)return;if(state.daily.vipEventDone||careerLevel()<2||state.minute<16*60||state.minute>21*60||state.paused)return;var chance=.00075*effectiveSpeed()*(careerLevel()-1);if(Math.random()>chance)return;state.daily.vipEventDone=true;queueExecutiveVip(pickExecutiveVipKey())}
function resolveExecutiveVip(item,mode){var v=vipDefs[item.key],req=executiveRequirements(item.key),cover=departmentCoverage(req),need=req.length,sreq=vipSpaceRequirements(item.key),scover=vipSpaceCoverage(item.key),sneed=sreq.length,missing=Math.max(0,sneed-scover),success=false,msg='',cost;if(mode==='command'){cost=420+item.level*90+missing*140;if(state.cash<cost){state.owner=Math.max(0,state.owner-2);state.stats.vipFailed++;msg='预算不够，全酒店想帮也帮不动。业主 -2'}else if(missing>=2){state.cash-=cost;state.stats.totalExpense+=cost;state.rep=Math.max(0,state.rep-2);state.stats.vipFailed++;msg='GM 可以催人，但不能现场变出两个缺失空间。硬拉通仍然翻车。'}else{state.cash-=cost;state.stats.totalExpense+=cost;state.rep=Math.min(100,state.rep+4+item.level);state.owner=Math.min(100,state.owner+1);state.stats.vipResolved++;recordRevenue(180+item.level*90);success=true;msg=missing?'GM 亲自补了最后一个空间短板，险过。':'GM 亲自拉通全部门，问题被完整解决。'}}else if(mode==='makeover'){cost=360+missing*240+item.level*40;if(state.cash<cost){state.owner=Math.max(0,state.owner-1);state.stats.vipFailed++;msg='临时改造预算没批下来。'}else{state.cash-=cost;state.stats.totalExpense+=cost;state.stats.emergencyMakeovers=(state.stats.emergencyMakeovers||0)+1;state.rep=Math.min(100,state.rep+3+item.level);state.owner=Math.min(100,state.owner+1);state.stats.vipResolved++;recordRevenue(150+item.level*80);success=true;msg='临时封层、布置、会客室转换和 Welcome Amenity 一起上，空间短板被临时补住。'}}else if(mode==='delegate'){var threshold=item.level>=4?need:Math.max(2,need-1),spaceThreshold=item.level>=4?sneed:Math.max(1,sneed-1);if(cover>=threshold&&scover>=spaceThreshold){state.rep=Math.min(100,state.rep+2+cover*.5);state.owner=Math.min(100,state.owner+2);state.stats.vipResolved++;recordRevenue(260+cover*110);success=true;msg='Leadership Team 和酒店硬件都接住了 VIP，GM 只需要签字。'}else{state.rep=Math.max(0,state.rep-(4+item.level));state.owner=Math.max(0,state.owner-2);state.stats.vipFailed++;msg=cover<threshold?'部门覆盖不足，SOP 在最需要它的时候失效了。':'空间没到位：团队很努力，但酒店物理条件不够。'}}else{recordRevenue(520+item.level*120);state.owner=Math.min(100,state.owner+3);state.rep=Math.max(0,state.rep-(3+item.level+missing));state.stats.vipFailed++;msg='Revenue 很漂亮，DP 也很精彩。'}if(item.key==='maintenance'&&success){state.rep=Math.min(100,state.rep+1);state.owner=Math.min(100,state.owner+1);recordRevenue(120);msg+=' 可售房被及时救回，还顺手挽回了今晚收入。'}state.daily.highlight=(success?'✅ ':'⚠️ ')+v.icon+' '+v.name+'：'+msg;showToast(state.daily.highlight)}
function showExecutiveDecision(item){var v=vipDefs[item.key],req=executiveRequirements(item.key),cover=departmentCoverage(req),sreq=vipSpaceRequirements(item.key),scover=vipSpaceCoverage(item.key),missing=Math.max(0,sreq.length-scover),spaceText=vipSpaceMissingText(item.key),body=v.icon+' '+v.name+'\n'+v.desc+'\n\n主责部门：'+req.map(function(k){return departmentDefs[k].icon+departmentDefs[k].name+(managerHired(k)?' ✓':' ○')}).join(' · ')+'\n组织覆盖：'+cover+'/'+req.length+'\n\n空间就绪：'+scover+'/'+sreq.length+' · '+spaceText+(hasSignatureSpace()?'\n✨ '+signatureSpaces[state.brand].name+' 已启用':'')+'\n\n已到岗部门会给出自己的 Playbook；没到岗时只能由 GM 花更高成本救火。';var choices=[],i,k;for(i=0;i<req.length;i++){k=req[i];if(managerHired(k)){(function(dept){choices.push({title:departmentDefs[dept].icon+' '+departmentLeadLabel(dept,item),impact:'部门主导 · 现场成本 ¥'+({front:140,house:130,revenue:90,fb:180,events:170,engineering:160}[dept]||150),sub:departmentLeadSub(dept,item),best:(cover+scover)>=Math.max(2,req.length+sreq.length-(item.level>=4?1:2)),fn:function(){resolveDepartmentLead(item,dept)}})})(k)}}if(!choices.length||item.level>=3)choices.push({title:'GM 跨部门拉通',impact:'💰 -¥'+(420+item.level*90+missing*140)+' · '+(missing>=2?'硬件风险高':'可控'),sub:'组织不成熟时你可以亲自救火，但这是最贵、最耗 GM 注意力的方式。',best:!choices.length&&missing<=1,fn:function(){resolveExecutiveVip(item,'command')}});if(missing>0&&item.level>=3)choices.push({title:'Emergency Makeover',impact:'🏗️ -¥'+(360+missing*240+item.level*40)+' · 临时补硬件',sub:'适合硬件真的没到位时救今晚；不会永久提高空间等级。',fn:function(){resolveExecutiveVip(item,'makeover')}});if(cover>=req.length&&scover>=sreq.length)choices.push({title:'让 Leadership Team 自行结案',impact:'👥 全部门 / 全空间就绪',sub:'组织真正成熟后，GM 只看结果，不再亲自选战术。',best:true,fn:function(){resolveExecutiveVip(item,'delegate')}});showModal(escalationName(v.level),v.name,body,choices)}
''' +text[end:]

helper=r'''function personaPlaybookChoice(gu,p){var k=gu.personaKey||'chill';if(k==='road')return{title:'💼 极速通道：15 分钟内让他上车',impact:'👑 +1 · 🏢 +1',sub:'他根本不在乎套房，在乎别耽误行程。',fn:function(){state.rep=Math.min(100,state.rep+1);state.owner=Math.min(100,state.owner+1);regularCheckin(gu)}};if(k==='family')return{title:'👨‍👩‍👧‍👦 家庭包：加床 + 早餐 + 晚退房先排',impact:'💰 -¥120 · 👑 +2',sub:'把真正痛点一次处理掉，比空谈套房更有效。',fn:function(){if(state.cash>=120){state.cash-=120;state.stats.totalExpense+=120}state.rep=Math.min(100,state.rep+2);gu.latePending=false;regularCheckin(gu)}};if(k==='points')return{title:'🧮 先把 QN / 积分规则一次讲清',impact:'👑 +1 · 🏢 ±0',sub:'对积分党来说，“算不算”比房型更重要。',fn:function(){state.rep=Math.min(100,state.rep+1);regularCheckin(gu)}};if(k==='hunter'||k==='forum')return{title:'📱 打开房态一起看，透明说明库存',impact:'👑 -0.5 · 🏢 +0.5',sub:'不玩高楼层话术，直接把剩余套房和已锁房讲清楚。',fn:function(){markDenied(gu,p,.5,.5);gu.appWatch=false;regularCheckin(gu)}};if(k==='creator')return{title:'📸 给高楼层 + 拍摄友好房 + Welcome Drink',impact:'💰 -¥100 · 👑 +2 · 📣 曝光机会',sub:'她要的是“值得发”，不一定非要标准套房。',fn:function(){if(state.cash>=100){state.cash-=100;state.stats.totalExpense+=100}state.rep=Math.min(100,state.rep+2);recordRevenue(120);regularCheckin(gu)}};if(k==='proposal')return{title:'💍 求婚夜布置：让今晚有记忆点',impact:'💰 -¥180 · 👑 +3',sub:'这类客人对体验结果极敏感，值得单独处理。',fn:function(){if(state.cash>=180){state.cash-=180;state.stats.totalExpense+=180}state.rep=Math.min(100,state.rep+3);regularCheckin(gu)}};if(k==='whale')return{title:'💎 不硬升套，改做高消费体验包',impact:'💰 +¥260 · 👑 +1.5',sub:'把预算转成餐饮 / Spa / 接送，比白送套房更合算。',fn:function(){recordRevenue(260);state.rep=Math.min(100,state.rep+1.5);regularCheckin(gu)}};if(k==='planner')return{title:'🎤 当场给团队报价和样板房动线',impact:'💰 +¥180 · 🏢 +2',sub:'这不是一个住客，是潜在的下一张团单。',fn:function(){recordRevenue(180);state.owner=Math.min(100,state.owner+2);regularCheckin(gu)}};return null}
function openFront(){'''
r('function openFront(){',helper,'persona helper')
idx=text.index("if((state.perks||0)>0)choices.push",text.index('function openFront(){'))
text=text[:idx]+"var specialChoice=personaPlaybookChoice(gu,p);if(specialChoice)choices.unshift(specialChoice);"+text[idx:]
old="$('shareCardBtn').addEventListener('click',previewShareCard);$('postNoteBtn').addEventListener('click',postShareCard);$('personalityBtn').addEventListener('click',managerPersonality);$('resetBtn').addEventListener('click',function(){if(state.scenario&&state.scenario.active){if(confirm('退出当前 Challenge 并返回生涯吗？'))exitScenario();return}if(confirm('真的要清除《今晚有套吗？》的本地存档并重新开业吗？')){try{localStorage.removeItem(SAVE_KEY);localStorage.removeItem(LEGACY_SAVE_KEY);localStorage.removeItem(OLDER_SAVE_KEY);localStorage.removeItem(ANCIENT_SAVE_KEY);localStorage.removeItem(ANCIENT2_SAVE_KEY);localStorage.removeItem(SCENARIO_SAVE_KEY)}catch(e){}location.reload()}});"
new="function startNewCareer(){if(state.scenario&&state.scenario.active){if(confirm('先退出当前 Challenge，再新开档？'))exitScenario();return}if(!confirm('新开档会清除当前本地生涯进度，并从 Hyatt Place Day 1 重新开始。继续吗？'))return;try{localStorage.removeItem(SAVE_KEY);localStorage.removeItem(LEGACY_SAVE_KEY);localStorage.removeItem(OLDER_SAVE_KEY);localStorage.removeItem(ANCIENT_SAVE_KEY);localStorage.removeItem(ANCIENT2_SAVE_KEY);localStorage.removeItem(SCENARIO_SAVE_KEY)}catch(e){}location.reload()}\n$('shareCardBtn').addEventListener('click',previewShareCard);$('postNoteBtn').addEventListener('click',postShareCard);$('personalityBtn').addEventListener('click',managerPersonality);$('resetBtn').addEventListener('click',startNewCareer);if($('newGameBtn'))$('newGameBtn').addEventListener('click',startNewCareer);"
r(old,new,'newgame listener')
p.write_text(text,encoding='utf-8')
